### ISSUE TITLE
Confusing and inaccurate input statement names for transport efficiency sliders

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etsource#1006]
Some transport efficiency improvement sliders refer to one particular technology, but in fact update a wider category of vehicles.

We have
- `transport_car_using_diesel_mix_efficiency` <a href="etsource/inputs/demand/transport/transport_efficiency/transport_truck_using_compressed_natural_gas_efficiency.ad">file here</a>
- `transport_car_using_electricity_efficiency` <a href="etsource/inputs/demand/transport/transport_efficiency/transport_car_using_electricity_efficiency.ad">file here</a>
- `transport_truck_using_compressed_natural_gas_efficiency` <a href="etsource/inputs/demand/transport/transport_efficiency/transport_car_using_diesel_mix_efficiency.ad">file here</a>

which should be something like
- `transport_car_using_internal_combustion_engine_efficiency`
- `transport_car_and_truck_using_electricity_efficiency`
- `transport_truck_using_internal_combustion_engine_efficiency`

**Comment by michieldenhaan** [comment]
Closing, this has been fixed with last year's transport update
