### ISSUE TITLE
HHP IF-statement instead of fudge-factor in input statements

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etsource#1008]
As of now, all HHP updating input statements have an ugly fudge factor in the insulation_fraction_weighted_average formula:

```Insulation_fraction_weighted_average = (insulation_fraction_new_houses * INPUT_VALUE(households_number_of_new_houses) + insulation_fraction_old_houses * INPUT_VALUE(households_number_of_old_houses)) / (INPUT_VALUE(households_number_of_new_houses) + INPUT_VALUE(households_number_of_old_houses) + 0.0000000000000000001);```

This is done to make sure that the denominator does not become zero, which is possible if a user decides to destroy all houses.

This fudge factor should be replaced by an IF-statement which (for instance) sets the `insulation_fraction_weighted average` to 1 IF `INPUT_VALUE(households_number_of_new_houses) + INPUT_VALUE(households_number_of_old_houses) = 0`

Re-assign at will.

**Comment by ChaelKruip** [comment]
> Re-assign at will.

Assigning to @RobTerwel :laughing:

**Comment by RobTerwel** [comment]
Adding February Deploy milestone.
