### ISSUE TITLE
HHP Insulation formula correct mapping old and new houses

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etsource#1010]
In HHP updating input statements such as <a href='github.com/quintel/etsource/inputs/demand/households/households_misc/households_insulation_level_new_houses.ad' target='blank'>this one</a> @ChaelKruip and I have constructed a formula which relates the weighted average of the insulation level of old and new houses to the subtechnology of the HHP. We have mapped the insulation level formula of old houses onto [0,1], such that those values are obtained for R levels (the single variable in this formula) from [R_old_houses(max), R_old_houses(min)].

Note that we have mapped the insulation fraction for new houses onto [0,1] as well, with the latter number (the minimum isolation level) in fact of old houses, i.e. [R_new(max), R_old(min_)]. In all fairness, it should be mapped onto [R_new(max), R_new(min)]. To do so we would multiply the insulation_fraction_new_houses with a scaling factor of R_old(R_new(min)). However, since that factor is 2/15, this causes a discontinuity: the insulation fraction will be between [0 ; 2/15].

That means that initially the network_gas fraction will have its initial value, i.e. 0.2, but as soon as the user moves one of the four relevant sliders by 0.1 it will drop to about 80% of that. That _should_ actually be the initial value, but the node has 0.2 as input.value. 

Ideally we would use this scaling factor, but make sure there is no discontinuity. 

Re-assign at will.

**Comment by RobTerwel** [comment]
After discussing this with @ChaelKruip , we decided to put this on hold and pick it up when we have more time and information.

**Comment by michieldenhaan** [comment]
Closing, issue seems outdated with recent insulation/housing stock changes
