### ISSUE TITLE
Electric cooking technologies need to be added to the network calculation

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etsource#1022]
So far, `households_cooker_halogen_electricity` and `households_cooker_induction_electricity` are not included.
- [ ] These technologies need to be added to `network_lv_net_converters.gql`
- [ ] These technologies need to get simultaneousness parameters

**Comment by jorisberkhout** [comment]
Notifying @AlexanderWirtz and @dennisschoenmakers .

**Comment by dennisschoenmakers** [comment]
I thought we decided to put this on hold for now? :smile:

**Comment by jorisberkhout** [comment]
You're right! Removed the milestone.

**Comment by dennisschoenmakers** [comment]
> You're right! Removed the milestone.

:+1:

**Comment by jorisberkhout** [comment]
Cooking technologies are included in the new network calculation. Closing this issue.
