### ISSUE TITLE
Country-specific initial share or start_value_gql pick up from node

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etsource#1038]
## Background

Nodes can retrieve certain country-specific data from files (mostly .csv and .ad) as outlined in <a href="https://github.com/quintel/atlas/blob/master/lib/atlas/runtime.rb"a>runtime.rb<a/> in Atlas. 

In <a href="https://github.com/quintel/etengine/commit/13dd4ce584b1fa33ef764b1105f9dc0aebe3a5af"a>these commits<a/>, @antw implemented a way to pick up the `number_of_units` attribute from a node which enabled us to have car technology input statements set the `number_of_units` for the **future**. However, the `number_of_units` node attribute for the **present** for car technologies is country specific and should be equal to the share of the useful demand times the total number of cars in that country: 

`
QUERY_PRESENT(-> { V(transport_car_using_hydrogen, share_of_transport_useful_demand_car_kms) }) * AREA(number_of_cars)
`

or 

`(present:)V(transport_car_using_hydrogen_share) * AREA(number_of_cars)
`
## Problem

Although nodes are already able to pick up `AREA(number_of_cars)`, the problem is that ETEngine and Atlas as of now (to my knowledge) don't enable nodes to pick up these shares from queries. We do however need the present share of the useful demand, since we would otherwise face a discontinuity when one of these input statements - affecting the future - is moved and as a result changes the `number_of_units` value from 0 to the newly calculated value. The question is how to retrieve this information on the initial (i.e. present) useful demand shares and get it to the node.

@antw , 
-  is it currently possible to have a node pick up the initial shares as calculated by Atlas, and if so, how? 
-  if not, it is it possible to make this happen and if so, how hard and time-consuming would that be?

Thanks in advance!

You can find the 'work in progress' containing edited input statements on the branch `h2_number_scaling` on ETSource.

P.S. I know it is possible to export csv's containing the shares of UD from the transport analysis, but this would amount to mimicking Atlas in ETDataset and therefore duplicating calculations, introducing unnecessary risks and complexity.

**Comment by antw** [comment]
> is it currently possible to have a node pick up the initial shares as calculated by Atlas, and if so, how?

[We do this for `coupling_carrier`](https://github.com/quintel/atlas/blob/master/lib/atlas/exporter.rb#L94-L100), but it is considered a special-case. I suppose we could allow other edges to do it also, perhaps by adding a new `group` to which edges could belong: "preset_share" (we have "preset_demand" for nodes, so I think this name makes most sense). This would be pretty simple to implement.

This assumes that Atlas+Refinery already know (or can calculate) the correct share for the edge in question.

I'm not sure if this answers your question; please let me know if not.

**Comment by RobTerwel** [comment]
> I'm not sure if this answers your question

I think it does! Something like

```
      Edge.all.each do |edge|
        if edge.carrier == :car_kms
          data[edge.key] = edge.to_hash
          data[edge.key][:share] = edge.child_share
        end
      end
```

would probably suffice if it is exported as a child share `transport_useful_demand_car_kms_child_share` which looks like

```
key,share
transport_car_using_compressed_natural_gas,0.00000000000000E+00
transport_car_using_diesel_mix,0.00000000000000E+00
transport_car_using_electricity,1.00000000000000E+00
transport_car_using_gasoline_mix,0.00000000000000E+00
transport_car_using_hydrogen,0.00000000000000E+00
transport_car_using_lpg,0.00000000000000E+00
```

I just need to be able to inform every car technology node of its child share of `transport_useful_demand_car_kms` and this should absolutely do the job!

@antw , could you implement this?

**Comment by antw** [comment]
> @antw , could you implement this?

Will do. How soon do you need it?

**Comment by RobTerwel** [comment]
>  How soon do you need it?

Hmm... could it be done by tomorrow or Thursday?

**Comment by antw** [comment]
:+1:

**Comment by RobTerwel** [comment]
:gem:

**Comment by antw** [comment]
@RobTerwel I did look into this and reminded myself of [this code](https://github.com/quintel/etengine/blob/f8d79fcf526f029aba6afeb48884ea76398fe748/app/models/etsource/dataset/import.rb#L227-L232) in ETEngine. The shares of edges whose `type` is `share` should in fact *already* get their initial share set.

The edges on `transport_car_using_hydrogen` do in fact appear to be "share", so their values should already be getting set on the "present" graph.

Is ETEngine giving you a value different to the one you expect, or maybe you're receiving an error message?

**Comment by RobTerwel** [comment]
> Is ETEngine giving you a value different to the one you expect, or maybe you're receiving an error message?

The first question is a no (not as far as I know), the second one is a yes. If I 'use' the share in the node by for example setting in `tranport_car_using_hydrogen`:

```
~ number_of_units = SHARE(transport_useful_demand_car_kms_child_share, transport_car_using_hydrogen) * AREA(number_of_cars)
```
ETSource looks for a csv file called `transport_useful_demand_car_kms_child_share`, which doesn't exist yet. This is defined in Atlas in <a href="https://github.com/quintel/atlas/blob/master/lib/atlas/runtime.rb#L46-L61"a>runtime.rb<a/>

**Comment by antw** [comment]
Oh I see! It'll be looking for that file in `datasets/:country_code:/shares` and would expect its contents to look like [the CSV you posted above](https://github.com/quintel/etsource/issues/1038#issuecomment-175043067). Typically we set the share in the edge ([example](https://github.com/quintel/etsource/blob/master/edges/energy/energy_biomass_gasification_hydrogen-energy_distribution_hydrogen@hydrogen.ad#L4)), but that sounds a bit like what you objected to in the original post:

> I know it is possible to export csv's containing the shares of UD from the transport analysis, but this would amount to mimicking Atlas in ETDataset 


Normally, ETEngine will calculate the number_of_units automatically based on the demand and input capacity of the node; do things break if you remove that `number_of_units` line?

**Comment by RobTerwel** [comment]
> Normally, ETEngine will calculate the number_of_units automatically based on the demand and input capacity of the node; do things break if you remove that number_of_units line?

Yep, the `number_of_units` would be 0 if it isn't specified in the node because not all attributes necessary for the `number_of_units` calculations are given to car technologies. There is one way to circumvent this, which amounts to adding all attributes necessary for a correct number of units has already been done for <a href="https://github.com/quintel/etsource/blob/master/nodes/transport/transport_car_using_electricity.converter.ad"a>electric cars<a/>. However, giving for example gasoline cars an `input_capacity` is not very transparant and neither is it very sensible physically. But more than that, these attributes are set such that, when this car technology delivers 100% of the useful demand, the `number_of_units` is equal to the total number of cars. That number, of course, varies per country...

For these reasons the preferred approach would consist of setting the number of units like this:

> ~ number_of_units = SHARE(transport_useful_demand_car_kms_child_share, transport_car_using_hydrogen) * AREA(number_of_cars)

And yes, we (incl. @jorisberkhout and @ChaelKruip ) prefer to not export those shares from the dataset for the reason mentioned above.

Hope this clarifies things a bit!

**Comment by RobTerwel** [comment]
@antw , what is the status of this? Do you think it's still doable before the deploy?

**Comment by jorisberkhout** [comment]
@RobTerwel , does this still need to be resolved before the deploy? If not, I suggest removing the milestone.

**Comment by RobTerwel** [comment]
There are no quantitative differences in a NL dataset, so I will hereby remove the milestone.

**Comment by antw** [comment]
I am a bit stuck with this one to be honest. If it is in fact not deploy-critical, I'll take a deeper look in the coming days once the deployment is finished.
