### ISSUE TITLE
Industry gas CHP connected to MV in graph but appears in HV queries

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etsource#1052]
When looking into why <a href="https://github.com/quintel/mechanical_turk/blob/master/spec/network/network_infrastructure_investments_spec.rb#L109-L115"a>this mech_turk test for network costs <a/> failed, I stumbled upon an odd inconsistency:

The `industry_chp_combined_cycle_gas_power_fuelmix` converter is connected to the **MV** electricity grid in the graph. At the same time, it appears in <a href="https://github.com/quintel/etsource/blob/master/gqueries/modules/network/converter_groups/high_voltage_electricity_production.gql#L29"a>this **HV** electricity production query<a/>.  

Should this converter therefore be connected to the HV electricity grid in the graph or should it not appear in this HV electricity production query?

Notifying @AlexanderWirtz @jorisberkhout @ChaelKruip @dennisschoenmakers .

**Comment by jorisberkhout** [comment]
I believe the `industry_chp_combined_cycle_gas_power_fuelmix` has mistakingly ended up in the HV converter group (specified in `high_voltage_electricity_production.gql`) and should be moved to the MV converter group (specified in `network_mv_d_net_converters.gql`).

I would, however, like to hear @AlexanderWirtz ' opinion before proceeding.

**Comment by AlexanderWirtz** [comment]
I think it is quite large. 100 MWe. That would make it improbable that it is connected to anything but the HV network. Possibly to the MV-HV transformer, but even that seems a bit small. I forgot the thresholds. Chris has them documented somewhere. I would not connect it to the MV grid.

**Comment by AlexanderWirtz** [comment]
![image](https://cloud.githubusercontent.com/assets/308563/12680007/ce3cf9dc-c6a7-11e5-8990-fe8e11e11acd.png)

This suggests 100 MWe would be connected to HV, no?

**Comment by AlexanderWirtz** [comment]
![image](https://cloud.githubusercontent.com/assets/308563/12680021/e6965b54-c6a7-11e5-9b64-9df7ccd5d845.png)
Also from Network calculation documentation. This definitely suggests to put it in HV

**Comment by jorisberkhout** [comment]
Thanks for this information, @AlexanderWirtz . I agree with you that the `industry_chp_combined_cycle_gas_power_fuelmix` should be connected to the HV-net in the graph. As this is not deploy-critical, I will remove the milestone.

@RobTerwel , could you make an inventory of the work that needs to be done to move the `industry_chp_combined_cycle_gas_power_fuelmix` to the HV-net and potential fall-out of this?

**Comment by RobTerwel** [comment]
@AlexanderWirtz and @jorisberkhout , I agree as well.

> could you make an inventory of the work that needs to be done to move the industry_chp_combined_cycle_gas_power_fuelmix to the HV-net and potential fall-out of this?

Yes, I could. I would have to see with @ChaelKruip , but I think it mostly consists of adjusting some edges and gqueries. However, before I embark on this, could you tell me: 

- what is its priority? Since it is not deploy critical, could we pick it up after the deploy?
- wouldn't it be good to make an inventory of all converters which might have to be moved?

**Comment by jorisberkhout** [comment]
> - what is its priority? Since it is not deploy critical, could we pick it up after the deploy?
- wouldn't it be good to make an inventory of all converters which might have to be moved?

I put the issue on hold. Let's pick it up after the deploy, preferable as part of a general cleanup of the inputs for the network calculation as described in quintel/etmodel#2004.

**Comment by jorisberkhout** [comment]
Still relevant. In the new network calculation, this unit has been connected to the MV net, but this can easily be changed.

**Comment by MartLubben** [comment]
@AlexanderWirtz & @jorisberkhout :

I am trying to fix this issue. In my opinion another strange thing is causing this issue. The capacities of the CHP's which feed the 'industry_locally_available_electricity' are very different, between 1 - 100 MW. This is confusing to the user and causing a problem in the graph. 

We could:
- scale all CHP's to the same X MW. 
- scale the industry_chp_combined_cycle_gas_power_fuelmix to be below to 50 MW and connect it to the mv-hv transformer. 


![screen shot 2018-06-26 at 14 44 41](https://user-images.githubusercontent.com/33415156/41912312-9dd84ca8-794f-11e8-88bb-4f957299bc29.png)

**Comment by AlexanderWirtz** [comment]
> The capacities of the CHP's which feed the 'industry_locally_available_electricity' are very different, between 1 - 100 MW (see edited image). 

Confusing, but reality nonetheless. All of these actually occur: apart from the coal-fired one. That is not correct. I think there was some kind of mistake there. Scaling them is not realistic either.

**Comment by MartLubben** [comment]
@AlexanderWirtz You are right. Some weird things have happened here. 

![screen shot 2018-06-27 at 11 03 13](https://user-images.githubusercontent.com/33415156/41964294-e3b91e0a-79f9-11e8-9aec-3cb3976368fd.png)

**Comment by redekok** [comment]
@AlexanderWirtz: What is the conclusion of the discussion above? Should the `industry_chp_combined_cycle_gas_power_fuelmix` node also be connected to the HV net instead of the MV net in the graph (just like the `industry_chp_ultra_supercritical_coal` node, as discussed in https://github.com/quintel/etdataset/issues/785)?

**Comment by AlexanderWirtz** [comment]
Yes, all plants above 50 MW typically get connected to the HV grid as specified in https://github.com/quintel/etsource/issues/1052#issuecomment-176828014
