### ISSUE TITLE
BR dataset missing load_profiles, sliders don't appear

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etsource#1072]
The Brazil dataset is missing several <a href="https://github.com/quintel/etsource/tree/master/datasets/br/load_profiles"a>load profiles<a/> and sliders don't appear as a result (other datasets are fine). I tested the BR dataset briefly yesterday and sliders appeared just like I expected.

Re-assign at will.

You can find the error below: 

>
/var/www/etengine/releases/20160209154856/tmp/etsource/datasets/br/load_profiles/buildings_chp.csv is not known. Please add.↵/var/www/etengine/shared/bundle/ruby/2.1.0/bundler/gems/merit-fe96e416a8b1/lib/merit/load_profile.rb:97:in `rescue in read'↵/var/www/etengine/shared/bundle/ruby/2.1.0/bundler/gems/merit-fe96e416a8b1/lib/merit/load_profile.rb:94:in `read'↵/var/www/etengine/shared/bundle/ruby/2.1.0/bundler/gems/merit-fe96e416a8b1/lib/merit/load_profile.rb:115:in `read'↵/var/www/etengine/shared/bundle/ruby/2.1.0/bundler/gems/merit-fe96e416a8b1/lib/merit/load_profile.rb:82:in `load'↵/var/www/etengine/shared/bundle/ruby/2.1.0/bundler/gems/atlas-2dd7c1b743c8/lib/atlas/dataset.rb:196:in `load_profile'↵/var/www/etengine/releases/20160209154856/app/models/qernel/plugins/merit/always_on_adapter.rb:9:in `producer_attributes'↵/var/www/etengine/releases/20160209154856/app/models/qernel/plugins/merit/adapter.rb:30:in `participant'↵/var/www/etengine/releases/20160209154856/app/models/qernel/plugins/simple_merit_order.rb:69:in `block in setup'↵/var/www/etengine/releases/20160209154856/app/models/qernel/plugins/simple_merit_order.rb:68:in `each'↵/var/www/etengine/releases/20160209154856/app/models/qernel/plugins/simple_merit_order.rb:68:in `setup'↵/var/www/etengine/releases/20160209154856/app/models/qernel/plugins/plugin.rb:28:in `block in trigger'↵/var/www/etengine/releases/20160209154856/app/models/qernel/plugins/plugin.rb:26:in `each'↵/var/www/etengine/releases/20160209154856/app/models/qernel/plugins/plugin.rb:26:in `trigger'↵/var/www/etengine/releases/20160209154856/app/models/qernel/lifecycle.rb:59:in `block in with_callback'↵/var/www/etengine/releases/20160209154856/app/models/qernel/lifecycle.rb:58:in `each_value'↵/var/www/etengine/releases/20160209154856/app/models/qernel/lifecycle.rb:58:in `with_callback'↵/var/www/etengine/releases/20160209154856/app/models/qernel/lifecycle.rb:26:in `calculate'↵/var/www/etengine/releases/20160209154856/app/models/qernel/graph.rb:289:in `calculate'↵/var/www/etengine/releases/20160209154856/app/models/gql/gql.rb:273:in `calculate_graphs'↵/var/www/etengine/releases/20160209154856/app/models/gql/gql.rb:214:in `block in prepare'↵/var/www/etengine/releases/20160209154856/lib/instrumentable.rb:5:in `block in instrument'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/notifications.rb:159:in `block in instrument'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/notifications.rb:159:in `instrument'↵/var/www/etengine/releases/20160209154856/lib/instrumentable.rb:4:in `instrument'↵/var/www/etengine/releases/20160209154856/app/models/gql/gql.rb:214:in `prepare'↵/var/www/etengine/releases/20160209154856/app/models/scenario.rb:166:in `gql'↵/var/www/etengine/releases/20160209154856/app/models/api/v3/scenario_update_presenter.rb:73:in `perform_gqueries!'↵/var/www/etengine/releases/20160209154856/app/models/api/v3/scenario_update_presenter.rb:14:in `initialize'↵/var/www/etengine/releases/20160209154856/app/controllers/api/v3/scenarios_controller.rb:162:in `new'↵/var/www/etengine/releases/20160209154856/app/controllers/api/v3/scenarios_controller.rb:162:in `block in update'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/transactions.rb:208:in `transaction'↵/var/www/etengine/releases/20160209154856/app/controllers/api/v3/scenarios_controller.rb:160:in `update'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/action_controller/metal/implicit_render.rb:4:in `send_action'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/abstract_controller/base.rb:189:in `process_action'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/action_controller/metal/rendering.rb:10:in `process_action'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/abstract_controller/callbacks.rb:20:in `block in process_action'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:113:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:113:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'↵/var/www/etengine/shared/bundle/rub…/var/www/etengine/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:35:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/action_dispatch/middleware/params_parser.rb:27:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/action_dispatch/middleware/flash.rb:254:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/action_dispatch/middleware/cookies.rb:560:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/query_cache.rb:36:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:82:in `run_callbacks'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/action_dispatch/middleware/callbacks.rb:27:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/airbrake-3.1.16/lib/airbrake/rails/middleware.rb:13:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/railties-4.1.5/lib/rails/rack/logger.rb:38:in `call_app'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/railties-4.1.5/lib/rails/rack/logger.rb:20:in `block in call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/tagged_logging.rb:68:in `block in tagged'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/tagged_logging.rb:26:in `tagged'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/tagged_logging.rb:68:in `tagged'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/railties-4.1.5/lib/rails/rack/logger.rb:20:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/action_dispatch/middleware/request_id.rb:21:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/airbrake-3.1.16/lib/airbrake/user_informer.rb:16:in `_call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/airbrake-3.1.16/lib/airbrake/user_informer.rb:12:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/railties-4.1.5/lib/rails/engine.rb:514:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/railties-4.1.5/lib/rails/application.rb:144:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/railties-4.1.5/lib/rails/railtie.rb:194:in `public_send'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/railties-4.1.5/lib/rails/railtie.rb:194:in `method_missing'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/rack-cors-0.2.9/lib/rack/cors.rb:54:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:572:in `process_client'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/gctools-0.2.3/lib/gctools/oobgc/unicorn_middleware.rb:13:in `process_client'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:666:in `worker_loop'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.7.3.204/lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22:in `call'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.7.3.204/lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22:in `block (4 levels) in <top (required)>'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:521:in `spawn_missing_workers'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:140:in `start'↵/var/www/etengine/shared/bundle/ruby/2.1.0/gems/unicorn-4.8.2/bin/unicorn_rails:209:in `<top (required)>'↵/var/www/etengine/shared/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `load'↵/var/www/etengine/shared/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `<main>'"

**Comment by jorisberkhout** [comment]
After discussing with @antw , I realised that the missing profiles have never been there, meaning that the merit order has never been available for Brazil. This now manifests itself because the merit order is switched on by default. I will fix this by adding the Dutch load profiles to the Brazil dataset.

**Comment by ChaelKruip** [comment]
> This now manifests itself because the merit order is switched on by default.

That was my first guess as well but @RobTerwel showed me that the issue also occurred with Merit 'off'. Perhaps Merit works differently than before (needing profiles even if it's 'off') @antw? Perhaps for LOLE?

**Comment by RobTerwel** [comment]
> That was my first guess as well but @RobTerwel showed me that the issue also occurred with Merit 'off'. 

To elaborate a bit more, this occurred when I opened a clean BR scenario. When I went to settings the `Merit_order` box was not ticked (and neither did I turn it on there afterwards).

**Comment by antw** [comment]
> @antw? Perhaps for LOLE?

Profiles are indeed needed for LOLE. However this has been the case since the LOLE calculation was moved into Merit about a year ago, so it's not a recent change.

I'm guessing this issue would only appear if you chose the LOLE dashboard item, which is not shown by default.
