### ISSUE TITLE
Cherry-pick updated presets to production

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#1086]
With f3ad916c91603fc793a65e9e79cfcc5a6acaaeb8, the new SER presets have been added to master. 

@antw could you cherry-pick this to production as well please?

See https://github.com/quintel/etsource/pull/1084#issuecomment-190351661

**Comment by AlexanderWirtz** [comment]
Actually, @antw please don't yet. No rush. Sorry for the hassle, but for @jorisberkhout' demo purposes it is better to have the 'old' SER scenario on Live

**Comment by AlexanderWirtz** [comment]
Aha, I am to blame for the fact that the SER scenario's have not been updated yet. Can we go ahead and cherry pick this? Or am i too late now? :-)

**Comment by antw** [comment]
> Can we go ahead and cherry pick this?

Consider it done!
