### ISSUE TITLE
How come certain inputs have a start_value_gql PRESENT value, and others have a FUTURE value?

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etsource#1092]
When trying to find out what the erratic behaviour was behind https://github.com/quintel/etsource/issues/1091, @AlexanderWirtz and I noticed that certain inputs have a `start_value_gql` of the present (e.g. <a href="https://github.com/quintel/etsource/blob/master/inputs/demand/households/households_cooking/households_cooker_halogen_electricity_share.ad#L6"a>halogen cooking<a/>), while others have a `start_value_gql` of the future (e.g. <a href="https://github.com/quintel/etsource/blob/master/inputs/demand/households/households_cooling/households_cooling_heatpump_ground_water_electricity_share.ad#L6"a>cooling heatpumps<a/>).

Is there a reason for certain sliders having a future `start_value_gql` and other sliders having a present `start_value_gql`? When both occur within the same `share_group`, we could have situations like https://github.com/quintel/etsource/issues/1091 , where a `share_group` does not balance and inputs do not correctly update the graph.

Notifying @dennisschoenmakers and @jorisberkhout too.

**Comment by AlexanderWirtz** [comment]
As @jorisberkhout remarked in a conversation we were having about this, it seems some input statements were set to reset to the scenario value, which in itself is quite handy, as long as a default value is specified in case the `future` value is not set in the scenario file. This has not, however, been implemented consistently and here and there not even consistently within share groups.

@jorisberkhout suggested we might consider setting all start values to `future` values, **IF** specified and to `present` values if not.

**Comment by AlexanderWirtz** [comment]
This issue is of some importance for our discussions within GEA as most industrial heat demand is found in the paper industry, i.e. other industry sector. 

As I see it: 

1. Simplest fix: set all start_value_gql to future in the share group for heat demand in other industry
2. Somewhat more work: Make all of them consistent across the board in all sliders.

**Comment by ChaelKruip** [comment]
> @jorisberkhout suggested we might consider setting all start values to future values, IF specified and to present values if not.

I like this! @antw can you give us an estimate of how difficult this might be?

**Comment by antw** [comment]
> @jorisberkhout suggested we might consider setting all start values to future values, IF specified and to present values if not.

I'm having a thick moment here, sorry. If *what* is specified?

It is my understanding that if the Input has a `start_value_gql`, a hard-coded `start_value` [will never be used](https://github.com/quintel/etengine/blob/0617072fb5e88b3b58fe9a228af0f70cc6759ed6/app/models/input.rb#L200-L208).

**Comment by ChaelKruip** [comment]
> I'm having a thick moment here, sorry. If what is specified?

I think @AlexanderWirtz suggests that the start value (to which the slider is reset if the 'reset'-button is clicked) is the value of the start_gql for the present *unless* the slider-setting has been saved in the scenario before. Than the future value of the start_gql would be used.

> It is my understanding that if the Input has a start_value_gql, a hard-coded start_value will never be used.

Indeed.

**Comment by antw** [comment]
> the start value [...] is the value of the start_gql for the present unless the slider-setting has been saved in the scenario before.

What constitutes "saved before"? Sorry if I seem pedantic, but there are a couple of ways this could be interpreted and implemented:

* If the scenario is based on a preset or parent scenario, use the preset user values as start values.
* The start value is set when the user loads the ETM interface (and therefore would be updated if they refreshed the page).
* The start value is set when the user opens the slide containing the slider.

**Comment by ChaelKruip** [comment]
> What constitutes "saved before"? 

I think @AlexanderWirtz means "If the scenario is based on a preset or parent scenario, use the preset user values as start values."

@AlexanderWirtz can you confirm and clarify?

> Sorry if I seem pedantic [...]

I think you are precise for the right reasons :+1:

**Comment by RobTerwel** [comment]
> "If the scenario is based on a preset or parent scenario, use the preset user values as start values."

I believe this is indeed what @AlexanderWirtz means. 

I checked this locally: currently, regardless of whether the `start_value_gql` is defined as `present:` or `future:`, resetting a slider in *any unscaled user-saved or preset scenario* returns the slider value of the 'original` dataset. 

Let me illustrate this with two examples.
- If I open the preset scenario 'SER 2023' from the list of existing scenarios, change some shares updating inputs and then reset them, these inputs will be reset to the graph-initialized values of the latest (2013) NL dataset.
- If I open a new UK 2025 (or preset) scenario, change some shares updating inputs and save the scenario, load that scenario and reset these inputs, they will be reset to the to the graph-initialized values of the latest (2012) UK dataset.

For *user-saved scaled scenarios*, resetting share updating sliders  (after changing them) returns the input values that have been saved,  i.e. the `user_values`.  

What @AlexanderWirtz, @ChaelKruip and I would like to see is that the effect of resetting in unscaled, user-saved and preset scenario's is the same as it is in user-saved scaled scenario's: returning the `user_values` that belong to (latest) saved scenario one started out from.

- An example: suppose I open the preset scenario 'SER 2023' (whose 'mother' scenario is the 2013 NL dataset), pull some sliders and save it as a new scenario 'SER 2023 edited'. If I now load ' SER 2023 edited' , pull some sliders and reset them again, the sliders return the NL 2013 value. Instead, we would like to see the `user_values` of the saved scenario that constitutes the latest 'point of departure', i.e. 'SER 2023 -  edited'.

@antw, I hope this helps as an explanation. Could you give us a time estimate of how difficult this would be? In addition, could you (or someone else) explain what the difference is between a `start_value_gql = future:` and  `start_value_gql = present:` statement, as this does not (seem to) impact the values to which sliders are reset?

**Comment by AlexanderWirtz** [comment]
I agree with @RobTerwel , but I think it is helpful to use `start_value_gql = future: ` and `start_value_gql = present:` to clarify things here.

What we would ideally like is for all sliders to use `start_value_gql = future:`

In our understanding of things, this initializes a slider to a values someone has deliberately chosen for it in saving a scenario or creating a `scaled` scenario using the `etmodel` interface, or creating a `preset` scenario like `SER 2023 Energieakkoord`.

So we are not talking about API scenarios where users have not deliberately chosen to store a value for a slider. 

What we do not know is if changing all input statements to  `start_value_gql = future: ` always works. What if no`future` value has been specified? Will it default to the `present` value?

**Comment by jorisberkhout** [comment]
As discussed with @AlexanderWirtz , @ChaelKruip and @RobTerwel , this issue is turning into a confusion of tongues, as it now deals with two separate issues:

1. Why are some sliders set by `start_value_gql = present:` and some by `start_value_gql = future:`? (@RobTerwel's original question). This might cause erratic behaviour as described in `https://github.com/quintel/etsource/issues/1091`.
2. What is the expected behaviour of the `reset` button next to each slider in the front-end?

As discussed, I will resolve 1. by changing all occurrences of `start_value_gql = future:` to `start_value_gql = present:`. This is a temporary fix to avoid erratic behaviour like #1091.

In addition, I will create a new issue to discuss the second point.

**Comment by antw** [comment]
> For user-saved scaled scenarios, resetting share updating sliders (after changing them) returns the input values that have been saved, i.e. the user_values.

This surprises me; I can't see why this would be different for scaled scenarios.

> What we would ideally like is for all sliders to use start_value_gql = future:

Since the present graph is (supposedly) set-in stone and unchanging, it leads to the nice property that the min/max/start values can be queried once when the application loads, [and then cached](https://github.com/quintel/etengine/commit/c974c28cdfd2e80dd73e48c990fc198df936a187). Querying the future graph for all inputs would come with quite a performance penalty, and I think that's to be avoided considering that Merit-by-default undid four years of gains. :grin: 

If the request is “the start value should be inherited from the preset or ‘parent’ scenario” then I think I can come up with a better way to achieve that than resorting to using the future graph.

**Comment by RobTerwel** [comment]
> This surprises me; I can't see why this would be different for scaled scenarios.

A very quick demonstration:

Staging `scenario_id`=508234 **not scaled**
Cooling shares (1start_value_gql=future:`) set to 97% AC, 1% Air HP, 2% Ground HP.

*Before resetting* 

![screen shot 2016-03-21 at 14 22 42](https://cloud.githubusercontent.com/assets/14106387/13919980/c67ae726-ef70-11e5-9f5b-5ad86154ef51.png)

*After resetting*

![screen shot 2016-03-21 at 14 22 59](https://cloud.githubusercontent.com/assets/14106387/13919988/ca9580f0-ef70-11e5-99d6-7f933e79e5ab.png)

Staging `scenario_id`=508254 **scaled**
Cooling shares (1start_value_gql=future:`) set to 97% AC, 1% Air HP, 2% Ground HP.

*Before resetting* 

![screen shot 2016-03-21 at 14 23 26](https://cloud.githubusercontent.com/assets/14106387/13919995/d4212b10-ef70-11e5-92e1-0d65fa761340.png)

As you can see from the icon it cannot be reset - it has its 'starting' value.

**Comment by jorisberkhout** [comment]
Closed with #1101. The discussion on what the reset button next to each slider should do is continued in https://github.com/quintel/etmodel/issues/2085.
