### ISSUE TITLE
Initial_updates_preset_demands input statement features carriers which lack a timecurve

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etsource#1093]
The <a href= "https://github.com/quintel/etsource/blob/master/inputs/misc/initial_updates_preset_demands.ad"a>initial_updates_preset_demands<a/> input statement returns the production of a certain carrier from the timecurves based on the scenario year the user selects:

``
UPDATE( V(energy_production_bio_oil), preset_demand, TIME_SERIE_VALUE(energy_production_bio_oil,preset_demand,USER_INPUT())
      )
``

However, for `bio_oil` and `bio_ethanol`, these timecurves do not exist. As a result, this input updates the production with the value 0 and the primary production in the future is always zero; hence, we import that carrier based on the scenario's demand. This has implications for import, export and the biofootprint calculation.

To fix this, we could either add timecurves for `bio_oil` and `bio_ethanol` (the ETDataset way) or remove them from this input statement (which amounts to assuming that the future production will always be equal to that of the dataset's year's) (the ETSource way).

@ChaelKruip @jorisberkhout @AlexanderWirtz , what are your thoughts and preferences?

**Comment by ChaelKruip** [comment]
I have the feeling that it will be hard to find production curves for these carriers right @jorisberkhout @AlexanderWirtz ? Therefore, I would opt for a constant, non-zero production.

**Comment by AlexanderWirtz** [comment]
> I have the feeling that it will be hard to find production curves for these carriers right @jorisberkhout @AlexanderWirtz ? Therefore, I would opt for a constant, non-zero production.

Production curves are not feasible since the attractiveness of these carriers very much depends on policy. Removing them from the input statement is therefore the most feasible option. I would say an update statement to set this to zero should we want to, is no luxury. This doesn't have to come with a slider, but occasionally WE want to be able to set things to zero.

**Comment by RobTerwel** [comment]
> I would say an update statement to set this to zero should we want to, is no luxury.

<a href="https://github.com/quintel/etsource/tree/master/inputs/adjust_scaling/supply"a>Such input statements have just been created for scaled scenarios.<a/>

After discussing this with @jorisberkhout who also agrees with this decision, assigning myself to remove `bio_oil` and `bio_ethanol` from the input statement.
