### ISSUE TITLE
Biofootprint calculation takes into account import and export (whichever exists)

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etsource#1094]
First of all: sorry for the wall of text, but feel free to skip to the impact! 
### Current implementation

Nodes which belong to the `bio_footprint_calculation` group take part in the bio-footprint calculation. This group is and should be MECE-organised, as we would otherwise attribute too much land to a certain carrier. Currently, we take into account the _gross demand_: production and import. 
### Problem

Since nodes in this `bio_footprint_calculation` group are distribution nodes, they are often connected to import, export and production nodes. In this implementation we therefore also count the **excess** production - which is exported. Since the flow through the distribution nodes contributes to the biofootprint calculation, we are attributing both the import and export biofootprint to one country. This is inconsistent and means that if we add up all countries' bio-footprint calculations we would find we are using `areable_land` that is greater than the `areable_land` that is actually being used (provided there is import and export). The current calculation is therefore quite a 'worst-case' approach to a country's biofootprint - a good illustration is the biodiesel footprint which currently also counts tens of PJs of export.

![screen shot 2016-03-14 at 09 42 27](https://cloud.githubusercontent.com/assets/14106387/13739397/4b24bb42-e9cb-11e5-8862-d38a07ed639d.png)
### Discussion

An alternative to this implementation is a more energy-oriented calculation in which we would only count the biofootprint of the biomass that a country actually _consumes_ - taking into account the _net demand_ instead of gross demand.  In this way, adding up the biofootprint of all countries should give the correct footprint (which the current implementation doesn't). On the downside, with this alternative calculation it is conceivable a country produces a lot of biomass but exports it, with the result that we don't take into account _all_ biomass production and its biofootprint. 
#### Impact

On my local ETM I checked the difference between these implementations by just removing `energy_distribution_biodiesel` and putting `transport_final_demand_biodiesel` instead in the `bio_footprint_calculation`. The **bio-footprint dropped from 0.6 times NL to 0.2 times NL** in a clean NL 2050 scenario.

Notifying @AlexanderWirtz @dennisschoenmakers @jorisberkhout @ChaelKruip - please share your thoughts on these two implementations (or alternative ones).

**Comment by RobTerwel** [comment]
Any thoughts on this, @AlexanderWirtz , @dennisschoenmakers , @jorisberkhout @ChaelKruip ?

**Comment by RobTerwel** [comment]
After discussing this with @dennisschoenmakers , we came up with the following. 

- Both approaches to the footprint calculation (i.e. energetic and land-based) are relevant.
- It would be very instructive to have a little ?-icon explaining what the method underlying the biofootprint calculation is.
- It could be an idea to include *both*, in a fashion similar to our dashboard items for CO2-emissions and domestic CO2-emissions.  We would then have to choose the 'default' biofootprint calculation and one alternative biofootprint.

Currently we have a calculation that takes into account both production (land-based) and import (energetic). The idea is to split it in two: one demand-based, energetic biofootprint calculation which is based on the final demand for all carriers (therefore includes primary production and import if present) and a land-based calculation which is equal to the total biomass production of a country (and thus includes export if present). As a result, the first one has a biofootprint that goes up to multiples of that country's `areable_land`, but the second by definition cannot exceed a country's `areable_land`. As you can see from the scheme below, this means (if my reasonings is correct) we have all bases covered and could split the current biofootprint calculation into two separate, more meaningful ones.

|Implementation|Import|Total Production of Country|Primary Production for Consumption|Export|
|---|---|---|---|---|
|Current|Yes**|Yes|Yes*|Yes|
|**new**:Energetic |Yes**|No|Yes|No|
|**new**:Land-based |No|Yes|Yes*|Yes*|

'*' means it is only taken into account insofar as it is included in the total production (but not separately), i.e. when total production exceeds primary production for consumption.

'**' means it is only taken into account insofar as it is included in the primary production production for  consumption (but not separately), i.e. when primary production for consumption exceeds the total production of that country.

Find a mockup below, names are just working definitions I haven't given much thought yet:

![screen shot 2016-03-23 at 17 17 52](https://cloud.githubusercontent.com/assets/14106387/13992377/275a0dfe-f11c-11e5-946c-8b43f5e48a11.png)

**Comment by ChaelKruip** [comment]
> After discussing this with @dennisschoenmakers , we came up with the following.

I like it!
Note that this would duplicate the number of bio-footprint charts as well (currently one).

**Comment by RobTerwel** [comment]
> Note that this would duplicate the number of bio-footprint charts as well (currently one).

Good point!

**Comment by AlexanderWirtz** [comment]
I like it a lot. This split also forces us to take a close look at the production side of things. Does biodiesel production really claim this much arable land or is it done more in such a way that it does not claim additional arable land. Through crop rotation for example, which actually increases yields per km2 for food and biomass.

**Comment by dennisschoenmakers** [comment]
@ChaelKruip:
> I like it!

@AlexanderWirtz 
> I like it a lot.

**Everybody**
![](https://45.media.tumblr.com/82a98ba71d60495ae0789aa876429f7f/tumblr_n0cpp9fflP1sia4voo1_400.gif)

**Comment by redekok** [comment]
@marliekeverweij Do you think we can close this issue now that we're offering other dashboard items?

![image](https://user-images.githubusercontent.com/5946498/71659343-89707d00-2d47-11ea-8a67-8a93d9eadcd8.png)

**Comment by marliekeverweij** [comment]
Yes let's do it! 

Minor thing: we should update the group name of the biomass dashboard items, since 'Bio-footprint' is not suitable anymore. I'll do that.
