### ISSUE TITLE
How to create a preset scenario for a scaled scenario?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etsource#1109]
I am trying to create a preset scenario for Ameland from its database scenario (id = 515530 on the staging database). I have copied the inputs and other data to an `.ad` file (see excerpt below), but this does not reproduce the original scenario. It seems like it is missing data on the scaling (except for those parameters that are explicitly scaled by an input).

Do you have any idea how to create a preset for a scaled scenario, @antw or @grdw ?

```
- id = 515530
- description =
- title = Ameland
- display_group = Regionaal
- end_year = 2020
- preset_scenario_id = 515529
- in_start_menu = true
- use_fce = false
- area_code = nl
- user_values.number_of_energy_power_solar_pv_solar_radiation = 0.0
- user_values.number_of_energy_power_solar_pv_solar_radiation_present = 0.0
- user_values.buildings_useful_demand_for_space_heating_both = 21.5
...
```

Related to https://github.com/quintel/etengine/issues/835.

**Comment by antw** [comment]
Currently not possible since the scaling data is saved in a different database table. I'll see what we can do about that.

**Comment by jorisberkhout** [comment]
Thanks @antw , I'll discuss with @dennisschoenmakers to see how badly we want this.

**Comment by jorisberkhout** [comment]
Closing this issue as the actionable item is in https://github.com/quintel/etengine/issues/842.
