### ISSUE TITLE
Heat source GQL's break in ETEngine

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1128]
In the `etmoses-heat-network` branch there are gql files located at:

`gqueries/modules/etmoses/etmoses_average_lifetime_of_must_run_central_heat_network.gql`
`gqueries/modules/etmoses/etmoses_average_marginal_cost_of_must_run_central_heat_network.gql`
`gqueries/modules/etmoses/etmoses_total_investment_cost_of_must_run_central_heat_network`

This gql calls another gql that does not exist: `etmoses_installed_capacity_of_must_run_central_heat_network`, which causes ETEngine to raise a 422 error and therefor some problems arise testing ETMoses. I can't find the gql file it's trying to call in ETSource (also after a `git up`).

**Comment by ChaelKruip** [comment]
Fixed with https://github.com/quintel/etsource/commit/f667c1f1e2543c0585785b5d2367f59d37b80f1d

**Comment by grdw** [comment]
There's something else not entirely correct here.. (I'm sorry) 

This took my quiet some time but there's still something wrong with  the `Q(etmoses_heat_produced_by_must_run_central_heat_network)` part in `etmoses_average_marginal_cost_of_must_run_central_heat_network.gql` . Turns out that it returns `nil` but appearantly after some fiddling and searching in my ETSource folder it turns out that every key that does not exist within the `Q()` method just plainly returns `nil`. In other words: `etmoses_heat_produced_by_must_run_central_heat_network.gql` is missing.

**Comment by ChaelKruip** [comment]
> There's something else not entirely correct here.. (I'm sorry)

My bad!

Please use dummy values for now. I'm getting less and less convinced that we should try to get these numbers from the ETM...
