### ISSUE TITLE
Dashboard cost item includes the fuel costs of just one application of a combi technology

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etsource#1133]
The mechanical turk fails since we imported 634787b28eaa87e1cbc54948d8a4394b888debd1 in Beta ETEngine. In this commit we fixed the double counting of the investment costs for the combi technologies by taking into account only the `total_costs` for the most expensive of both applications of that combi technology.

I now realise that by correcting the `total_costs`, we not only correct the `fixed_costs` but also the `variable_costs`, which include the fuel costs. Hence, the dashboard cost item now only takes the fuel costs for one of the two applications (the most expensive) into account.

I think the solution would be to replace `total_costs` with `fixed_costs` in all Gqueries in 634787b28eaa87e1cbc54948d8a4394b888debd1, but would like to sit down with @ChaelKruip before we do this to avoid any further mistakes.

I believe that fixing this issue, will also fix the mechanical turk failing.

**Comment by ChaelKruip** [comment]
Well spotted @jorisberkhout! 😨

**Comment by jorisberkhout** [comment]
Assigning myself.
