### ISSUE TITLE
What is sustainable attribute used for in waste_mix since child shares are set by ETDataset

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etsource#1136]
I came upon this by accident. Not urgent. The `waste_mix.ad` files contains:

```
- sustainable = 0.38
- infinite = false
- graphviz_color = darkgrey
```

This made me wonder why this 0.38 number is not 0.55 as is the case in the NL. After some digging I realized the shares in `energy_distribution_waste_mix_child_share.csv` are updated by the Primary production analysis in `ETDataset`. For NL this produces the correct mix of 55% `biogenic_waste` and 45% `non_biogenic_waste`. 

If the shares and therefore its sustainability are set elsewhere what is the attribute `sustainale` used for then? Can it be removed?

**Comment by jorisberkhout** [comment]
Removing milestone.
