### ISSUE TITLE
Improve load profiles for must-run technologies

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etsource#1145]
As I discovered while looking at one of the new merit order charts, the load profiles for the must-run technologies (`agriculture.csv` and `buildings.csv`) are no longer aligned with the total demand profile (I would expect the five peaks in e.g. dark red to coincide with the five highest peaks of the (bright red) demand profile in the chart below).

I suggest picking this up as part of the `NL 2014 update` since 2014 starts on a different day than 2013 and we need to reconsider the profiles anyway.

Notifying @AlexanderWirtz and @ChaelKruip .

<img width="624" alt="screen shot 2016-07-19 at 17 19 35" src="https://cloud.githubusercontent.com/assets/4669028/16955942/ce60885a-4dd6-11e6-8a73-ff82a27685df.png">

**Comment by AlexanderWirtz** [comment]
well spotted! Agree with the suggested milestone

**Comment by TessColijn** [comment]
The misalignment starts at the beginning of the year. 1st of January is a Tuesday but the profile for 'agriculture_chp_engine_network_gas' starts on a sunday. 

![image](https://cloud.githubusercontent.com/assets/22587085/19079863/5cfbff3a-8a55-11e6-9ce1-4241c21c3b64.png)

Until the week of 28th of February this misalignment of 2 days continues. Around the end of February there is another issue where the 'agriculture_chp_engine_network_gas' only provides an output for 4 days.

![image](https://cloud.githubusercontent.com/assets/22587085/19080664/0cb2ec5c-8a58-11e6-8568-8822b50520c6.png)

After the week of the 28th of february the misalignment between total demand and 'agriculture_chp_engine_network_gas' differs by one day.

![image](https://cloud.githubusercontent.com/assets/22587085/19080726/3c42fffc-8a58-11e6-9d8a-59f1afa3cd6a.png)
