### ISSUE TITLE
Modelling behaviour of CHPs

### ISSUE THREAD

**Issue by TessColijn** [quintel/etsource#1174]
I have attempted to summarise the current status of the discussions around CHPs and the major problems concerning modelling their behaviour. I have tried to bring together the previous issues: https://github.com/quintel/merit/issues/80, https://github.com/quintel/merit/issues/85, #277, #890  #912 
### The three main issues that arise are:
1. FLH(profile) do not match the FLH(data) which gives loads above installed capacities
2. Rest capacity of must-runs should be used in the merit order. The must-runs should not be Must-not-runs during inactive hours. 
3. If CHPs participate in the merit order we need to take into account that they can sell the heat produced. This will influence marginal costs of the CHPs and thus their role in the merit order. 
   ### Current situation:

**CHP profiles:**
For Current profiles assigned to CHPs see issue #277. All industry profiles are flat. All agriculture profiles follow a Monday-Friday schedule as described in: 'Agriculture_Chps.md'. The buildings profile gives a varied profile. Unfortunately, no documentation for this profile exists. 

**Research Data provides:** 
- Full load hours of technology
  *effective capacity/unit
  *availability 

**User:**
- number of units for agriculture and industry
- percentage share for buildings and households

**The discrepancies between FLH(profile) and FLH(data) can be described as follows:**

`
E = FLH * Cap/unit * NoU
`

If user adds more units, total energy output increases. The profile matched to the particular technology is scaled such that surface area is equal to the energy output. This can result in situations where the CHPs are running above the installed available capacity. 

Let us assume FLH(profile)= total(profile)/max(profile). In the case of an unrealistic loads the FLH(profile)< FLH(data). https://github.com/quintel/etsource/issues/912

With flat profiles this is not a problem as the output capacity <= installed available capacity. For flat profiles FLH(profile)>= FLH(data).

**CHPs that are currently included in merit order table as dispatchable:**

`energy_chp_ultra_supercritical_coal`
`energy_chp_ultra_supercritical_cofiring_coal`
`energy_chp_ultra_supercritical_lignite`
`energy_chp_combine_cycle_network_gas`
### Possible approaches to solutions to the problems:
1. Develop a merit order for heat including CHPs, watertanks used as buffer and other heat technology. This merit order will need to fulfil various conditions:
   1.    It should be sector specific (ie a different merit order per sector) such that heat for the agricultural sector is obtained from `agriculture_chps` and not `industry_chps`.
   2.    Users play an active role in demand and supply of heat by CHPs(ie is there a surplus or a shortage of heat?). This will most likely be in the form of a slider for number of units.
   3.    Electricity produced by CHPs can still be considered a must-run in electricity merit order.
   4.    CHPs would then play a role in the heat merit order and the electricity merit order. Decisions will have to be made which merit order takes priority. This could also be a dynamic decision that adjusts to cost and price.
   5. Can the demand curve for heat be time dynamic?
2. Adjust profiles to correct current issues such that FLH(profiles)=FLH(data). In order to prevent issues with dataset updates, it would in this case also be useful to design the profiles in such a way that they can be adjusted to changes in FLH(data). In this cases decisions will have to be made to determine how the profile will be adjusted. For example, for agriculture CHPs will more full load hours be realized with a shorter summer, or active hours in the weekends? One goal should be to design the profile in such a way that rest capacity can be determined and used in the merit order as a possible electricity source. 
3. Simple solution: give all CHPs a static flat profile.
4. (Not sure about this one) Would it be possible to model some of the more problematic CHPs such as agriculture as a volatile. From the documentation: https://github.com/quintel/documentation/blob/master/modules/merit/profiles_how_to.md , I understand that a load curve would need to be modelled based on data Ie wind speeds. Could this data be temperature coupled with the size of the space needing heating? 
5. What would happen if we let CHPs be dispatchables? Then we let the load of CHPs be dependant on the electricity price. If the electricity price is low the CHPs are not needed. If the price is high CHPs provide an alternative electricity source. In this case their should be a check or a visualisation if the heat demand (for example for greenhouses) is met. Don't we have something like that? We could give a sector specific mekko which enables the user to recognise excess and shortages in heat and decided how to resolve the shortage.

Note:  To correctly include CHPs in any merit order, marginal costs have to be modelled correctly to take both heat production and electricity production into account. See #236 and #887.

**Comment by TessColijn** [comment]
Here and overview of the CHP issue so far @ChaelKruip @jorisberkhout @AlexanderWirtz

**Comment by AlexanderWirtz** [comment]
Thanks @TessColijn . Have you also noted the issue on marginal costs for dispatchable CHPs? This involves taking into account only the fuel used to produce electricity for CHPs with a steam cycle (where heat is not produced as a waste product), and not the fuel used to generate heat when calculating marginal costs. This is clearly a separate issue, although it is related if you were to implement solution 1.

As far as your solutions are concerned: 
I do not think **1** will work, as we will get a feedback loop. CHPs producing heat also produce power, which will affect the electricity merit order. Or is there something I am missing?
I do not think **3** is realisic, so perhaps **2** is preferable? I haven't given this enough thought though

**Comment by michieldenhaan** [comment]
Closing, option 5 is now implemented
