### ISSUE TITLE
Primary demand calculations based on nodes and edges should give the same result

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#1178]
Queries such as:
```
V(energy_heat_network_unused_steam_hot_water, primary_demand) = 17755169863.350967
```

should give the same result as (not an actual working query)
```
V(energy_heat_network_steam_hot_water-energy_heat_network_unused_steam_hot_water@steam_hot_water, primary_demand) = 16018086904.6281
```

I see the same type of difference with electricity. 

Perhaps a different recursive method is used for edges and nodes?

**Comment by antw** [comment]
Was there a specific scenario in which you observed this? I'm not seeing it on beta. The `primary_demand` methods on `Link` is basically `value from right converter` × `conversion` × `parent_share`.

A 2040 NL scenario, `present` graph:

```ruby
V(energy_heat_network_steam_hot_water, primary_demand)
# => 155,004,116,273.1732
```

```ruby
V(
  OUTPUT_LINKS(
    V(energy_heat_network_steam_hot_water),
    "lft_converter.key == :energy_heat_network_unused_steam_hot_water"
  ),
  primary_demand
)

# => 33,278,362,488.174786
# =  155B * 0.828... (conversion) * 0.259... (parent_share)
```

**Comment by ChaelKruip** [comment]
I used the PRESENT values for a clean BE 2030 scenario:
```
TXT_TABLE(LG(final_demand), key, demand, primary_demand)
```
and 
```
TXT_TABLE(G(final_demand_group), key, demand, primary_demand)
```
and compared the line about the `energy_heat_network_unused_steam_hot_water` in the latter to the corresponding one in Excel:

Edges:
![20161025_consistency_check_v03_xlsx](https://cloud.githubusercontent.com/assets/1303760/19683795/27cf566c-9ab4-11e6-8dfc-e30a15e0c56b.png)

Nodes:
![screenshot_25_10_2016__13_10](https://cloud.githubusercontent.com/assets/1303760/19683861/75504a90-9ab4-11e6-9d2d-d269381bbe00.png)
