### ISSUE TITLE
Explore ideas related to folder structure of etsource

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1180]
When creating a local dataset, does it hold all the same `ad` files as a country dataset? To elaborate: is a local dataset the same as doing:

````
# For example:
cp -r datasets/nl datasets/nl_amsterdam
````

---

There are multiple approaches

We could do it as such:

````
datasets/nl
├── demands
...
├── shares
└── time_curves

datasets/nl_amsterdam
├── demands
...
├── shares
└── time_curves
````

or we could nest the datasets. Or keep everything at one level and symlink certain directories and pretend as though everything is nested.

**Comment by ploh** [comment]
> we could nest the datasets. 

in what way would we nest it? does it not have to follow the same structure as country datasets do - in order to be readable by etengine (or is that atlas here)?

> keep everything at one level and symlink certain directories and pretend as though everything is nested.

symlink from the original country dataset that the local dataset was created from?

**Comment by grdw** [comment]
> in what way would we nest it?

In such a fashion:

````
nl
├── demands
├── efficiencies
├── fce
├── load_profiles
├── local_datasets
│   └── nl_amsterdam
│       ├── demands
│       ├── efficiencies
│       ├── fce
│       ├── load_profiles
│       ├── network
│       ├── shares
│       └── time_curves
├── network
├── shares
└── time_curves
````

**Comment by ploh** [comment]
@grdw Please describe our current implementation as well as our ideas (datasets/full_datasets/nl + datasets/derived_datasets/ameland; datasets/nl + datasets/nl/derived/ameland; datasets/nl/full + datasets/nl/ameland; ...)

**Comment by grdw** [comment]
Out current implementation is as follows:

````
datasets/nl
├── nl.full_dataset.ad
├── demands
├── efficiencies
├── fce
├── load_profiles
├── network
├── shares
└── time_curves
````

````
datasets/ameland
├── ameland.derived_dataset.ad
├── graph.yml
└── time_curves
````

They live on the same level as a 'dataset'. The `derived_dataset` and `full_dataset` '.ad'-prefixes map to the corresponding class inside of Atlas.

**Comment by grdw** [comment]
https://github.com/quintel/etlocal/issues/33

**Comment by ChaelKruip** [comment]
Can we close this @grdw?

**Comment by grdw** [comment]
Sure! 👍
