### ISSUE TITLE
Rake Task: create an initial local dataset

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1182]
Specify:

- rake task with `number_of_residences` as an argument, and a country like `nl`. 
- automatically generate a scaled down dataset

**Comment by ploh** [comment]
#1179

**Comment by ploh** [comment]
Needed by #1179

**Comment by antw** [comment]
This is a bit of a nitpick, but Atlas is responsible for *managing* ETSource ([especially automated tasks](https://github.com/quintel/atlas/tree/master/lib/tasks)), so this issue probably belongs [over there](https://github.com/quintel/atlas/issues). Issues on this repo are normally focused on data problems ("industry demand is too high", "query *x* is returning an odd value", ...).

Generally speaking: modelling/data issues: ETSource, code issues: Atlas.

**Comment by grdw** [comment]
Superseded by https://github.com/quintel/atlas/issues/52
