### ISSUE TITLE
NL 2012 dataset is no longer working, possibly due to energy balance not being decrypted

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etsource#1189]
I ran into issues with the `nl2012` dataset locally and see the same happening in the Beta-server. I figured out that the `energy_balance.gpg` was not properly decrypted locally. After updating my `gnupg`, everything worked fine locally. I am assuming that the same thing is happening on the Beta server. Could someone look into this with some priority, as the `nl2012` dataset is used for a rather important scenario of one of our customers?

Pinging @antw and @grdw .

**Comment by grdw** [comment]
I got an error at Airbrake:

> Load profile at /var/www/etengine/releases/20161103162430/tmp/etsource/datasets/nl2012/load_profiles/agriculture_chp.csv is malformatted. It needs to contain 8760 / n points.It now has 8784 points.

**Comment by antw** [comment]
Yep; [the load profile](https://github.com/quintel/etsource/blob/master/datasets/nl2012/load_profiles/agriculture_chp.csv) is too long.

**Comment by grdw** [comment]
It also turned out that the energy_balance.csv files were missing on beta:

![screen shot 2016-11-07 at 11 26 10](https://cloud.githubusercontent.com/assets/2676542/20054380/0119f79c-a4dd-11e6-90e3-0ad8028c0ed7.png)

I just ran `rake decrypt` and there they were again.

**Comment by antw** [comment]
It is correct for the energy_balance.csv files to not be present in the ETSource directory (hint: NL was working fine without it). [ETEngine will decrypt them automatically](https://github.com/quintel/etengine/blob/221fbf0eab973f73adbb8b5ddc91928ad09c99a7/app/models/etsource/base.rb#L68) when checking out an ETSource commit into `etengine/tmp/etsource`.

Can you remove them again from the ETSource directory please? That they exist in the Git clone will probably break ETEngine, because it won't overwrite a file which already exists.

**Comment by grdw** [comment]
> Can you remove them again from the ETSource directory please? 

Yes. 

> It is correct for the energy_balance.csv files to not be present in the ETSource directory
> That they exist in the Git clone will probably break ETEngine

Oops, didn't know that. 😓

**Comment by jorisberkhout** [comment]
Thanks for looking into this @grdw and @antw and apologies for any confusion. @TessColijn fixed the length of the load profile in https://github.com/quintel/etsource/commit/f16610f98c7f87cb29ccdc619c3242271b047805. However, the `nl2012` dataset is still not working on Beta ETEngine as witnessed when creating a new `nl2012` scenario straight from ETEngine. Could anyone check for any Airbrake errors that might give a clue on what going on? @antw , @grdw , perhaps?

**Comment by antw** [comment]
`electricity_output_capacity` for energy_interconnector_imported_electricity is returning `nil`. This is set with an `interconnector_capacity` `AREA` attribute in Atlas. That attribute is not present for the 2012 dataset.

* [nl](https://github.com/quintel/etsource/blob/5645d6d8008097dbfd5440206086eedacf712aca/datasets/nl/nl.ad)
* [nl2012](https://github.com/quintel/etsource/blob/5645d6d8008097dbfd5440206086eedacf712aca/datasets/nl2012/nl2012.ad)

**Comment by antw** [comment]
I have copied across the 2013 value since I expect it didn't change much in 12 months. Please adjust as you see fit.

I also added a validation to Atlas to prevent that happening again.

**Comment by jorisberkhout** [comment]
My bad! Thanks for fixing this @antw !
