### ISSUE TITLE
Format of an initializer input

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1206]
I'm currently investigating a little bit into the format of an initializer input and what they might look like. The thing I came up with is that the only mandatory attribute I see these `.ad` files having are the `query` key. So for example:

````
- query = UPDATE(V(energy_production_bio_oil), demand, USER_INPUT())
````

From my point of view the `update_period`  and/or the `priority` don't make any sense. This is because the `priority` is `Infinity`; they'll always run first; before any of the other inputs and the `update_period` is always "both".

**Comment by grdw** [comment]
Including @AlexanderWirtz @DorinevanderVlies @jorisberkhout @ChaelKruip

**Comment by antw** [comment]
> This is because the priority is Infinity; they'll always run first

I can foresee them having a `priority`. Their priority is certainly infinite relative to *normal* inputs, but it might still be the case that you want to ensure that one initializer input is executed prior to another.
