### ISSUE TITLE
Derived datasets: Allow scaling to other area attributes

### ISSUE THREAD

**Issue by ploh** [quintel/etsource#1208]
Currently, `rake scale` accepts only `NUMBER_OF_RESIDENCES` as scaling attribute, i.e. if the user for example only knows the `number_of_inhabitants`, she has to manually calculate the corresponding `number_of_residences` before creating the derived dataset.

It should be possible to specify the scaling factor via any one of the following:
```
number_of_residences
number_of_inhabitants
areable_land
number_of_buildings
number_of_cars
```

**Comment by ploh** [comment]
@AlexanderWirtz @jorisberkhout @DorinevanderVlies Do you agree with the above list of area attributes whose value may be used as the base for the scaling factor?

**Comment by jorisberkhout** [comment]
I would limit the list to `number_of_residences` and `number_of_inhabitants`. Most energy flows scale directly with these parameters. I don't see a very direct link between the energy flows and the other parameters.

**Comment by grdw** [comment]
Closing this issue as this is highly unlikely to happen any time soon.
