### ISSUE TITLE
Initializer input present number of units value doesn't correspond with the future

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1209]
````
- query =
    EACH(
      UPDATE(V(energy_chp_supercritical_waste_mix), number_of_units, USER_INPUT()),
      UPDATE(L(energy_chp_supercritical_waste_mix), preset_demand_by_electricity_production, V(energy_chp_supercritical_waste_mix, production_based_on_number_of_units))
    )
- priority = 1
- max_value = 300.0
- max_value_gql = present:MAX(1.0,DIVIDE( DIVIDE( Q(total_electricity_produced), V(energy_chp_supercritical_waste_mix,maximum_yearly_electricity_production_per_unit) ), 10 ))
- min_value = 0.0
- start_value_gql = present:V(energy_chp_supercritical_waste_mix,number_of_units)
- step_value = 0.1
- unit = #
````

This initialzier input doesn't appear to work. The `number_of_units` isn't correctly set for the future eventhough the input is correctly passed in the future graph; afaik.

**Printscreen from ETEngine:**

![screen shot 2017-01-16 at 17 28 04](https://cloud.githubusercontent.com/assets/2676542/21991015/479d453c-dc11-11e6-9c0c-b3dd4018a366.png)

----

My question is if this is a property specific thing or? What could be the problem?

**Comment by antw** [comment]
I don't see anything which would prevent this from being executed with the `future` graph. Presumably the `USER_INPUT()` is 0.5, and the `present` graph is getting the correct value?

* Do other initializer inputs apply their values correctly to both graphs?
* Perhaps [insert a debugger here](https://github.com/quintel/etengine/blob/314fe6a5ad73352a74e5bcccf8de1a2a13f21daa/app/models/gql/gql.rb#L345) and assert that the input is actually executed for the `future` graph. You can [go deeper](https://github.com/quintel/etengine/blob/314fe6a5ad73352a74e5bcccf8de1a2a13f21daa/app/models/gql/query_interface/base.rb#L58) and debug where the actual query string is executed (remember that it should appear twice; once for each graph).
* [The previous line](https://github.com/quintel/etengine/blob/314fe6a5ad73352a74e5bcccf8de1a2a13f21daa/app/models/gql/gql.rb#L344) refers to the init. inputs on the `present` graph. I don't expect that it will, but does using inputs from the `future` graph have any effect?

**Comment by grdw** [comment]
> Do other initializer inputs apply their values correctly to both graphs?
> Perhaps insert a debugger here and assert that the input is actually executed for the future graph. 

I checked that and that seems to be fine. 

I think I need to investigate a little further as specified by you:

> You can go deeper and debug where the actual query string is executed (remember that it should appear twice; once for each graph).

> The previous line refers to the init. inputs on the present graph. I don't expect that it will, but does using inputs from the future graph have any effect?

That seems highly unlikely - although it looks confusing at first sight I think that's probably not it.

**Comment by grdw** [comment]
Maybe the future is altered *after* the initializer input fired but I need to validate that.

**Comment by ploh** [comment]
@grdw Does this problem still exist?
If you cannot reproduce it anymore, I would suggest to close this issue. After all, I successfully managed to migrate an old scaled scenario to a derived dataset. Hence, there is a good chance that this was unrelated to the derived dataset machinery.

**Comment by grdw** [comment]
> @grdw Does this problem still exist?

I think not but I need to validate that though. I can't remember if I solved this yes or no. I'll take another quick peak.

**Comment by grdw** [comment]
![screen shot 2017-02-01 at 13 56 19](https://cloud.githubusercontent.com/assets/2676542/22507615/a96e8088-e886-11e6-9253-beb1dc4aafa0.png)

This is solved!
