### ISSUE TITLE
How to know if you're energy_balance.csv files need an update?

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1211]
Today @ChaelKruip and I were debugging @DorinevanderVlies laptop because one final demand (`industry_useful_demand_for_chemical_refineries_useable_heat`) didn't match. It took some time to figure out that the `energy_balance.csv`'s were old. Because those files are not checked into git for obvious reasons it would be nice if git were smart enough to automatically run `rake decrypt` once any of the `energy_balance.gpg` files are changed.

This could be done by using a [git-hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks)?

**Comment by grdw** [comment]
Include @antw @ChaelKruip @dennisschoenmakers

**Comment by marliekeverweij** [comment]
Is this issue still relevant? Removing the 'Bugs' label as it is a minor issue

**Comment by DorinevanderVlies** [comment]
> Is this issue still relevant?

Not sure...

**Comment by DorinevanderVlies** [comment]
Remarkably enough I ran into this issue again today.

I don't fully understand Gerard's solution, but it sounds like a nice fix
