### ISSUE TITLE
A new set of initialiser inputs need to replace the inputs currently used for scaling local datasets

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#1212]
I think we
* should start with a fresh set of initialiser inputs (perhaps having the word "initialiser" in the name to distinguish them from the rest)
* put them in their own directory (the initialiser_input directory seems fine)
* design them to be the 'necessary and complete' set of inputs to change anything a researcher would want to change
* write them in such a way they do not depend on the end-year (so no %/year type update statements)

**Comment by ploh** [comment]
I would suggest to have the migration script automatically create new initializer inputs corresponding to the inputs currently used in the migrated scenarios' user_values.
This should be pretty easy and this way we can get started quickly without having to rethink every scenario's/dataset's setup.

**Comment by ChaelKruip** [comment]
> I would suggest to have the migration script automatically create new initializer inputs corresponding to the inputs currently used in the migrated scenarios' user_values.
This should be pretty easy and this way we can get started quickly without having to rethink every scenario's/dataset's setup.

Does this mean that each local (derived) dataset has its own directory of inputs? I think it would be better to have a fixed set of initialiser inputs which we use for all datasets this reduces redundancy and allows us to keep track of how they change etc.

**Comment by ploh** [comment]
> > I would suggest to have the migration script automatically create new initializer inputs corresponding to the inputs currently used in the migrated scenarios' user_values. (...)

> Does this mean that each local (derived) dataset has its own directory of inputs?

No, it means that whenever we want to migrate an input for which there is no corresponding initializer input yet, we create it on-the-fly. If there already is one, that is gonna be used.

> I think it would be better to have a fixed set of initialiser inputs which we use for all datasets this reduces redundancy and allows us to keep track of how they change etc.

:+1:

**Comment by grdw** [comment]
What's the status of this; is this still relevant? Should there be a new set? In my opinion the work @DorinevanderVlies and @BerendSmits are doing is useful since they are indirectly testing out if the initializer inputs work as they should. So maybe fix what there needs to be fixed for now and when the time is there think of a structurally better approach?

**Comment by ChaelKruip** [comment]
> So maybe fix what there needs to be fixed for now and when the time is there think of a structurally better approach?

I think that @DorinevanderVlies and @BerendSmits are very close to closing this issue.

**Comment by grdw** [comment]
Can this be closed? @ChaelKruip

**Comment by ChaelKruip** [comment]
> Can this be closed? @ChaelKruip

👍
