### ISSUE TITLE
Discussion: Disallow fixed values in scaleable inputs and remove step value

### ISSUE THREAD

**Issue by antw** [quintel/etsource#1213]
Following on from quintel/etmodel#2328 and quintel/etengine#902:

It is apparently quite tricky to scale a scenario which is based on a derived region since there are two sets of "scalings" required for input values to make sense in the front-end: full dataset → derived dataset, derived-dateset scenario → scaled-down scenario.

In order to solve this, I suggest we...

### Disallow the use of fixed input values when using a scaleable `unit`

Every input with a scaleable unit should use `start_value_gql`, `min_value_gql`, and `max_value_gql`, and would not be permitted to use `start_value`, `min_value`, or `max_value`. This would eliminate the need to scale these in ETEngine; it would happen automatically by virtue of the graph and dataset having been scaled down.

IMO this would be a step in the right direction even without the problems described in quintel/etmodel#2328. I see no intuitive reason for the P2G input to have [a hard-coded range of 0 to 100000 units](https://github.com/quintel/etsource/blob/680b817ed3d83b9d319e4c2d8816d44fe088418b/inputs/flexibility/energy/number_of_energy_flexibility_p2g_electricity.ad). Surely we would expect a German scenario to be able to install far more than a Netherlands scenario? This is probably true for many (all?) scaleable inputs with hard-coded values.

At present, there are [85 such inputs](https://gist.github.com/antw/fc64b1357efdbe694cac3c8d4a57f4fc).

The simplest way would be to replace these with a query referencing the number of inhabitants, residences, buildings, etc.

```
# number_of_energy_flexibility_p2g_electricity

- min_value_gql = 0.0
- max_value_gql = 0.005959627 * AREA(number_of_inhabitants)
- start_value_gql = "present:V(energy_flexibility_p2g_electricity, number_of_units)"
- unit = #
```

It would still be acceptable to use hard-coded values [for unscalable inputs](https://github.com/quintel/etengine/blob/470256764853fa338a13543e272de324bd46610b/app/models/scenario_scaling.rb#L7-L8). For example:

```
# agriculture_geothermal_share

- min_value = 0
- max_value = 100.0
- start_value_gql = "present:V(agricult[...]ble_heat) * 100)"
- unit = %
```

### Get rid of step values in ETSource inputs

This eliminates the need to scale step values in ETEngine.

1. Steps are not enforced by ETEngine,
2. They are overridden in ETModel with a custom value (`input_elements.step_value`). I believe ETFlex also uses custom values.
3. Some of our other applications *might* use the ETEngine step value, and may need to be adjusted.

I suggest that we also consider getting rid of the explicit step value in ETModel. This will allow the ETM to determine a suitable step value automatically; each slider is ~110px wide, so the step could be `(max - min) / 100`. This means the ETM steps would automatically scale correctly in smaller regions.

---

In theory, I think these changes would allow scaling of derived scenarios to work correctly.

I've assigned many people to this issue; sorry for the spam. 😆  I would appreciate your feedback when able.

**Comment by ChaelKruip** [comment]
I think I can do this next week.

**Comment by ChaelKruip** [comment]
Excellent idea @antw!

**Comment by ploh** [comment]
> In theory, I think these changes would allow scaling of derived scenarios to work correctly.
> I've assigned many people to this issue; sorry for the spam. :laughing: I would appreciate your feedback when able.

Yes, this is exactly in the direction that I was thinking [with this](https://github.com/quintel/etmodel/issues/2328#issuecomment-274048727) :+1:  - only I did not know much about the involved components. :wink:

**Comment by ChaelKruip** [comment]
> and would not be permitted to use start_value, min_value, or max_value. 

Thinking a bit more about this, only the `start_value` and `max_value` are an issue as the `min_value` is zero always for inputs which depend on the scaling anyways

**Comment by ChaelKruip** [comment]
> I suggest that we also consider getting rid of the explicit step value in ETModel.

@antw is this already supported? Can I remove the step-value from the inputs?

**Comment by antw** [comment]
> @antw is this already supported? Can I remove the step-value from the inputs?

ETModel disregards the step value from ETEngine, but I don't know if that's true of our other applications; the Optimizer almost certainly still uses it. ETModel defines it's own step value for each input(-element), which is what I was really referring to in that quote.

I think the `step_value` will have to remain in ETSource and ETEngine for the *short term*, until we have the chance to audit our other apps, but since the only applications which need use full-size datasets it should be possible for us to not worry about scaling it.
