### ISSUE TITLE
Local datasets: slider value doesn't change as number of inhabitants changes

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etsource#1214]
I used the following input to adjust the number of inhabitants in my local dataset to 4000:
`- init.households_number_of_inhabitants_both = 0.004000`

The number of inhabitants both present and future does indeed change to 4000, **however the slider value is not changed.**
The slider can be used to adjust the future number of inhabitants. It's just the inital value that does not correspond to the set value.

![image](https://cloud.githubusercontent.com/assets/19907658/22157142/bc3c3de4-df36-11e6-907d-c3063612116a.png)

**Comment by grdw** [comment]
> The slider can be used to adjust the future number of inhabitants. It's just the inital value that does not correspond to the set value.

What if you change the `number_of_inhabitants` through the `number_of_inhabitants` attribute in the `.ad` file without the use of an initializer input?

**Comment by DorinevanderVlies** [comment]
Usubg `init.number_of_inhabitants` gives similar problems.

It seems that there is memory of previously used values. For example I also used `init.number_of_inhabitants = 4000` first, when changing this to `init.number_of_inhabitants = 1111`
the number of the slider showed 4000, but the table showed 1111. This memory issue is inconsistent though. 

Furthermore, the same input (`init.number_of_inhabitants = 1111`) leads to different results when I re-open the scenario.

### Screenshots:

![image](https://cloud.githubusercontent.com/assets/19907658/22198907/e81a6a02-e158-11e6-956f-eff5f85809b3.png)

When this is shown I'm not able to move the slider.
![image](https://cloud.githubusercontent.com/assets/19907658/22198582/6c96bfb2-e157-11e6-9460-a9cf4abc87ec.png)

![image](https://cloud.githubusercontent.com/assets/19907658/22198799/74031150-e158-11e6-8a4e-f70814d5bd3e.png)

When this is shown I'm not able to move the slider.
![image](https://cloud.githubusercontent.com/assets/19907658/22198863/b27106e0-e158-11e6-98d9-e5fe91f0cc19.png)

**Comment by DorinevanderVlies** [comment]
Looked at this with @grdw, two things caused this issue:

1.  'number_of_inhabitants' is an area attribute defined during scaling. Overwriting this with an initialiser input leads to the above problems.
2. The memory issue which a describe is due to the cache of ETEngine. `Powder restart' after changing the .ad file and before reopening the scenario fixes this. It would be nice if also when running the model locally the cache of ETEngine is emptied automatically when the .ad file is adjusted or a scenario is re-opened. I'll make an issue for this.
