### ISSUE TITLE
Empty memory of ETEngine when re-opening a scenario or changing a .ad file

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etsource#1215]
As mentioned in #1241 re-opening a scenario after adjusting the .ad file sometimes leads to problems as ETEngine remembers old values in the cache.

Powder restart of ETEngine solves this.

It would be nice is ETEngine was restarted automatically, or if the cache was emptied automatically when 
- a scenario is re-opened
- the .ad file of a dataset is changed

**Comment by grdw** [comment]
Is this problem still relevant?

**Comment by DorinevanderVlies** [comment]
Closing this issue. Will make new issue or re-open if needed
