### ISSUE TITLE
Local datasets: How to initialize energy production?

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etsource#1219]
### Bigger picture
As a full test for local datasets I'm trying to reproduce the local scenario that was made for Paddepoel Noord (beta server scenario ID 607505)
To do this I convert the user inputs of the scenario on the beta server to inputs for the .ad file of a dataset I made scaled to 385 households.

### Problem/question
I try to set energy production to 0.
When I do this my scenario doen't load fully anymore. The sliders, charts and dashboard remain empty.

Am I using the wrong initializer inputs?

![image](https://cloud.githubusercontent.com/assets/19907658/22251948/db101dc6-e24c-11e6-8994-c3250afae694.png)

### Inputs
**User inputs original scenario on beta server**

` energy_production_biodiesel_both: 0`
`energy_production_bio_ethanol_both: 0`
`energy_distribution_woody_biomass_both: 0`
`energy_extraction_natural_gas_both: 0`
`energy_extraction_crude_oil_both: 0`

**My attempt to convert them to inputs**

`- init.energy_production_biodiesel_present = 0`
`- init.energy_production_bio_ethanol_present = 0`
`- init.energy_distribution_woody_biomass_present = 0`
`- init.energy_extraction_natural_gas_present = 0`
`- init.energy_extraction_crude_oil_present = 0`

**Comment by grdw** [comment]
Quick question: why do you switch from `_both` to `_present`?

**Comment by DorinevanderVlies** [comment]
>Quick question: why do you switch from _both to _present?

I thought `both` statements don't work in local datasets. Switching to `present` solves the problem.
