### ISSUE TITLE
Wrong input in .ad file of local dataset causes bug in local etmodel

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etsource#1220]
### Problem
When I have a random wrong input in the .ad file of a local dataset it causes my complete etmodel.dev not to open. Not even other datasets.

Would that also occur on the beta or live server? 

### Images
**The "some random completely wrong input" I used in the .ad file of a local dataset:**
![image](https://cloud.githubusercontent.com/assets/19907658/22252192/ab531fc4-e24d-11e6-9765-c1a38e836156.png)

**The result when I try to load etmodel.dev**
![image](https://cloud.githubusercontent.com/assets/19907658/22252189/a94f4d60-e24d-11e6-9e3c-adccd0d73e6d.png)

**Comment by grdw** [comment]
> Would that also occur on the beta or live server?

Yes. 👍  Which is exactly why you're doing this locally.

**Comment by DorinevanderVlies** [comment]
- Yes. 👍 Which is exactly why you're doing this locally.

Check, a related question. Would we be able to share local datasets with clients?

**Comment by grdw** [comment]
On a side note: maybe the error handling can be a little bit more descriptive though 🤔 

> Would we be able to share local datasets with clients?

Eh.. we could zip them and mail them I guess 😆 but what do you mean by this?

**Comment by DorinevanderVlies** [comment]
For example if we make a scenario for Drenthe, using a local model, and we want to share it with the other people involved in the project, would that be possible?

**Comment by grdw** [comment]
> For example if we make a scenario for Drenthe, using a local model, and we want to share it with the other people involved in the project, would that be possible?

No, that would not be possible locally. The only wat this can be achieved (as far as I know) is to deploy the Drenthe dataset and create a scenario similar to the one you created locally on either the beta or production server.

**Comment by DorinevanderVlies** [comment]
> The only wat this can be achieved (as far as I know) is to deploy the Drenthe dataset 

Would deploying the local dataset (made with the .ad file as input) be possible? 

@AlexanderWirtz 
The question you raised during a daily standup last week was if the methods of the "local datasets project" can be used for Drenthe. As I understand it now sharing a scenario would not be possible. That seems a problem to me.

**Comment by grdw** [comment]
> Would deploying the local dataset (made with the .ad file as input) be possible?

Not yet. All `local-dataset` branches need to be merged inside `master` for:

- etengine
- etmodel
- etsource
- atlas

Once that is done we can actually start deploying datasets like Drenthe :)

**Comment by AlexanderWirtz** [comment]
> Not yet. All local-dataset branches need to be merged inside master for:

@ChaelKruip @ploh @antw 

We would like to use the new method, but do of course need to share the created scenarios with our client (the province of Drenthe). Do you foresee such a deploy happening by early February? 

Good catch @DorinevanderVlies

**Comment by ploh** [comment]
> Do you foresee such a deploy happening by early February?

Yes. I think we should discuss this in more detail in the meeting tomorrow.

**Comment by ploh** [comment]
@DorinevanderVlies By now, the existence of the inputs used in the .ad file is verified if you run `rspec` in your etsource checkout - so you should probably do that before starting up your local server.

@DorinevanderVlies @grdw Do you agree that this can be closed now?

**Comment by grdw** [comment]
I agree, this can be closed 👍
