### ISSUE TITLE
Local datasets: How to initialize costs

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etsource#1221]
The local scenario on the beta server contains input that defines costs of fuels and CO2 emissions:

Can I initialize that in the .ad file, if so, how? Or is it a scenario input?
I assume it is the first as costs are typically part of a dataset, not a scenario.

**Local dataset on beta server:**
`costs_biomass: 0.0`
`costs_co2_free_allocation: 0.0`
`costs_co2: 674.0`
`costs_coal: 80.0`
`costs_gas: 22.0`
`costs_oil: 55.0`
`costs_uranium: 0.0`

**Comment by grdw** [comment]
> The local scenario on the beta server

Which scenario is that exactly? :)

**Comment by ploh** [comment]
> Can I initialize that in the .ad file, if so, how? Or is it a scenario input?
I assume it is the first as costs are typically part of a dataset, not a scenario.

The answer depends on exactly one thing: Do you want to specify the costs for the present (-> .ad file)? Or for the future (-> scenario user_values)?

**Comment by DorinevanderVlies** [comment]
That's a good question. Maybe specifying the costs for the future (so through user values) is sufficient. 

If I would want to specify the present costs, what initializer input would I need to use?

**Comment by ploh** [comment]
> If I would want to specify the present costs, what initializer input would I need to use?

If there was a `_present` input for this, then @grdw probably created an accordingly named init. input for this. Otherwise you could look at the input for the future and use that as a template to create a new init. input for this.

**Comment by grdw** [comment]
@DorinevanderVlies is this issue still needed?

**Comment by DorinevanderVlies** [comment]
Can be closed
