### ISSUE TITLE
Add specs for local datasets

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1222]
Validate:

- `DerivedDataset`
  - Validate that the referenced initializer inputs exist
- `InitializerInput`
  - Check if `update_type` is one of `nil`, `factor`, or `%`
  - Check if `query` is applicable and doesn't contain syntax errors

**Comment by ploh** [comment]
> Validate if the initializer inputs syntax is correct

Do you mean the query string?

**Comment by grdw** [comment]
> Do you mean the query string?

No, just checking if the `InitializerInput` exists.

**Comment by ploh** [comment]
>  > Do you mean the query string?

> No, just checking if the `InitializerInput` exists, I guess. 

So, like this?:

- `DerivedDataset`
  - Validate that the referenced initializer inputs exist
- `InitializerInput`
  - Check if `update_type` is one of `nil`, `factor`, or `%`

**Comment by grdw** [comment]
We also need to validate that the `- query` is valid for the `InitializerInput` probably.
