### ISSUE TITLE
Mistakes in transport_car carrier share inputs

### ISSUE THREAD

**Issue by ploh** [quintel/etsource#1223]
As discovered in https://github.com/quintel/etengine/issues/904#issuecomment-275199374 while migrating a scenario to a new derived dataset, there are probably some errors in the `transport_car_using_..._share(_present)` inputs:

In [these lines of the present inputs](https://github.com/quintel/etsource/blob/ea7cc5af9be787f76df760b01f32744e77b8f561/inputs/adjust_scaling/transport/transport_car_using_hydrogen_share_present.ad#L8-L12) (the ones from this share group are all similar):
The use of `INPUT_VALUE(transport_car_using_electricity_share)` although we are updating the present graph, i.e. it should be `INPUT_VALUE(transport_car_using_electricity_share_present)` here.

And in [these lines of the future inputs](https://github.com/quintel/etsource/blob/ea7cc5af9be787f76df760b01f32744e77b8f561/inputs/demand/transport/transport_car/transport_car_using_hydrogen_share.ad#L7-L12):
The use of `QUERY_PRESENT(-> { AREA(number_of_cars) })` is probably a mistake since the future number of electric cars should be relative to the future total number of cars and not to the present total number.

**Comment by AlexanderWirtz** [comment]
well spotted!

**Comment by ChaelKruip** [comment]
@ploh what is the action here? Have you tried your own suggestions for fixing this? I don't know what is expected of me here 😄

**Comment by AlexanderWirtz** [comment]
@ChaelKruip I'll venture a guess: you are expected to fix these. 😄  

They look like obvious mistakes, but a closer look might be warranted. @BerendSmits this is relevant to our work, as a fix to this issue will affect the outcome of the Drenthe dataset. Only in cases where `future` and `present` are not equal, though.

**Comment by ploh** [comment]
The action is to verify that my ideas about this are right and implement them :wink:
I did not try myself because I was not sure about my solution (especially regarding the future inputs) and because I did not have the time for it

**Comment by ChaelKruip** [comment]
> The action is to verify that my ideas about this are right and implement them

I still have some questions before I invest a considerable amount of time into this:
* How do I verify these ideas? I have not yet worked with the new scaling locally...
* Is this even relevant for the new scaling methods? Aren't we using "both"-statement only for that? Or is this for purpose of migrating old scaled scenario's? 
* Are there many (any?) scenario's where these queries are used and could we fix these in some other way?

@ploh could you please provide some insight?

**Comment by ploh** [comment]
> * How do I verify these ideas? I have not yet worked with the new scaling locally...

The mistake in the _future_ inputs does not concern the new scaling at all. It is simply a mistake in an `Input` - which is probably connected to a slider.

> * Is this even relevant for the new scaling methods? Aren't we using "both"-statement only for that? Or is this for purpose of migrating old scaled scenario's? 

The mistake in the _present_ inputs becomes even worse with the new scaling method, I am afraid. I just looked at the [implementation of `INPUT_VALUE()`](https://github.com/quintel/etengine/blob/6425fb86b6dd3242931b863d988485f013001073/app/models/scenario.rb#L226) and saw that it _will not_ respect values set by initializer inputs.
You probably have to let @grdw or @antw develop a new function like `INITIALIZER_INPUT_VALUE()` that looks at the init. input values instead - and then use this in all the `InitializerInput`s instead of `INPUT_VALUE()`.

> * Are there many (any?) scenario's where these queries are used and could we fix these in some other way?

I do not know how many there are but I came across one when trial-migrating a Gea scenario.

**Comment by grdw** [comment]
> [..] develop a new function like INITIALIZER_INPUT_VALUE() 

I'm wondering a bit to why this is relevant. I see a lot of links and text which I haven't really read thusfar. So maybe you can shortly summarize what you did and how you came to this conslusion. Is this related to migrating scaled scenarios or related to the new flow of local datasets? I'm a bit confused to what is what.

**Comment by ploh** [comment]
> > [..] develop a new function like INITIALIZER_INPUT_VALUE() 

> Is this related to migrating scaled scenarios or related to the new flow of local datasets? I'm a bit confused to what is what.

This (the issue with the INPUT_VALUEs) is independent of migrating old scenarios. Whenever you use `INPUT_VALUE()` in an init. input you are not going to get the expected results. The other question is whether the `INPUT_VALUE()` function should be used at all - it seems a bit of a hack to me. What do you think @antw?

**Comment by grdw** [comment]
> Whenever you use INPUT_VALUE() in an init. input you are not going to get the expected results.

Why is that? Is that because it ignores the scaling or fetches an incorrectly formatted value?

**Comment by ploh** [comment]
> > Whenever you use INPUT_VALUE() in an init. input you are not going to get the expected results.

> Why is that? Is that because it ignores the scaling or fetches an incorrectly formatted value?

Just look at the [implementation](https://github.com/quintel/etengine/blob/6425fb86b6dd3242931b863d988485f013001073/app/models/scenario.rb#L226) :stuck_out_tongue_winking_eye: 

It is not gonna get the value set in the .ad file but only a value set in a user_value

**Comment by grdw** [comment]
> It is not gonna get the value set in the .ad file but only a value set in a user_value

For example:

There is a node A and a node B.

So if I understand it correctly. If I set (for example, the demand of node A) and the demand of node B is dependent of the demand of node A (because of `INPUT_VALUE()`) than the demand will be incorrect. Assuming the priorities are set correctly.

**Comment by ploh** [comment]
> So if I understand it correctly. If I set (for example, the demand of node A) and the demand of node B is dependent of the demand of node A (because of `INPUT_VALUE()`) than the demand will be incorrect. Assuming the priorities are set correctly. 

Yes. Although this is a bit of a theoretic example. [In practice](https://github.com/quintel/etsource/blob/ea7cc5af9be787f76df760b01f32744e77b8f561/inputs/adjust_scaling/transport/transport_car_using_hydrogen_share_present.ad#L8-L12) the `INPUT_VALUE()` function is probably only used for things that are hard to query directly from the graph - at least I would hope so :wink:

**Comment by ChaelKruip** [comment]
After some investigation by @grdw we found that the offending lines have been added related to a discussion in https://github.com/quintel/etsource/issues/1038

In short: the `number_of_units` attribute of cars does not follow automatically from the demand (as for other technologies) because some necessary attributes (efficiency and capacity) are not defined for cars. 

@RobTerwel @AlexanderWirtz do you remember why it was needed to update the`number_of_units` for cars in the first place? The relevant commit is here: https://github.com/quintel/etsource/commit/a263a1eb6dffcb23b190d0ed4eb57fb3a31d75b6

**Comment by RobTerwel** [comment]
>@RobTerwel @AlexanderWirtz do you remember why it was needed to update thenumber_of_units for cars in the first place?

Yes, we did this so as to be able to calculate the additional costs for electric vehicles (as requested in https://github.com/quintel/etsource/issues/800). For that we needed to be able to retrieve the future number of electric cars, hence the attribute (which is only used for cost calculations).

**Comment by ChaelKruip** [comment]
> Yes, we did this so as to be able to calculate the additional costs for electric vehicles (as requested in #800). For that we needed to be able to retrieve the future number of electric cars, hence the attribute (which is only used for cost calculations).

@RobTerwel thanks for your answer! 

If I'm not mistaken, [this is the cost query used](https://github.com/quintel/etsource/blob/master/gqueries/general/costs/costs_of_transport_vehicles.gql):
```
# Return total cost of all electric cars

- query =
    SUM( 
      V((transport_car_using_electricity), " total_costs_per(:plant) * number_of_units "),
      V((transport_car_using_hydrogen), " total_costs_per(:plant) * number_of_units ")
    )
- unit = euro
```

I think we could/should rewrite the cost-queries to calculate the number_of_units from the share and the total number of cars like this:

```
# Return total cost of all electric cars

- query =
    SUM( 
      V((transport_car_using_electricity), total_costs_per(:plant)) * DIVIDE(INPUT_VALUE(transport_car_using_electricity),100) * QUERY_PRESENT(-> { AREA(number_of_cars) }),
      V((transport_car_using_hydrogen), total_costs_per(:plant)) * DIVIDE(INPUT_VALUE(transport_car_using_hydrogen),100) * QUERY_PRESENT(-> { AREA(number_of_cars) })
    )
- unit = euro
```

This allows us to remove the offending lines from all inputs right?

@RobTerwel @ploh @antw does this seem like a good solution to you as well?

**Comment by ploh** [comment]
> does this seem like a good solution to you as well?

That depends. In your above new query you still use `INPUT_VALUE()`, right? If you want to query an "input" with that, that really is an init. input (or might depend on one), then this probably does not solve the problem - although I must admit that I do not completely follow anymore.

**Comment by ChaelKruip** [comment]
> In your above new query you still use INPUT_VALUE(), right? 

INPUT_VALUE refers to the (future) slider setting. This is (fortunately) a well-tested feature and does not depend on initialiser inputs. To my knowledge this should work fine (testing this locally as we speak).

**Comment by antw** [comment]
> does this seem like a good solution to you as well?

Personally, no, I don't think that it is. This is using an input value to query the share of a car technology; while I expect that this *would* work, I think the practice should be discouraged. The *graph* is the authority in matters concerning shares and demands, and provided the information you need is available on the graph you should use that instead.

You can query the share of the link(s) to determine the technology share:

```ruby
SUM( 
  V(transport_car_using_electricity, total_costs_per(:plant)) *
    V(LINK(transport_car_using_electricity, transport_useful_demand_car_kms), share) *
    QUERY_PRESENT(-> { AREA(number_of_cars) }),

  V(transport_car_using_hydrogen, total_costs_per(:plant)) *
    V(LINK(transport_car_using_hydrogen, transport_useful_demand_car_kms), share) *
    QUERY_PRESENT(-> { AREA(number_of_cars) })
)
```

---

I am a little confused why you can't just use `number_of_units`:

```ruby
V(transport_car_using_electricity, number_of_units)
```

The returned value is slightly different from the `QUERY_PRESENT` version (11216 vs 11224).

**Comment by ChaelKruip** [comment]
> Personally, no, I don't think that it is. This is using an input value to query the share of a car technology; while I expect that this would work, I think the practice should be discouraged. The graph is the authority in matters concerning shares and demands, and provided the information you need is available on the graph you should use that instead.

I agree. The 'solution' I was referring to is to remove the lines that update the number of units from the input statements. 

> You can query the share of the link(s) to determine the technology share:

👍 

> I am a little confused why you can't just use number_of_units:

You *can* use them but that requires that the 'number_of_units' is defined. 

Normally, the 'number_of_units' attribute is calculated by a [method in ETEngine](https://github.com/quintel/etengine/blob/90ef9bc7e9ff45798b3ecd93e77bd73ffe4ef9d5/app/models/qernel/converter_api/helper_calculations.rb#L18) which requires 'input_capacity' and 'full_load_seconds' to be defined for a technology. For cars, these attributes are not known (nor do they make much sense physically). 

That's why @RobTerwel chose to calculate the 'number_of_units' in the input-statements based on the AREA(number_of_cars) and the slider-settings. 

> The returned value is slightly different from the QUERY_PRESENT version (11216 vs 11224).

I am currently exploring why this is. Seems a bit too much difference for a round-off error...

**Comment by antw** [comment]
> The 'solution' I was referring to is to remove the lines that update the number of units from the input statements.

Sorry, my bad. I think rewriting the queries to remove references to `number_of_units` seems like a fine idea, especially if you can do it without having to use `INPUT_VALUE`.

**Comment by ploh** [comment]
Maybe that is naive (I still do not know much about GQL and graph updates) but I think the `number_of_units` should be set correctly for the car converters. Sooner or later someone is gonna use it again without thinking twice and then the problem re-surfaces.
Maybe the car converters need their own `number_of_units` computation method (like the _demand driven converters_ already do). I guess this would be a quick thing for @antw to implement :wink:
