### ISSUE TITLE
Initializer inputs that don't do anything

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1227]
The migration left with some initializer inputs without a query. This is ofcourse impossible, these are the one's without a `query` or an empty looking `query`:

Migrated: | Originates from:
-------------|-------------------------
[agriculture_burner_network_gas_share.ad](https://github.com/quintel/etsource/pull/1228/files#diff-925b3b2775fbb523b4ff582e46e5daf3) | [agriculture_burner_network_gas_share_present.ad](https://github.com/quintel/etsource/blob/master/inputs/adjust_scaling/agriculture/agriculture_burner_network_gas_share_present.ad)
[households_cooling_airconditioning_electricity_share.ad ](https://github.com/quintel/etsource/pull/1228/files#diff-59ace0e6ce5e1e58a2f5cea02740e0a9) | [households_cooling_airconditioning_electricity_share_present.ad](https://github.com/quintel/etsource/blob/master/inputs/adjust_scaling/households/households_cooling_airconditioning_electricity_share_present.ad)
[households_heat_network_connection_steam_hot_water_share.ad ](https://github.com/quintel/etsource/pull/1228/files#diff-be42d19e4d611753a817ee0e5e61e790) | [households_heat_network_connection_steam_hot_water_share_present.ad](https://github.com/quintel/etsource/blob/master/inputs/adjust_scaling/households/households_heat_network_connection_steam_hot_water_share_present.ad)
[households_lighting_incandescent_electricity_share.ad ](https://github.com/quintel/etsource/pull/1228/files#diff-eafde6b382047e6f0cf75e7f6bf48f9d) | [households_lighting_incandescent_electricity_share_present.ad](https://github.com/quintel/etsource/blob/master/inputs/adjust_scaling/households/households_lighting_incandescent_electricity_share_present.ad)
[households_water_heater_network_gas_share.ad ](https://github.com/quintel/etsource/pull/1228/files#diff-9fcb37ad9c38047f4af589a62aeb3a32) | [households_water_heater_network_gas_share_both.ad](https://github.com/quintel/etsource/blob/master/inputs/adjust_scaling/households/households_water_heater_network_gas_share_both.ad)

---

This [one](https://github.com/quintel/etsource/pull/1228/files#diff-037b4900364e968e16e08e6127cbc297R7) has a non-supported attribute called `dependent_on`. What is it and what does it do?

**Comment by grdw** [comment]
The migration left with some initializer inputs without a query. This is ofcourse impossible, these are the one's without a `query` or an empty looking `query`:

Migrated: | Originates from:
-------------|-------------------------
[agriculture_burner_network_gas_share.ad](https://github.com/quintel/etsource/pull/1228/files#diff-925b3b2775fbb523b4ff582e46e5daf3) | [agriculture_burner_network_gas_share_present.ad](https://github.com/quintel/etsource/blob/master/inputs/adjust_scaling/agriculture/agriculture_burner_network_gas_share_present.ad)
[households_cooling_airconditioning_electricity_share.ad ](https://github.com/quintel/etsource/pull/1228/files#diff-59ace0e6ce5e1e58a2f5cea02740e0a9) | [households_cooling_airconditioning_electricity_share_present.ad](https://github.com/quintel/etsource/blob/master/inputs/adjust_scaling/households/households_cooling_airconditioning_electricity_share_present.ad)
[households_heat_network_connection_steam_hot_water_share.ad ](https://github.com/quintel/etsource/pull/1228/files#diff-be42d19e4d611753a817ee0e5e61e790) | [households_heat_network_connection_steam_hot_water_share_present.ad](https://github.com/quintel/etsource/blob/master/inputs/adjust_scaling/households/households_heat_network_connection_steam_hot_water_share_present.ad)
[households_lighting_incandescent_electricity_share.ad ](https://github.com/quintel/etsource/pull/1228/files#diff-eafde6b382047e6f0cf75e7f6bf48f9d) | [households_lighting_incandescent_electricity_share_present.ad](https://github.com/quintel/etsource/blob/master/inputs/adjust_scaling/households/households_lighting_incandescent_electricity_share_present.ad)
[households_water_heater_network_gas_share.ad ](https://github.com/quintel/etsource/pull/1228/files#diff-9fcb37ad9c38047f4af589a62aeb3a32) | [households_water_heater_network_gas_share_both.ad](https://github.com/quintel/etsource/blob/master/inputs/adjust_scaling/households/households_water_heater_network_gas_share_both.ad)

---

This [one](https://github.com/quintel/etsource/pull/1228/files#diff-037b4900364e968e16e08e6127cbc297R7) has a non-supported attribute called `dependent_on`. What is it and what does it do?

**Comment by grdw** [comment]
> This is ofcourse impossible, these are the one's without a query or an empty looking query: [..]

Including @AlexanderWirtz @ChaelKruip 

Could you perhaps tell me what to do with these initializer inputs without any queries in them? I would say: remove them.... but since some of these WIP commits (for two initializer inputs) ended up in the master branch it might be that these two are still of some use?

**Comment by ChaelKruip** [comment]
> ...it might be that these two are still of some use?

@antw can you think of a reason why these inputs without a query would exist?

**Comment by antw** [comment]
>@antw can you think of a reason why these inputs without a query would exist?

No; I expect they'd have no effect.

**Comment by antw** [comment]
> No; I expect they'd have no effect.

*Actually* if they belong to a share group, perhaps the whole group is controlled through a single input, and the others exist just so that everything adds up to 100?

**Comment by antw** [comment]
> Actually if they belong to a share group, perhaps the whole group is controlled through a single input, and the others exist just so that everything adds up to 100?

... that doesn't appear to be the case for [any of the inputs @grdw described](https://github.com/quintel/etsource/issues/1227#issuecomment-276033822). I imagine the inputs are needed to ensure the groups sum to 100, but why they have no query is a mystery to me.

**Comment by ChaelKruip** [comment]
@antw @grdw shall we merge the input and keep this issue open for now? We can investigate what happens if we remove them later.

**Comment by ChaelKruip** [comment]
Including @AlexanderWirtz @BerendSmits

**Comment by grdw** [comment]
> We can investigate what happens if we remove them later.

I guess so. It might be a bit confusing though because they won't do anything for now, but at least that is documented. If the people with energy + GQL powers could maybe write the relevant queries (`- query =`) that would be great to I suppose :angel:

**Comment by grdw** [comment]
Will be superseded, therefor closing https://github.com/quintel/etsource/tree/new_initializer_inputs/initializer_inputs
