### ISSUE TITLE
What needs to happen with the old %y update period initializer inputs in the adjust scaling folder.

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1229]
I managed to migrate the old adjust scaling inputs with %y as an `update_type` to new initializer inputs with an absolute update type. However the old %y inputs are still in use for scaled scenarios. The scaled scenarios aren't *all* going to be migrated but a few of them are. 

@ploh what was your plan for these inputs in relation to the scenario migration? I know that there was some discussion during a meeting last week about this.

**Comment by ploh** [comment]
Actually, I am not sure... It would be easy to migrate them to "%", but to absolute values?

**Comment by ChaelKruip** [comment]
> Actually, I am not sure... It would be easy to migrate them to "%", but to absolute values?

Why is "%" easier than absolute values in your view @ploh?

**Comment by grdw** [comment]
> Why is "%" easier than absolute values in your view @ploh?

I guess because when migrating, it's hard to determine what the actual absolute value might have been I can assume.

**Comment by ChaelKruip** [comment]
> I guess because when migrating, it's hard to determine what the actual absolute value might have been I can assume.

Harder than knowing the "%"? 
To know the "%", you need to either know
* present and future value to be able to say: % = future / present, or
* start_year and end_year and %/year (USER) value to say: % = (1 + USER_VALUE / 100)^(end_year - start_year)

For an absolute number you need to know either:
* future value (that's the value you want right there!)
* present value,  start_year, end_year and %/year (USER) value to say: future_value = present_value * (1 + USER_VALUE / 100)^(end_year - start_year)

If you don't know present or future values for the demand (or other attribute), the absolute value might be tricky indeed. Is that what you meant @grdw?

**Comment by grdw** [comment]
> Is that what you meant @grdw?

Yes. I think @ploh and @AlexanderWirtz had some discussion about this so they can probably explain the problem a bit more in detail than I can.

**Comment by ploh** [comment]
> > Is that what you meant @grdw?

> Yes. I think @ploh and @AlexanderWirtz had some discussion about this so they can probably explain the problem a bit more in detail than I can. 

Yes, that is it. So far, I only look at the scenario (and its `user_values`) and the `Input`s (and their `update_type`s). From this I can determine % with %y, start_year, end_year.

But let me think about what we would have to do for an absolute value... probably load the scenario and hook into the preparation of the scenario's `Gql` object - perhaps by implementing an optional callback inside of this preparation which is called whenever an `UPDATE()` statement is executed and is passed the executed `Input` as well as the new value after the update... or something along these lines.

Or, alternatively, parse the Input's query string and directly get the value in question from the final prepared graph, but... I guess this may be incorrect in cases where the value in question is later changed by another update statement again.

**Comment by ChaelKruip** [comment]
> But let me think about what we would have to do for an absolute value... 

Don't bother I would say. We only need to do this migration once anyway right? I was just curious to know the reasons.

**Comment by ploh** [comment]
> > But let me think about what we would have to do for an absolute value... 

> Don't bother I would say. We only need to do this migration once anyway right? I was just curious to know the reasons.

That is correct. The plan was for me to develop my framework (i.e. a Rake task that does some preparations and then start a Pry console where you can tweak and test the outcomes) for migrating old scenarios so that Alex can use it. But I think that this is probably not of much use with the new initializer inputs that are quite different from the old inputs in case of %y updates.
The [migration of the Paddepoel scenarios](https://github.com/quintel/etmodel/issues/2319#issuecomment-275391938) will probably have to be done completely manually then. But I will still try to fire up my framework on it and see where it gets me. Maybe the %y problem is not a problem in this case after all.

**Comment by ChaelKruip** [comment]
> The migration of the Paddepoel scenarios will probably have to be done completely manually then. 

Yes, I think we should just start doing it and fix problems manually as we go along. @ploh can you pick this up?

**Comment by ploh** [comment]
> @ploh can you pick this up?

Yes, I am doing that in quintel/etmodel#2319

**Comment by ploh** [comment]
@AlexanderWirtz @grdw @ChaelKruip Since the init. inputs that Gerard created do not contain the %y update_type and the Paddepoel user_values / init. inputs will be done manually anyways (https://github.com/quintel/etsource/issues/1229#issuecomment-276623134), I would suggest to close this now.
