### ISSUE TITLE
Better support for old datasets

### ISSUE THREAD

**Issue by ploh** [quintel/etsource#1231]
Structure the datasets directory like this:
```
datasets
├ de
│ └ 2013
├ nl
│ ├ 2012
│ ├ 2013
│ └ 2014
└ uk
  └ 2013
```

This probably has to be supported by scripts in etdataset and also requires changes in etengine.

See discussion [starting here](https://github.com/quintel/etmodel/issues/2319#issuecomment-275402188)

**Comment by marliekeverweij** [comment]
Same issue as https://github.com/quintel/etsource/issues/1371
