### ISSUE TITLE
Industry initializer inputs in the new local datasets structure

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etsource#1232]
The initializer inputs for useful in the industry sector now update with a percentage (- update_type = %), not an absolute value. I would propose to change this. 

Advantages:

- When you have exact UD (or FD) data per carrier  (as was the case for Drenthe and GEA), this saves you the trouble of having to query the scaled values, and adjusting your values accordingly. 
- Consistency: all other UD's are set as an absolute value. 

Disadvantage:

- When there is no data for exact energy use available, the percent inputs enable you to use the national carrier mix, and bring it to a local level. 

@AlexanderWirtz what is your opinion on this? @ChaelKruip was ok with us making this change.

**Comment by AlexanderWirtz** [comment]
If @ChaelKruip thinks it is OK, I am alright with it. I do wonder if we need to retain the `%-type` inputs for legacy purposes.

Also, @ChaelKruip told me that some UD-converters are initialized in inputs that update more than 1 converter at once. Obviously those inputs need to remain `%-type` inputs, right?

**Comment by BerendSmits** [comment]
Superseded by #1280
