### ISSUE TITLE
Local datasets households_useful_demand_electric_appliances initializer input

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etsource#1233]
The `households_useful_demand_electric_appliances` initializer input sets the useful demands for all the household appliances at once, to the same value. This is not desirable, it is now impossible to set different UD's for different appliances. 

Can we make 8 separate inputs, one for each appliance?

**Comment by ChaelKruip** [comment]
> Can we make 8 separate inputs, one for each appliance?

Whom are you asking?

I think we can BTW 😉

**Comment by BerendSmits** [comment]
> Whom are you asking?

I was asking @grdw, 

>I think we can BTW 😉

;p  will you please make 8 separate inputs?

**Comment by grdw** [comment]
Yes, this is doable 👍 

> will you please make 8 separate inputs?

@ChaelKruip I'm assigning you for this.

**Comment by ChaelKruip** [comment]
> @ChaelKruip I'm assigning you for this.

And I'm assigning @BerendSmits 😄 
Ask me if you need anything!
