### ISSUE TITLE
Local dataset .ad files failing rspec

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etsource#1239]
The .ad files seem to sometimes 'break', they fail rspec and no longer load. I've added two local datasets to which this has happened, for drenthe.derived.ad the error message was 'scaling is not a number', for drenthe2.derived.ad there were 3 errors, 
base_dataset => ["does not exist"],
+:interconnector_capacity => ["is not a number"],
+:scaling => ["can't be blank"]

See Gist: https://gist.github.com/BerendSmits/febc58d73da7cf57a90312e574a10213 for the two  broken .ad files.

**Comment by antw** [comment]
I can't reproduce this with either of the .ad files; all three attributes are present in both files.

If you encounter this again please reopen this issue, post the contents of the .ad file and if possible include every part of the "Failures" section which rspec outputs.

For example:

```
Failures:

  1) Validating datasets: drenthe
     Failure/Error: expect(document).to be_valid
       expected that :drenthe would be valid
       Diff:
       @@ -1 +1,2 @@
       +:init => ["contains inputs belonging to the buildings_appliances share group, but the values sum to 1.0, not 100"]

     # ./spec/validate_documents_spec.rb:32:in `block (4 levels) in <top (required)>'

Finished in 2.49 seconds
5930 examples, 1 failure, 11 pending
```
