### ISSUE TITLE
local datasets: slider setting of old houses can't be increase above initial setting

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etsource#1243]
I've made a local scenario containing 2000 new and 161 old houses.
In the ETM-interface it is not possible to increase the number of old houses.

![image](https://cloud.githubusercontent.com/assets/19907658/22931566/6831a944-f2c5-11e6-98c8-d2e4cd34cdd2.png)

Below a .txt version of the .ad file is used:
[npb.derived.txt](https://github.com/quintel/etsource/files/774234/npb.derived.txt)

notifying @ChaelKruip

**Comment by grdw** [comment]
This is the case for every scaled scenario unfortunately. I'm not sure why this is though.

**Comment by ChaelKruip** [comment]
> I need to research this a little bit.

👍

**Comment by grdw** [comment]
![screen shot 2017-02-14 at 16 41 37](https://cloud.githubusercontent.com/assets/2676542/22936002/784bbd2e-f2d4-11e6-9af3-2ee3df5b878e.png)

Okay, I found out that this is for *every* scenario. Not every scaled scenario specifically. So, I'm wondering if this has a reason? *Looks at @ChaelKruip ?*

**Comment by grdw** [comment]
> it is not possible to increase the number of new houses.

Just to be clear though, you mean, you can't drag the slider for `Residences built after 1991`? Right?

**Comment by ChaelKruip** [comment]
> Okay, I found out that this is for every scenario. Not every scaled scenario specifically. So, I'm wondering if this has a reason? Looks at @ChaelKruip ?

This is because you can't travel back in time 😜

**Comment by DorinevanderVlies** [comment]
good point ☺️ 
I was mixing up old and new residences (because 1992 is a higher number...)
I should have increased `after 1991` which is indeed possible.
Sorry for the confusion
