### ISSUE TITLE
Number of cars in local datasets

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etsource#1253]
The number of cars in local datasets does not seem to follow the .ad file. For instance, in Drenthe the .ad file lists number of cars as: 
![screen shot 2017-02-22 at 13 59 26](https://cloud.githubusercontent.com/assets/24872776/23212474/2c1cfd30-f907-11e6-9831-df8323865322.png)

But when you open a scenario and query the number of cars, it gives: 

![screen shot 2017-02-22 at 14 00 50](https://cloud.githubusercontent.com/assets/24872776/23212509/5a55d0f0-f907-11e6-875f-6d48aa60fe54.png)

Where the queried number comes from is unknown, it is not the total number of cars in NL (its about 500x larger). For Paddepoel, its 1,470,126.568, for Noorderplantsoen its 8,876,542.882 (more than NL).

**Comment by BerendSmits** [comment]
@grdw i think it relates to this discussion: https://github.com/quintel/etsource/issues/1223

**Comment by grdw** [comment]
I found it 😆 it turns out that a [`demand`](https://github.com/quintel/etsource/blob/master/initializer_inputs/transport/transport_car/transport_useful_demand_car_kms.ad#L4) was used to fill the `number_of_cars` attribute. Which ofcourse doesn't work as expected.

**Comment by BerendSmits** [comment]
Superseded by https://github.com/quintel/etmodel/issues/2360. Closing
