### ISSUE TITLE
Initializer input for energy_power_supercritical_waste_mix

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etsource#1255]
We're currently using energy_power_supercritical_waste_mix in local datasets to convert scaled CHP presence to power plant presence, to avoid issues with excess heat. We don't have an energy_power_supercritical_waste_mix initializer input though. @AlexanderWirtz, shall we make one? 

NB We're also missing energy_power_ultra_supercritical_lignite, but that one is used a lot less I think.

**Comment by AlexanderWirtz** [comment]
@BerendSmits well spotted! yes, let's create this initializer input. For lignite I am not surprised we have no initializer input. This is not relevant for NL.
