### ISSUE TITLE
Creating local datasets for all neighborhoods/districts and municipalities of the Netherlands would exceed the maximum 1GB limit of a github repository

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1264]
I'm currently working on https://github.com/quintel/etlocal/issues/33.  I've used a still WIP csv which contains a row for every municipality, district and neighborhood provided by @BerendSmits. The next thing was to create a very simple rake rask which read the CSV, looped over each row and only scaled every municipality, district and neighborhood to a local dataset. Everything went fine until I found the following:

The CSV contains 14934 rows. An average local dataset is about 2MB in size.

2MB * 14934 = ~30GB

Which is 30 times the limit of a Github repository. The obvious culprits are the `fce`, `load_profiles`, `network` and `time_curves` folders. But even if you'd remove these folders and only account for the size of the `.ad` file and the `graph.yml` that github limit will be exceeded:

For example (paddepoel_noord):

```
paddepoel_noord.derived.ad   12KB
graph.yml                   332KB
----------------------------------+
                            344KB
```

344KB * 14934 = ~ 5GB

So I'm wondering what to do now 🤔. We could support all municipalities but we can't support all neighborhoods and districts for that matter. 

---

**Solutions to support all municipalities/neighborhoods/districts would be:**

- Store datasets in a database instead of files (MySQL's default limit with MyISAM = 256TB - that will work) 
- Create a dataset on the fly in ETLocal as a 'tmp' dataset and only persist the datasets that are actually researched (like `paddepoel_noord`, `de_biezen`, etc.)
- ? 

I need to investigate any of these solutions thoroughly before this can work.

**Comment by michieldenhaan** [comment]
Closing, no plans to add all NL neighbourhoods to the ETM
