### ISSUE TITLE
Making some changes in the set of initializer inputs in the industry sector

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etsource#1280]
As explained in https://github.com/quintel/etmodel/issues/2336, the set of initializer inputs we now have for the industry sector is not ideal, sometimes multiple statements work on the same node. Also % updates are used a lot, which we try to avoid. 

We decided in the past not to adjust them, because that would result in an enormous list of required inputs (as discussed in https://github.com/quintel/etsource/issues/1232, supplemented by a discussion in person with @AlexanderWirtz and @ChaelKruip). 

However, since @grdw has built us a beautiful ETlocal environment which can decide for us which initializer inputs to use, I would propose to revisit the possibility of setting absolute demands with the initializer inputs. This unties the hands of users and etlocal smart analysis stuff, and gives us a mutually exclusive, collectively exhaustive set of initializer inputs. It also helpes us out of the slightly uncomfortable situation of having analysis steps in both etlocal and built into initializer inputs (since a grouped % update is essentially an analysis step). 

What are your opinions @AlexanderWirtz @DorinevanderVlies?

**Comment by grdw** [comment]
With `graph_methods` you'd need to explicitly set demands (per node) for the industry sector anyway. ETLocal can become smarter one day. Will note this down but it doesn't have any priority yet.

**Comment by grdw** [comment]
Closing this issue as this discussion is no longer relevant.
