### ISSUE TITLE
Simult constants larger than 1.0 (or smaller than -1.0) should not be supported in network calculation

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#1284]
After the implementation of the dynamic demand curve, only five instances remain:
* ground heat pump for cooling
* airconditioner
* micro CHP for hot water
* micro CHP for space heating
* fuel cell (not shown in overview below)
![screenshot_08_06_2017__16_23](https://user-images.githubusercontent.com/1303760/26934213-0a4470f2-4c69-11e7-85ee-f9c6330f66ba.png)

We need to assess what to do with the simult constants relatively soon. In the long term, I think we are going to model all technologies explicitly making them obsolete.

**Comment by jorisberkhout** [comment]
These simultaneousness parameters are no longer needed in the new network calculation, so closing this issue.
