### ISSUE TITLE
per_person inputs

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etsource#1299]
When checking the set of intializer inputs, I noticed we still have quite a few that have per_person in the name of the file. Since the UD being set is not per person but total, it might be nice to remove this part. The names from the initializer inputs come from the regular inputs on etsource, which we should probably also change. 

There are seven inputs that have per_person in the name: 

households_useful_demand_heat_per_person_both.ad
households_useful_demand_cooking_per_person.ad
households_useful_demand_old_houses_heat_per_person.ad
households_useful_demand_new_houses_heat_per_person.ad
households_useful_demand_cooking_per_person_both.ad
households_useful_demand_new_houses_heat_per_person_both.ad
households_useful_demand_old_houses_heat_per_person_both.ad

Changing these names means we have to migrate all the scenario's in which they are used, and also make sure etmodel still knows where to find them. @antw could you make an estimate as to how much time this would cost, and whether or not you think it would be worth it? 

The UD's in the transport sector have a similar problem, they have kms in their names, without actually being kilometers. However, changing them might be more difficult, because the nodes in the graph also have kms in their names.

**Comment by antw** [comment]
> @antw could you make an estimate as to how much time this would cost, and whether or not you think it would be worth it?

We'd need to...

* Rename the files
* Write a migration to update scenarios on ETEngine
* Update presets
* Write a migration to update input elements in ETModel

All-in-all, I'd guess a couple of hours should do it. Whether it's worth changing, I can't really say; it seems pretty low-priority unless it impacts work on ETLocal somehow.

> The UD's in the industry sector have a similar problem, they have kms in their names

I believe this indicates their use of the `car_kms`, `shipping_kms`, and `truck_kms ` carriers, but I'm unsure of the significance of "kms" in the node name (most other nodes don't include the carrier names this way). Sorry, I don't really know much about this. :blush:

@ChaelKruip do you have an opinion on the naming of these nodes?

**Comment by ChaelKruip** [comment]
> @ChaelKruip do you have an opinion on the naming of these nodes?

Not really. I think this is mostly about useful demand nodes. For most of them, the `carrier` is not really that clear of a concept. It's all expressed in Joules in the end (the ETM being an energy model). 

With respect to renaming in general. I'd like to see understandable, consistent naming as much as the next guy but it's quite some work for a couple of files. @BerendSmits can you make an inventory of inputs that need renaming now and do the actual work when we have a whole batch?

**Comment by BerendSmits** [comment]
The new initializer methods should render this unnecessary.
