### ISSUE TITLE
Double input for industrial heat pump?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#1306]
<img width="879" alt="cursor_and_energytransitionmodel" src="https://user-images.githubusercontent.com/1303760/29180937-a75ca38e-7df9-11e7-9bcb-5e01a95a0a29.png">

**Comment by DorinevanderVlies** [comment]
`industry_chemicals_other_heatpump_water_water_electricity_share` is a slider input 

`industry_chemicals_other_heatpump_water_water_electricity` is an adjust scaling input
The share is a scaling input.

I propose to rename the scaling input to industry_chemicals_other_heatpump_water_water_electricity_present. That way the name is more in line with the other scaling inputs. Se commit https://github.com/quintel/etsource/commit/3102bf036896a088ef6a69818b05afa602153069.

**Comment by DorinevanderVlies** [comment]
Closed with: https://github.com/quintel/etsource/commit/d2711d50a437d0d1f772122bd62505c42e5b7b80
