### ISSUE TITLE
Changing an attibute in P2H technologies removes merit_order_demand_profile and ..._source

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etsource#1312]
### Context
@jorisberkhout and me are updating the P2H nodes by running the node source analysis. We find that not only the attriutes we want to change change, but also some lines are remove from the nodes.

This also happens when I run a rake task that should just change one attribute

### Detail
When I update an attribute in the `industry_chemicals_other_flexibility_p2h_electricity` node by a rake task, eg when I run:
bundle exec rake import:node NODE=industry_chemicals_other_flexibility_p2h_electricity heat_output_capacity=50.0 ,
I expect this attribute to change and maybe the sequence of the node (they both do change)
However, two lines are removed from the file:
`- merit_order.demand_profile = industry_heat`
and `- merit_order.demand_source = industry_useful_demand_for_chemical_other_useable_heat`

@antw do you know why this happens and how we can solve this?

**Comment by antw** [comment]
Sorry, I hadn't updated ETSource to use the most recent version of Atlas. Grab the latest copy of ETSource, then run `bundle install` and you should be good-to-go.

**Comment by DorinevanderVlies** [comment]
Thanks!

**Comment by DorinevanderVlies** [comment]
This problem was fixed before, however it came up again today as @jorisberkhout and I updated the P2H nodes again
