### ISSUE TITLE
Discussion: what to do with biogas that is always produced

### ISSUE THREAD

**Issue by wmeyers** [quintel/etsource#133]
@AlexanderWirtz @markquintel please contribute

Some biogas is always produced, but cannot always be exported. For example biogas produced in landfills and sewage water treatment facilities. In the ETM we will offer users the choice to get rid of this type of CHP, but that does not remove the biogas production itself. One solution could be to create a Flaring converter, that gets rid of this excess biogas as loss, when no CHP is there to burn it. Another option could be to create a CHP in the model that users cannot increase or decrease.

Any other ideas?

**Comment by MartLubben** [comment]
@jorisberkhout Is this issue solved and could you close it? You were the last assigned person :)

**Comment by redekok** [comment]
Closing this issue as it is not relevant anymore after the biomass modelling update.
