### ISSUE TITLE
The problem with FIRST(LINKS(OUTPUT_SLOTS(V(<some node>),not_defined))

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1339]
While cleaning up the initializer inputs and specifying which node attributes and edge attributes to set I stumble upon this magic:

```
FIRST(LINKS(OUTPUT_SLOTS(V(<some node>),not_defined))
```

This query looks for all the output slots of `<some node>`, selects all the edges (LINKS) and picks the first edge (FIRST). This is pretty magical. If I were to alter the graph at `<some node>` and add a new node and edge, this query will not function as intended and might cause unforseen bugs. What I would suggest is to turn it into something explicit:

```
LINK(<some node>, <first node>)
```

This is logical, involves no magic, is exactly as it is in other inputs.

Files that have this magic:

- [x] inputs/adjust_scaling/transport/transport_train/transport_train_using_coal_share_present.ad
- [x] inputs/adjust_scaling/transport/transport_train/transport_train_using_diesel_share_present.ad
- [x] inputs/adjust_scaling/transport/transport_train/transport_train_using_electricity_share_present.ad
- [x] inputs/demand/buildings/buildings_misc/buildings_lighting_savings_from_daylight_control_light.ad
- [x] inputs/demand/buildings/buildings_misc/buildings_lighting_savings_from_motion_detection_light.ad
- [x] inputs/demand/transport/transport_plane/transport_plane_using_kerosene_share.ad
- [x] inputs/demand/transport/transport_plane/transport_plane_using_bio_ethanol_share.ad
- [x] inputs/demand/transport/transport_plane/transport_plane_using_gasoline_share.ad
- [x] inputs/demand/transport/transport_train/transport_train_using_coal_share.ad
- [x] inputs/demand/transport/transport_train/transport_train_using_diesel_share.ad
- [x] inputs/demand/transport/transport_train/transport_train_using_electricity_share.ad

**Comment by grdw** [comment]
Re-assign at will

**Comment by BerendSmits** [comment]
@AlexanderWirtz I don't think we use adjust_scaling anymore right?  Is it maybe time to throw those away? Or should we keep them for the old Gelderland dataset?

**Comment by AlexanderWirtz** [comment]
@BerendSmits I am not sure they are not used. How would we find out? Query the database?

**Comment by ChaelKruip** [comment]
Assigning @grdw. Let me know if you need help!

**Comment by BerendSmits** [comment]
> @BerendSmits I am not sure they are not used. How would we find out? Query the database?

I did a preliminary search and I found quite a few unfortunately: 
- GEA scenario's
- Ameland scenario's 
- IABR scenario's
- NEXT Electric
- Zuid Holland
- Let's try it again FOR THE SECOND TIME FOR GOD's Sakefor Gateway scenario (:joy:) 
- Paddepoel Noord

Some of these will probably still be in use right @AlexanderWirtz ?  

In that case, although this is not the prettiest method we have, we should probably keep them...

**Comment by ChaelKruip** [comment]
> @AlexanderWirtz I don't think we use adjust_scaling anymore right? Is it maybe time to throw those away? Or should we keep them for the old Gelderland dataset?

Should this be another issue? I don't see the connection with the title 😟

**Comment by BerendSmits** [comment]
> Should this be another issue? I don't see the connection with the title 😟

I brought it up because the first three files for which this is an issue, are adjust_scaling inputs. But yes, it should probably be dealt with separately. But I think we figured it out, we'll need to keep them. So my apologies for the intermission, I'll put a smal .md file in the adjust_scaling folder. 

And then back to you @grdw ->

**Comment by grdw** [comment]
> I don't think we use adjust_scaling anymore right?

Ehh, this discussion derailed quiet into a completely different issue.
