### ISSUE TITLE
Why are buildings appliances shares set in the way they are set?

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1341]
For buildings I find the following type of initializer inputs:

```ruby
EACH(
  UPDATE(LINK(buildings_appliances_wood_pellets,buildings_useful_demand_for_appliances), share, DIVIDE(USER_INPUT(),100)),
  UPDATE(LINK(buildings_useful_demand_for_appliances,buildings_appliances_network_gas), share,
 ->{SUM(NEG(SUM(V(EXCLUDE(INPUT_LINKS(V(buildings_useful_demand_for_appliances)),UPDATE_COLLECTION()), share))), 1)}
  )
```

I understand the first line:

```ruby
UPDATE(LINK(buildings_appliances_wood_pellets,buildings_useful_demand_for_appliances),` share, DIVIDE(USER_INPUT(),100))
```

I don't get this:

```ruby
->{SUM(NEG(SUM(V(EXCLUDE(INPUT_LINKS(V(buildings_useful_demand_for_appliances)),UPDATE_COLLECTION()), share))), 1)}
```

I do get what it does but I don't know why it's there. 

---

Side note: 

This:

```ruby
V(EXCLUDE(INPUT_LINKS(V(buildings_useful_demand_for_appliances)),UPDATE_COLLECTION()), share)
```

... returns the same as: ...

```ruby
V(INPUT_LINKS(V(buildings_useful_demand_for_appliances)), share)
```

... this.

**Comment by ChaelKruip** [comment]
> I don't get this:

I think it is an explicit way to balance the share group. With the ETModel balancer, I think this can safely be removed. I advice to try that out locally first though 😄

**Comment by grdw** [comment]
> I think it is an explicit way to balance the share group

Yes, it seems to be the case. It's pretty horrible at it though: to elaborate:

Let 's say this the share group:

```
A) 20%
B) 20%
C) 30%
D) 30%
```

I set the share of A to 40. Now, node D goes down because of this.

```
A) 40%
B) 20%
C) 30%
D) 10%
```

I set node B to 40%

```
A) 40%
B) 40%
C) 30%
D) 0% (-10% ??!!)
```

Now I have a problem because I can't actually do this. It will still try to lower node D because that's all the inputs are capable of doing except if I alter node D directly. 

Anyway, stating that this only lives in `adjust_scaling` I'm not going to fester to much time on actually cleaning this up, unless this is still being used? 

The new intiailizer methods will not make use of any of this, and balancing should be done in a front-end not in inputs.

**Comment by ChaelKruip** [comment]
> The new initializer methods will not make use of any of this, and balancing should be done in a front-end not in inputs.

Should we also remove this from the current inputs? It seems that the ETModel balancer overrides this behaviour anyway...

**Comment by grdw** [comment]
> Should we also remove this from the current inputs? It seems that the ETModel balancer overrides this behaviour anyway..

Yes. But they aren't in there as far as I can see.

They're only in:

```
inputs/adjust_scaling/buildings/buildings_appliances/buildings_appliances_coal_share_both.ad
inputs/adjust_scaling/buildings/buildings_appliances/buildings_appliances_electricity_share_both.ad
inputs/adjust_scaling/buildings/buildings_appliances/buildings_appliances_crude_oil_share_both.ad
inputs/adjust_scaling/buildings/buildings_appliances/buildings_appliances_wood_pellets_share_both.ad
inputs/adjust_scaling/buildings/buildings_appliances/buildings_appliances_network_gas_share_both.ad
```

**Comment by ChaelKruip** [comment]
So, can we close this @grdw?

**Comment by grdw** [comment]
Yes! 👍
