### ISSUE TITLE
Can we remove the correction for double counting in costs gquery?

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etsource#1346]
Should we remove the correction for double counting from the dashboard gquery costs of produced heat plus insulation now these technologies are not double counted anymore?

The gquery  [costs_of_produced_heat_plus_insulation](https://github.com/quintel/etsource/blob/9e497c279596ab1f2157180b675e6e0759fdb95b/gqueries/general/costs/costs_of_produced_heat_plus_insulation.gql) currently contains a [correction for double counting](https://github.com/quintel/etsource/blob/9e497c279596ab1f2157180b675e6e0759fdb95b/gqueries/output_elements/dashboard/dashboard_total_cost_correction.gql).

notifying @ChaelKruip

**Comment by ChaelKruip** [comment]
> are not double counted anymore?

Their capacity is not counted twice anymore indeed. Their investment costs would still be counted twice as there are space heating and hot water versions of all combi-technologies
