### ISSUE TITLE
Solar thermal shares not whitelisted

### ISSUE THREAD

**Issue by MichielDenHaan** [quintel/etsource#1356]
### Please whitelist shares:

:"households_useful_demand_for_hot_water_for_houses_with_solar_heater-households_water_heater_solar_thermal@useable_heat":

:"households_useful_demand_for_hot_water_for_houses_with_solar_heater-households_useful_demand_for_hot_water_after_solar_heater@useable_heat":

and:

:"households_useful_demand_for_space_heating_after_insulation_and_solar_heater-households_useful_demand_for_space_heating_after_insulation_for_houses_with_solar_heater@useable_heat":

:"households_useful_demand_for_space_heating_after_insulation_for_houses_with_solar_heater-households_water_heater_solar_thermal@useable_heat":

Thx!

**Comment by grdw** [comment]
Edges to be whitelisted:

- [ ] "households_useful_demand_for_hot_water_for_houses_with_solar_heater-households_water_heater_solar_thermal@useable_heat"
- [ ]  "households_useful_demand_for_hot_water_for_houses_with_solar_heater-households_useful_demand_for_hot_water_after_solar_heater@useable_heat"
- [ ]  "households_useful_demand_for_space_heating_after_insulation_and_solar_heater-households_useful_demand_for_space_heating_after_insulation_for_houses_with_solar_heater@useable_heat"
- [ ] "households_useful_demand_for_space_heating_after_insulation_for_houses_with_solar_heater-households_water_heater_solar_thermal@useable_heat"
