### ISSUE TITLE
Add some more applications to data dump

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etsource#1357]
### Background and problem
Our client is currently using the data export intensely 😃 
They compared the final demand table in ETM to the final demand in the data export and found that the sum differs.

### Research and assumed cause
Some research thought me the following:

1. Most of the difference is because export is shown in the export but not in the ETM-table
2. Some groups / nodes seem are presented in the ETM-table, but seem to be missing from the datadump. Analysis can be found in the attached Excel file:
[comparison data export and final demand table.xlsx](https://github.com/quintel/etsource/files/1324618/comparison.data.export.and.final.demand.table.xlsx)

### Proposed solution
IMO 1 is not a problem.
I think we can solve 2 by adding `groups = [application_group]` to the following nodes:
- households_water_heater_solar_thermal
- industry_useful_demand_for_chemical_fertilizers_electricity
- energy_power_sector_own_use_electricity
- energy_cokesoven_consumption_coal_gas
- energy_export_coal_gas
- energy_power_geothermal
- energy_heater_for_heat_network_geothermal
- buildings_collective_geothermal
- households_collective_geothermal

Not sure about:
- industry_final_demand_for_chemical_fertilizers_steam_hot_water

I got inspiration from https://github.com/quintel/etsource/pull/1308/files.
@jorisberkhout do you agree with this? 

With these changes I'm only missing 0.29 PJ for electricity - energy which is present in the ETM-table, but not in the datadump.

**Comment by ChaelKruip** [comment]
@DorinevanderVlies when are you planning on picking this up?

**Comment by DorinevanderVlies** [comment]
2. is fixed by https://github.com/quintel/etsource/pull/1361

3. However, something else is going on as well:
The nodes below are present in the datadump with a final demand = 0. However, in the final demand table of the ETM the demand of these nodes _is_ present. The nodes themselves give a non-zero final demand (example empty scenario). 
- energy_power_sector_own_use_electricity 14.64 B
- energy_cokesoven_consumption_coal_gas 7.40 B
- energy_export_coal_gas 25.21 B
 
@antw do you know why the final demand of these nodes is zero in the datadump even though it it non-zero in the graph?

**Comment by antw** [comment]
> do you know why the final demand of these nodes is zero

They all have something in common: they're on the far left of the graph with no outputs. `final_demand_of_carrier` didn't like this.

An ETEngine fix has been pushed.
