### ISSUE TITLE
How does this work and why?

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1358]
https://github.com/quintel/etsource/blob/master/initializer_inputs/industry/number_of_industry_chp_engine_gas_power_fuelmix.ad#L8

I see that a demand value is being put into the place where a share should be. In my limited knowledge a share is something between 0 and 1, but this is not the case. This line has always been this way appearantly according to this commit: c5c4b1d6361051086d04b836584e1af595f7b641 

How does this work?

**Comment by antw** [comment]
It's a `type=constant` edge. These allow you to [set a demand for the edge using the `share` attribute](https://github.com/quintel/etengine/blob/ec14296360ad2639baabed5ccf0282240e024c8d/app/models/qernel/calculation/links.rb#L34-L50). It's a weird (legacy) quirk. See also: [Etsource::Import](https://github.com/quintel/etengine/blob/ec14296360ad2639baabed5ccf0282240e024c8d/app/models/etsource/dataset/import.rb#L201).

I guess it would be nice to do away with this – since it's really confusing to set a demand using `share` – but, offhand, I don't know what the implications would be.

**Comment by grdw** [comment]
One more question, but where in the code is corrected for the fact that the share will be `> 1.0` for constant edges? Also can we set a constant edge with a value between 0 and 1? Or does this always need to be a demand which is `> 1.0`?

**Comment by grdw** [comment]
Ow, @ChaelKruip told me that these shares always have a share value of 1.0 and you just update a demand under the misnomer 'share'.

**Comment by antw** [comment]
>  where in the code is corrected for the fact that the share will be > 1.0 for constant edges

[Here](https://github.com/quintel/etengine/blob/ec14296360ad2639baabed5ccf0282240e024c8d/app/models/qernel/link.rb#L190-L210) ([called here](https://github.com/quintel/etengine/blob/ec14296360ad2639baabed5ccf0282240e024c8d/app/models/qernel/graph.rb#L316)).

> ChaelKruip told me that these shares always have a share value of 1.0 and you just update a demand under the misnomer 'share'.

This is not the case. Once the graph is calculated the edges will have the correct share assigned.

```ruby
V(LINK(agriculture_chp_engine_biogas, agriculture_locally_available_electricity), share)
# => 0.04386451792336214
```

**Comment by BerendSmits** [comment]
I checked if we can just ignore this for initializer methods (and just set demand for the nodes we need), but that does not seem to work. So should we try something to fix this, or leave it as is and build it into IM and ETLocal? What do you think @ChaelKruip @antw @grdw ? 

Including @MichielDenHaan

**Comment by ChaelKruip** [comment]
> I checked if we can work around this for initializer methods (and just set demand for the nodes we need)

Can you explain a bit more what you are trying to do here?

> but that does not seem to work

Why not?

> So should we try something to fix this

Can you explain a bit more what a fix would look like? I have trouble following the line of reasoning. Sorry 😬

**Comment by BerendSmits** [comment]
> Can you explain a bit more what you are trying to do here?

If we do not want to set this constant share, we can just set the demand straight into the node. That way, we do not set a demand for the edge using the share attribute, and we do not depend on this legacy quirk. 

I used the HH solar PV as an example, so I put the following into the initializer_inputs.yml:

```
demand_setter:
  households_solar_pv_solar_radiation: 10000000000
```
Also, I whitelisted the node. 

This is 10 PJ of 'solar pv demand' which should give you 1.6 PJ of electricity. 

> but that does not seem to work
> Why not?

The `households_solar_pv_solar_radiation` node gives the following demands:

![screen shot 2017-09-29 at 10 58 56](https://user-images.githubusercontent.com/24872776/31008736-6e400b08-a505-11e7-9206-0ee24442054e.png)


AS you can see, the extra solar pv electricity is not forwarded into the locally available electricity in the households sector. The market penetration percentage in the front end is also unchanged. ETEngine does not work properly from left to right, so the solar power is not correctly entered into the graph. It looks like we cannot go around setting the constant share. 

> Can you explain a bit more what a fix would look like?

I'm not entirely sure if I'm the best person to understand what changing this would mean for etsource (@antw perhaps you have a better overview of what fixing this would mean), but for me a fix could be as simple as no longer calling it a share, but just treat it as setting a demand to an edge (but that is just me liking shares to add up to one, and not knowing anything about ruby).  

Another way would be to equip ETengine to work right-to-left, but I am unsure about what that would mean (I can imagine a lot). 

There are some preset_demand nodes which are not on the far left of the graph (for instance the wind turbines), so maybe way can look at those for inspiration?

**Comment by ChaelKruip** [comment]
Has this question been answered satisfactorily @BerendSmits? Shall we close this issue?

**Comment by BerendSmits** [comment]
The answer was basically: for now we're going to leave this the way it is, and if we need to use it in etlocal, we will. Maybe at a later time we can fix this. So yes, for now this can be closed.
