### ISSUE TITLE
Identical inputs for industry construction and wood products

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1359]
[industry_useful_demand_for_other_construction_efficiency](https://github.com/quintel/etsource/blob/master/inputs/demand/industry/industry_useful_demand_for_other_construction_efficiency.ad) is exactly the same as [industry_useful_demand_for_other_wood_products_efficiency](https://github.com/quintel/etsource/blob/master/inputs/demand/industry/industry_useful_demand_for_other_wood_products_efficiency.ad). 

They both update construction. This seems wrong.

This is also problematic with the current initializer inputs and in fact only correct with the initializer methods.

**Comment by grdw** [comment]
Assigning @ChaelKruip - re-assign at will.

**Comment by grdw** [comment]
```diff
datasets/flevoland/flevoland.derived.ad
144:- init.industry_useful_demand_for_other_construction = 82.5214614155307
154:- init.industry_useful_demand_for_other_wood_products = 41.9371361292041

datasets/friesland/friesland.derived.ad
142:- init.industry_useful_demand_for_other_construction = 22.5086093714239
152:- init.industry_useful_demand_for_other_wood_products = 265.334672154047
```

There are two local datasets which currently use these inputs

**Comment by BerendSmits** [comment]
I checked the effects of this bug in the scenario's @grdw mentioned:

 Friesland has 140 TJ less in the 'other industry sector' in the front end (+147 TJ in wood_products, -284.7 TJ in construction), and Flevoland  has 180 TJ more in the other industry sector (-30 TJ in wood_products, +210 TJ in construction) 

Can we merge the fix, or should we first change the scenario's/inform the users @AlexanderWirtz @jorisberkhout ?

**Comment by BerendSmits** [comment]
The inputs are not used in the front end and are also not in any scenario's, so there will be no effect there

**Comment by AlexanderWirtz** [comment]
I think informing the users is a good idea and we will need to fix this regardless. 

I need a bit more information on what to tell Friesland. I understand we made a mistake here, so if we can fix it that would be great. Would like to know how this affects outcomes like renewability, CO2 emissions and other visible dashboard items.

**Comment by BerendSmits** [comment]
In the old situation the dashboard for Friesland looked like this: 

![screen shot 2017-09-28 at 09 24 50](https://user-images.githubusercontent.com/24872776/30954058-023ad752-a42f-11e7-9165-8a962516a1a3.png)

In the new situation it will look like this: 

![screen shot 2017-09-28 at 09 26 09](https://user-images.githubusercontent.com/24872776/30954120-4930619a-a42f-11e7-86d8-ca33642636a1.png)

**Comment by BerendSmits** [comment]
Fix is in branch `construction_wood_products_bug`, can we merge this?

**Comment by ChaelKruip** [comment]
> Fix is in branch construction_wood_products_bug, can we merge this?

Who are you asking this @BerendSmits?

**Comment by BerendSmits** [comment]
> Who are you asking this @BerendSmits?

@jorisberkhout and @AlexanderWirtz

**Comment by AlexanderWirtz** [comment]
go ahead and merge.

**Comment by BerendSmits** [comment]
Fixed by https://github.com/quintel/etsource/pull/1363
