### ISSUE TITLE
Rake scale doesn't add the heat curves

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etsource#1366]
The rake scale task doesn't add the necessary heatcurves csv files (#anycurrentdataset/curves/heat) to a new dataset.

**Comment by grdw** [comment]
Fixed with: https://github.com/quintel/atlas/commit/96596d7b3cf7c2ce16105ee91533e380d31e0e2b#diff-570156e24823180b9e2c105aa84dcaf4
