### ISSUE TITLE
Groningen/Ten Boer non-energetic network gas/natural gas does not disappear when sector size is 0%

### ISSUE THREAD

**Issue by MichielDenHaan** [quintel/etsource#1383]
When I set the size of the fertilizers industry to 0% in the Groningen/Ten Boer dataset (on beta server) only the electricity demand goes to 0. The non-energetic networkgas and natural gas stay the same. For the other industry sectors all works fine.

![screen shot 2017-10-17 at 09 11 25](https://user-images.githubusercontent.com/32056448/31651635-c110daa4-b31c-11e7-910c-c3c1aad88674.png)

**Comment by antw** [comment]
I think there's a bad interaction between an initializer method value and the graph.

For comparison, here are the flows of "industry useful demand for chemical fertilizers useable heat" in [NL](https://beta-engine.energytransitionmodel.com/data/746682/converters/industry_useful_demand_for_chemical_fertilizers_useable_heat) and [Ten Boer](https://beta-engine.energytransitionmodel.com/data/746675/converters/industry_useful_demand_for_chemical_fertilizers_useable_heat) with the fertilizers slider set to 0%:

**NL**

![in-nl](https://user-images.githubusercontent.com/4383/31662305-b88bff44-b335-11e7-90eb-3d6d32e0eea0.png)

**Ten Boer**

![in-gr](https://user-images.githubusercontent.com/4383/31662312-c11985fa-b335-11e7-9f45-3add56962954.png)

The values on the left are the energy ETEngine expects should be leaving the node in the present and future, according to the demands of the nodes to the left; in this case probably based on preset demand of "[haber_bosch_process_hydrogen](https://beta-engine.energytransitionmodel.com/data/746675/converters/industry_chemicals_fertilizers_haber_bosch_process_hydrogen)"? However, the initializer method forces a custom value on to the useable heat/gas nodes.

From the graph_values.yml for this region:

```yaml
  industry_useful_demand_for_chemical_fertilizers_network_gas_non_energetic: 8819895
  industry_useful_demand_for_chemical_fertilizers_useable_heat: 3163225.5
```

... neither of these are `preset_demand` nodes, so it's inevitable that inconsistencies will arise in the graph if we try to set them.

As far as I am aware, only preset demand nodes should be whitelisted for use in initializer methods. Berend investigated this quite thoroughly and found that setting demands on random nodes in the middle of the graph would not work ([see here for an example why](https://3.basecamp.com/3797409/buckets/4290417/documents/605846478#__recording_640775896)).

---

Including @DorinevanderVlies and @ChaelKruip.

**Comment by MichielDenHaan** [comment]
Thanks! So if I understand this correctly, we have to set the haber_bosch thing and all the carrier shares for industry_useful_demand_for_chemical_fertilizers_useable_heat (see graph below)?
![screen shot 2017-10-17 at 14 11 04](https://user-images.githubusercontent.com/32056448/31664308-36f97bcc-b345-11e7-9dae-2dfe1b2ba247.png)
(which means the useful demand fertilizers are incorrectly 'whitelisted' as preset demand setters)
![screen shot 2017-10-17 at 14 06 45](https://user-images.githubusercontent.com/32056448/31664163-b262f8c0-b344-11e7-909d-d53a682485db.png)

**Comment by antw** [comment]
> we have to set the haber_bosch thing and all the carrier shares

I think so, but that seems terribly inconvenient for you. 😐

In the short-term I don't think there is any other option; editing the demand of any node not in the `preset_demand` group will likely result in inconsistencies such as this.
