### ISSUE TITLE
Hybrid heatpumps and insulation

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#1387]
Households_insulation_level still contains calculations for hybrid heatpump carrier shares. Since heatpumps are modelled dynamically now, this is probably redundant.

![households_insulation_level_new_houses_ad_ ___projects_etsource](https://user-images.githubusercontent.com/32056448/31765748-c1482ba8-b4c5-11e7-8ab4-4e9975205b28.png)

To do:
- [x] Test if indeed redundant
- [x] If so, clean up code

**Comment by ChaelKruip** [comment]
@MichielDenHaan I have turned the bullets into check-boxes 😄

**Comment by MichielDenHaan** [comment]
w00t!

**Comment by antw** [comment]
Good catch. These might still be necessary for scenarios which have the merit order disabled.

**Comment by michieldenhaan** [comment]
These inputs statements have been replaced since the recent insulation/housing stock updates. Tested HHP behaviour with and without merit and seems to be working fine!
