### ISSUE TITLE
ETM overestimating ambient heat

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#1392]
Ambient heat in the NL 2015 dataset is more than twice as high as CBS statistics (12.3 PJ vs 5.7 PJ). For the NL 2013 dataset and Groningen Ten Boer I noticed a similar divergence.
For 2015, the majority of ambient heat is in the buildings sector (7.9 PJ, heat pump with TS).

Could this high number be caused by an overestimation of the heat pump TS COP?

![buildings_space_heater_collective_heatpump_water_water_ts_electricity_converter_xlsx](https://user-images.githubusercontent.com/32056448/31998673-ecc26cf6-b990-11e7-8577-55b11b07ce41.png)

**Comment by ChaelKruip** [comment]
> Could this high number be caused by an overestimation of the heat pump TS COP?

Possibly. Also by an overestimation of the market share of TS HPs.

**Comment by DorinevanderVlies** [comment]
> Could this high number be caused by an overestimation of the heat pump TS COP?

I think so. The market share is currently determined using data regarding final demand of gas (and electricity) of heat pumps. CBS has roughly 1:3 for gas:ambient. Heat pumps for buildings in ETM have roughly 1:9. So by using FD gas as input to determine the market share the market share is overestimated.

> Possibly. Also by an overestimation of the market share of TS HPs.

For the 2015 dataset we can also determine the market share starting with produced heat. This will lead to more realistic ambient heat, but an underestimation of FD gas by this technology.

**Comment by MichielDenHaan** [comment]
Yes, though it is a bit fragmented. In the buildings sector they assume a COP of 4 for compression cooling (see https://www.cbs.nl/nl-nl/publicatie/2017/15/monitoring-warmte-2015).

Electricity use:
![electricity cooling](https://user-images.githubusercontent.com/32056448/32268724-78c545e8-bef0-11e7-9401-9e28184a6789.png)

Ground:
http://statline.cbs.nl/Statweb/publication/?DM=SLNL&PA=82379NED&D1=1&D2=a&D3=25&HDR=T,G1&STB=G2&VW=T

And:
"Het totale finale energieverbruik voor koude betreft 1% van het totale finale energieverbruik in Nederland in 2015. [...] In 2015 was de totale koude productie uit WKO’s in Nederland ongeveer 2 PJ (CBS, 2016). Dit betreft grotendeels koude voor eigen gebruik in de utiliteitsbouw. De koude uit WKO is ca. 5% van de totale koude productie in de dienstensector. [...] Koudelevering via netten (die meerdere gebouwen bedienen) was in 2015 goed voor 0,4 PJ koude."
