### ISSUE TITLE
ETM underestimating waste heat

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#1395]
In the NL 2015 dataset, renewable waste heat produced by waste chps is 3 times lower than CBS and IEA Energy Balance data (ETM 4 PJ vs CBS 13,5 PJ vs. IEA 11,7 PJ). The reason for this is that the total waste input in the ETM for these chps is set in such way that the electricity produced by waste chps matches the IEA energy balance. However, the heat produced by these chps does not add up to the amount on the energy balance, resulting in a heat deficit.

The electricity/heat efficiencies are based on this 2012 report: https://refman.energytransitionmodel.com/publications/1937. 

![energytransitionmodel](https://user-images.githubusercontent.com/32056448/31999347-3d936e8a-b993-11e7-8ed8-243d6e97c066.png)

If we would use 2017 [RVO](https://www.rvo.nl/onderwerpen/duurzaam-ondernemen/duurzame-energie-opwekken/bio-energie/afvalverbranding) data (20% electrical efficiency, 23% heat efficiency), renewable heat would rise to 8,3 PJ. Still doesn't allign with CBS/IEA but we're getting closer. Part of the residual may be due to the fact that: "Afvalverbrandingsinstallaties zijn complexe installaties met een hoog eigen energieverbruik, vooral voor reiniging van de rookgassen. Deze energie wekken ze voor een groot deel zelf op en de zelf opgewekte en verbruikte energie telt ook mee bij het bruto eindverbruik. Tot voor de revisie was alleen de zelf opgewekte en verbruikte elektriciteit in beeld. Na de revisie wordt ook de zelf opgewekte en verbruikte warmte meegenomen." I cannot find exact numbers for 2015, but the order of magnitude is another +2-2.5 PJ heat.

**Comment by DorinevanderVlies** [comment]
Just to clarify:
Do you propose to change the specs of waste chp's?

I would agree with that.

**Comment by MichielDenHaan** [comment]
I prefer that too but the question is what the new specs should be.. The 23% RVO heat efficiency (most likely) doesn't include the heat used for flue gas cleaning. This now goes into losses. I think it's good to increase heat efficiency to account for flue gas cleaning, but it is hard to find precise data on this. To match IEA/CBS, heat efficiency should be 33%/38% respectively..

**Comment by ChaelKruip** [comment]
> Do you propose to change the specs of waste chp's?

> I would agree with that.

The specs of CHPs have been researched by another consultancy (EnergyMatters) who's expertise lies with CHPs. The good thing about their research is that we now have a 'consistent' data-source for all specs of CHPs. I would like to hear @AlexanderWirtz's opinion on this before we start changing the specs.

**Comment by marliekeverweij** [comment]
@michieldenhaan is this something we want to update during the heat project?

**Comment by michieldenhaan** [comment]
Good suggestion @marliekeverweij, I'll ask HVC if they have data on this. If not, I think we should leave this for now
