### ISSUE TITLE
P2G for industry leads to negative export losses (primary energy use)

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#1412]
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://user-images.githubusercontent.com/32056448/32277607-4d53f9f4-bf13-11e7-8d80-3e3c6d216ebd.png)

**Comment by MichielDenHaan** [comment]
losses_for_exported_energy query:
![losses_for_exported_energy_gql_ ___projects_etsource](https://user-images.githubusercontent.com/32056448/32278416-f6b69680-bf15-11e7-89ba-4f54c552e2e6.png)

Primary demand of hydrogen is 0, demand is positive, resulting in a decrease of energy use:
![hydro](https://user-images.githubusercontent.com/32056448/32278523-440ecdda-bf16-11e7-84c9-0e609bc52f59.png)

**Comment by ChaelKruip** [comment]
@MartLubben is this still happening?

**Comment by MartLubben** [comment]
Hey @ChaelKruip,

Yes it is still happening. I do not see a quick fix. Hydrogen has no primary demand 'yet', so it is always '0' or negative.  I think this is even more complex. When the hydrogen is produced for industry and transport, but not used, then it is not exported, but still a negative export (an import). It is takes as free energy, from curtailed wind electricity. 

@marliekeverweij Do you see a quick fix for the deploy?

**Comment by marliekeverweij** [comment]
Sorry I do not see a quick fix now. 

Actually Michiel and I do not really know the intended behaviour of this chart/table. We have decided that we want to fix this issue during the H2 project. I will make a to-do for it!

Is that okay, @ChaelKruip ?

**Comment by ChaelKruip** [comment]
> Is that okay, @ChaelKruip ?

👍

**Comment by AlexanderWirtz** [comment]
My 2 cts: could this be remedied by creating a hydrogen import node?

**Comment by michieldenhaan** [comment]
Issue was caused by the p2g node, which wasn't in the primary_energy_demand group. Since all electricity going into this node is renewable and since renewable electricity is considered to be primary demand, it should have been in there.

![monosnap 2018-03-29 15-08-11 1](https://user-images.githubusercontent.com/32056448/38090498-149b32f2-3363-11e8-9910-21d3585557a6.png)

**Comment by michieldenhaan** [comment]
For future reference: it turned out that all excess electricity used for flexibility options was not regarded as primary demand. Since all excess electricity is renewable electricity (and renewable electricity is primary), it should have been. The result was that the use of flexibility options led to a decrease in primary demand. In the case of export (as described in this issue), it even led to negative energy flows as primary demand was 0 while export demand was non zero. This is fixed by adding a new excess electricity node, putting it in the primary_energy_demand group and attaching all flexibility options to it (https://github.com/quintel/etsource/commit/8bb136c842b8b495a9e0b059a9a9662ecc994fcc)
