### ISSUE TITLE
Merging fertilizer fix breaks local datasets

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#1417]
https://github.com/quintel/etengine/pull/958 adds new edges to the graph (the purple ones), which breaks the local datasets. As @DorinevanderVlies pointed out, a rake task to update the datasets is not a viable option since all local datasets are based on nl2013 while nl2015 is now the default. She suggested switching back to nl2013 locally, perform the rake task and switch to nl2015 again. Do you guys know what is the best way to do this?

![fert](https://user-images.githubusercontent.com/32056448/32435694-f26ac36a-c2e1-11e7-8432-a63d71d6a5ad.png)

![_failed___build_5_of_etsource_fertilizer_energetic_demand_fix_-_semaphore](https://user-images.githubusercontent.com/32056448/32435944-c081faf2-c2e2-11e7-8a6b-f17d63c4804c.png)

![engine](https://user-images.githubusercontent.com/32056448/32435962-d4ad993c-c2e2-11e7-8025-d4e0b55a0d3e.png)

**Comment by DorinevanderVlies** [comment]
> She suggested switching back to nl2013 locally, perform the rake task and switch to nl2015 again. Do you guys know what is the best way to do this?

I actually also know how to do this and am happy to help you with it.

@antw and @grdw, I'm curious if you have any objections or other suggestions

**Comment by antw** [comment]
No objections, but I think it's easier than switching between NL2013 and NL2015 locally. The derived datasets have [an attribute `base_dataset`](https://github.com/quintel/etsource/blob/70f7a71d54b91f85037c151c4467ecc713b89cc1/datasets/friesland/friesland.derived.ad#L83) which describes the parent dataset.

The derived datasets which are based on 2013 data should have that attribute changed from "nl" to "nl2013". You should then be able to run the Rake task and get the expected result.

**Comment by DorinevanderVlies** [comment]
> The derived datasets which are based on 2013 data should have that attribute changed from "nl" to "nl2013". You should then be able to run the Rake task and get the expected result.

Even better, thanks @antw

**Comment by MichielDenHaan** [comment]
Thanks! The local datasets are ok now, but now semaphore fails at the country datasets:
![rakerefreshgraph](https://user-images.githubusercontent.com/32056448/32443280-ba860e2e-c2fe-11e7-8f04-f5c2f4bf6b54.png)

Any idea how to fix this @antw?

**Comment by antw** [comment]
It seems that for those regions it cannot calculate a demand for "industry_chemicals_fertilizers_haber_bosch_process_hydrogen".

I'm looking into why.

**Comment by MichielDenHaan** [comment]
Yeah that's the node affected by this merge. Currently, the haber_bosch only has hydrogen as an input. Joris added useable heat (the purple lines above). The local datasets broke down because they didn't have a value set for this useable heat, maybe something similar happens for the country datasets?

**Comment by antw** [comment]
> The local datasets broke down because they didn't have a value set for this useable heat

Yes, kind of... these datasets have zero demand for locally available hydrogen and useable heat. As a result, Refinery cannot figure out what the share of hydrogen and heat are as inputs to the "haber bosch process" node.

Here's the **UK**:

![industry_chemicals_fertilizers_haber_bosch_process_ calculable](https://user-images.githubusercontent.com/4383/32446024-811db190-c2ff-11e7-87cb-8e6c882ac80f.png)

And for comparison, **NL** (which has non-zero demands and can compute the shares of the carriers):

![industry_chemicals_fertilizers_haber_bosch_process_ finished](https://user-images.githubusercontent.com/4383/32446143-d65c0af8-c2ff-11e7-8645-86042e09bc7a.png)

**Comment by antw** [comment]
I'm not sure what to suggest here, since it's obvious that Refinery cannot automatically calculate the shares of those carriers when demand is zero. Are you sure that the NL scenario is correct: that is, it is correct to simply dump *all* hydrogen and heat into the "haber-bosch" node? Is there not a known ratio by which these carriers should be mixed?

**Comment by jorisberkhout** [comment]
I'll look into other ways of initializing the graph here.

**Comment by jorisberkhout** [comment]
I fixed this issue by copying the output shares of the steam methane reformer for hydrogen and useable heat to the input shares of the Haber Bosch node. This is not ideal, but fixes all datasets for now.

**Comment by DorinevanderVlies** [comment]
nice!

**Comment by jorisberkhout** [comment]
Closed by #1416 .
