### ISSUE TITLE
Remove duplicate Gqueries

### ISSUE THREAD

**Issue by antw** [quintel/etsource#1420]
I've noticed that we have a number of duplicate Gqueries.

In the presence of multiple Gqueries with the same key we can't be sure which one will take precedence in Atlas.

I intend to make Atlas stricter so this cannot happen again, but first we must decide which of the duplicate queries to keep. In some cases the queries are not identical and may therefore be returning unexpected results.

@ChaelKruip would you mind assigning to whomever you think is most appropriate? I could delete the duplicates myself, but when there are differences I'm not sure which is correct.

---

### `electricity_used_for_heating_in_households.gql` (2)
* [gqueries/general/energy_use/electricity_used_for_heating_in_households.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/general/energy_use/electricity_used_for_heating_in_households.gql)
* [gqueries/output_elements/output_series/bezier_56_heat_production_in_households/electricity_used_for_heating_in_households.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/output_elements/output_series/bezier_56_heat_production_in_households/electricity_used_for_heating_in_households.gql)

⚠️ Similar queries, different units (MJ/PJ).

---

### `electricity_used_for_hot_water_in_households.gql` (2)
* [gqueries/general/energy_use/electricity_used_for_hot_water_in_households.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/general/energy_use/electricity_used_for_hot_water_in_households.gql)
* [gqueries/output_elements/output_series/bezier_65_source_of_hot_water_in_households/electricity_used_for_hot_water_in_households.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/output_elements/output_series/bezier_65_source_of_hot_water_in_households/electricity_used_for_hot_water_in_households.gql)

⚠️ Similar queries, different units (MJ/PJ).

---

### `primary_demand_of_greengas_from_curtailment.gql` (2)
* [gqueries/general/primary_demand/primary_demand_of_greengas_from_curtailment.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/general/primary_demand/primary_demand_of_greengas_from_curtailment.gql)
* [gqueries/output_elements/output_series/mekko_166_primary_demand_of_biomass/primary_demand_of_greengas_from_curtailment.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/output_elements/output_series/mekko_166_primary_demand_of_biomass/primary_demand_of_greengas_from_curtailment.gql)

✅ Identical queries: suggest deleting the "output_elements" query.

---

### `primary_demand_of_greengas_from_export.gql` (2)
* [gqueries/general/primary_demand/primary_demand_of_greengas_from_export.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/general/primary_demand/primary_demand_of_greengas_from_export.gql)
* [gqueries/output_elements/output_series/mekko_166_primary_demand_of_biomass/primary_demand_of_greengas_from_export.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/output_elements/output_series/mekko_166_primary_demand_of_biomass/primary_demand_of_greengas_from_export.gql)

✅ Identical queries: suggest deleting the "output_elements" query.

---

### `final_demand_in_metal_industry_energetic.gql` (3)
* [gqueries/output_elements/output_series/mekko_155_mekko_of_final_demand_in_industry/final_demand_in_metal_industry_energetic.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/output_elements/output_series/mekko_155_mekko_of_final_demand_in_industry/final_demand_in_metal_industry_energetic.gql)
* [gqueries/output_elements/output_series/mekko_179_mekko_of_final_demand_in_industry_nl/final_demand_in_metal_industry_energetic.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/output_elements/output_series/mekko_179_mekko_of_final_demand_in_industry_nl/final_demand_in_metal_industry_energetic.gql)
* [gqueries/output_elements/output_series/mekko_180_mekko_of_final_demand_in_industry_other/final_demand_in_metal_industry_energetic.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/output_elements/output_series/mekko_180_mekko_of_final_demand_in_industry_other/final_demand_in_metal_industry_energetic.gql)

❌ Different queries.

---

### `final_demand_in_metal_industry_non_energetic.gql` (3)
* [gqueries/output_elements/output_series/mekko_155_mekko_of_final_demand_in_industry/final_demand_in_metal_industry_non_energetic.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/output_elements/output_series/mekko_155_mekko_of_final_demand_in_industry/final_demand_in_metal_industry_non_energetic.gql)
* [gqueries/output_elements/output_series/mekko_179_mekko_of_final_demand_in_industry_nl/final_demand_in_metal_industry_non_energetic.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/output_elements/output_series/mekko_179_mekko_of_final_demand_in_industry_nl/final_demand_in_metal_industry_non_energetic.gql)
* [gqueries/output_elements/output_series/mekko_180_mekko_of_final_demand_in_industry_other/final_demand_in_metal_industry_non_energetic.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/output_elements/output_series/mekko_180_mekko_of_final_demand_in_industry_other/final_demand_in_metal_industry_non_energetic.gql)

❌ Different queries.

---

### `final_demand_in_refineries_industry_energetic.gql` (2)
* [gqueries/output_elements/output_series/mekko_179_mekko_of_final_demand_in_industry_nl/final_demand_in_refineries_industry_energetic.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/output_elements/output_series/mekko_179_mekko_of_final_demand_in_industry_nl/final_demand_in_refineries_industry_energetic.gql)
* [gqueries/output_elements/output_series/mekko_180_mekko_of_final_demand_in_industry_other/final_demand_in_refineries_industry_energetic.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/output_elements/output_series/mekko_180_mekko_of_final_demand_in_industry_other/final_demand_in_refineries_industry_energetic.gql)

✅ Identical queries: suggest deleting the "output_elements" query.

---

### `final_demand_in_refineries_industry_non_energetic.gql` (2)
* [gqueries/output_elements/output_series/mekko_179_mekko_of_final_demand_in_industry_nl/final_demand_in_refineries_industry_non_energetic.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/output_elements/output_series/mekko_179_mekko_of_final_demand_in_industry_nl/final_demand_in_refineries_industry_non_energetic.gql)
* [gqueries/output_elements/output_series/mekko_180_mekko_of_final_demand_in_industry_other/final_demand_in_refineries_industry_non_energetic.gql](https://github.com/quintel/etsource/blob/b22d618aadbfdeea7fae51a482fa932afdbfa076/gqueries/output_elements/output_series/mekko_180_mekko_of_final_demand_in_industry_other/final_demand_in_refineries_industry_non_energetic.gql)

✅ Identical queries: suggest deleting the "output_elements" query.

**Comment by ChaelKruip** [comment]
Assigning @MartLubben as I think he will learn a lot from this ticket 😄

**Comment by MartLubben** [comment]
I never say no to a learning opportunity. :p

**Comment by MartLubben** [comment]
Hey all, 
I removed all doubles. 
With the equal queries I followed the advise of @antw . 
With the heat in households and with the metal industry I discussed with @michieldenhaan what to do. We chose to remove the oldest versions and checked the code for mistakes. 

Explanations of choices:

We kept gqueries/output_elements/output_series/bezier_65_source_of_hot_water_in_households/electricity_used_for_hot_water_in_households.gql 
It was 3 months old had PJ as unit but it was divided by BILLIONS. The other was over 4 years old.

We kept gqueries/output_elements/output_series/mekko_179_mekko_of_final_demand_in_industry_nl/final_demand_in_metal_industry_non_energetic.gql 
It was a year old and included hydrogen in the total sum. The query in mekko 180 was equal, made at the same day, but a less logical place. The Query in mekko 155 was 3 years old and did not include hydrogen in the total sum of energy. 

@ChaelKruip I assign you to check this :), ok?

**Comment by ChaelKruip** [comment]
> @ChaelKruip I assign you to check this :), ok?

👍
