### ISSUE TITLE
Cant import pull request that removes Groningen Ten Boer

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#1457]
ETEngine returns an error because 'Groningen Ten Boer' does not exist

**Comment by grdw** [comment]
Todo:

- [ ] Remove all scenarios with `groningen_ten_boer` as area

**Comment by grdw** [comment]
@michieldenhaan is it a proper call to action to remove all scenarios for `groningen_ten_boer`? Please discuss this with somebody. If that's all fine than proceed and merge https://github.com/quintel/etengine/pull/973
