### ISSUE TITLE
Clean up remote branches

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1463]
**In PR/development:**
```
  origin/Cleaning_double_queries
  origin/bump-ruby-version
  origin/fertilizer_energetic_demand_fix
  origin/new_nodes_edges_p2l
  origin/dynamic-heat
```

**Not in a PR (I tagged the person who was the latest commiter):**

Are these branches still in development or are they 'stale'? Remove them if so, thank you! 👍 

@michieldenhaan :
```
  origin/co2-fix-international-aviation
```

@antw :
```
  origin/heat-curve-sets
```

@MartLubben :  
```
  origin/import_slider
```

@jorisberkhout :  
```
  origin/int_trans_alloc
```

**Comment by marliekeverweij** [comment]
Have deleted `origin/chart209` and `origin/new_nodes_edges_p2l` is still in development!

**Comment by DorinevanderVlies** [comment]
I made a pull request for `origin/dynamic-heat` (https://github.com/quintel/etsource/pull/1464) and will remove this branch after it's merged

**Comment by jorisberkhout** [comment]
Closing as no-one is assigned.
