### ISSUE TITLE
Costs of imported electricity are 0 if own production is 0.

### ISSUE THREAD

**Issue by MartLubben** [quintel/etsource#1532]
The costs of imported electricity are based on the average costs of electricity. If you do not produce electricity, the costs are 0. 

`- query =
    IF( V(G(electricity_production),output_of_electricity).sum == 0,
      0,
      PRODUCT(
       Q(costs_of_produced_electricity),
       V(energy_import_electricity,demand),
       INVERSE(V(G(electricity_production),output_of_electricity).sum)
      )
    )
- unit = euro`

![](https://quintel.slack.com/files/U73UD6MPA/F8TCT80F6/freeelectricity.png)

According to @AlexanderWirtz it was the fault of @ChaelKruip :p. #dontshootthemessenger

@jorisberkhout @DorinevanderVlies @michieldenhaan

**Comment by MartLubben** [comment]
![freeelectricity](https://user-images.githubusercontent.com/33415156/34986310-6d920f1e-fab7-11e7-9c89-c5427d3d4b2c.png)

**Comment by ChaelKruip** [comment]
> According to @AlexanderWirtz it was the fault of @ChaelKruip

The GQuery under scrutiny has been introduced in [this commit](https://github.com/quintel/etsource/commit/a8bfc647d5fd985878a73b901b1f31cbdf0650f3#diff-14d7e5bfeba02d209de9c2e66a59625c) which dates from 10 Oct 2011 which was roughly 2.5 months before I joined the company:
![20111215_ao_chael_kruip_getekend_pdf__page_1_of_5_](https://user-images.githubusercontent.com/1303760/34991515-2bffc916-faca-11e7-8afe-50d921ec7186.png)

On a more serious note: the costs of (imported) electricity is not a quantity which can be unambiguously determined unless you explicitly model the region(s) from which this electricity is imported.

One way to deal with this is to let the user assign a price to imported electricity similarly to the CO2-slider. I am not against this perse but it makes the model a bit more complex.

On the other hand, if you allow the user to assume a (fixed) price for imported electricity, this opens up the possibility to include import as a 'dispatchable participant' in the Merit Order. This would be a big improvement of the ETM in my opinion. 

@MartLubben How much time would it take you to add such a slider to the ETM?

A related issue is that the costs of local electricity are not uniquely determined in the ETM at the moment either (see https://github.com/quintel/etmodel/issues/2424 and https://github.com/quintel/merit/issues/61).

**Comment by MartLubben** [comment]
> @MartLubben How much time would it take you to add such a slider to the ETM?

At least less then six years. :)

On a more serious note: The slider will be quite equal to the CO2-slider, with probably the same challenges. We can create a slider, however the start value of the price of imported electricity should be a fixed price. I guess 90% can be done in a day or two, including testing.

**Comment by michieldenhaan** [comment]
I'm in favour of adding an extra slider. It's a bit cumbersome and probably not something users want to think about, but the leverage of locally produced electricity is huge at the moment in local datasets. Most local datasets only have (expensive) solar pv in households/buildings and hence import 99% of their electricity at huge costs. Building 0.05 gas plant units can lead to a 20% drop in overall costs.

**Comment by michieldenhaan** [comment]
![yuge](https://user-images.githubusercontent.com/32056448/34996656-8da1d7e4-fada-11e7-9583-0200735ccc0b.png)

**Comment by ChaelKruip** [comment]
> I'm in favour of adding an extra slider.

I am assigning @MartLubben to first find out if this is an idea that the rest of the team can get behind and, if so, implement this.

**Comment by AlexanderWirtz** [comment]
> According to @AlexanderWirtz it was the fault of @ChaelKruip :p. #dontshootthemessenger

Please note (for posterity's sake) that I was joking...

I like @ChaelKruip's idea for including imported electricity in the merit order (as a virtual plant). I can only think of one caveat: in any realistic future, the price of imported electricity will be anything but static. In fact, it will probably be more volatile than it is now. In my opinion, it should be technically possible (at some point) to upload a price (or cost) curve for imported electricity at some point, overriding the static slider setting. Imports could then participate in the merit order according to said price curve.

Any fix now should keep this in mind.

**Comment by ChaelKruip** [comment]
> In my opinion, it should be technically possible (at some point) to upload a price (or cost) curve for imported electricity at some point, overriding the static slider setting. Imports could then participate in the merit order according to said price curve.

I fully agree. Let's take it one step at a time. A fixed cost is already quite a big one! 
I actually propose to break this up into two parts:
* Add a slider and use its value as the cost of imported electricity
* Change Merit to include import as a participant in the merit order (we need to think about this carefully)

**Comment by michieldenhaan** [comment]
I would very much like to see this solved before the deploy, especially with the launch of ETLocal coming up. Not sure if this is realistic @MartLubben ?

**Comment by michieldenhaan** [comment]
Closing, fixed by https://github.com/quintel/etsource/pull/1570
