### ISSUE TITLE
Rake import csv results in incorrect syntax for input sparse graph keys

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#1584]
Current behaviour:
![graph_values yml zutphen projectsetsourcedatasetszutphen 2018-03-05 09-12-08](https://user-images.githubusercontent.com/32056448/36963924-53e54982-2055-11e8-8fe8-1a854fe175fa.png)

Intended behaviour:
![graph_values yml aalten projectsetsourcedatasetsaalten 2018-03-05 09-12-18](https://user-images.githubusercontent.com/32056448/36963929-5d8446fa-2055-11e8-9562-7b555b10f3a4.png)

**Comment by grdw** [comment]
It's fixed within the commit [here](https://github.com/quintel/etsource/commit/6984159ee3c0e59b60a48b1dced13f0567909df3). So if you switch to the 66-datasets branch it should work as expected.
