### ISSUE TITLE
CO2 emissions of imported electricity are not yet set with the dataset, but fixed.

### ISSUE THREAD

**Issue by MartLubben** [quintel/etsource#1599]
The co2 emissions of imported electricity is in the dataset and in the area file. However this is not (yet) setting the value of the carrier. At this moment the attribute 'co2_conversion_per_mj' of the carrier 'imported_electricity' is fixed with a Dutch average number. 

This has to be made flexible in the (near) future. An FCE way could be an options, but there could maybe be an easier option. The only thing that is needed is to set the attribute of a carrier with a number from the dataset. @ChaelKruip And @antw I am curious about your opinions.

**Comment by michieldenhaan** [comment]
Moved to new issue: https://github.com/quintel/etsource/issues/1766
