### ISSUE TITLE
E-bikes and bikes start in Spain BAU scenario both on 100%

### ISSUE THREAD

**Issue by MartLubben** [quintel/etsource#1605]
![screen shot 2018-03-12 at 16 21 14](https://user-images.githubusercontent.com/33415156/37292619-8351b202-2611-11e8-877b-c2bb9c1f3d4b.png)
@grdw I can recall that there was a migration in the past about the bikes and E-bikes share. Do you know more about this?

**Comment by michieldenhaan** [comment]
![monosnap 2018-04-05 11-40-08](https://user-images.githubusercontent.com/32056448/38358648-204701b8-38c6-11e8-912f-afe43aa35d86.png)
