### ISSUE TITLE
Individual heat percentages don't add up in all cases

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#1636]
See for instance: [https://pro.energytransitionmodel.com/scenarios/357082/factsheet](https://pro.energytransitionmodel.com/scenarios/357082/factsheet)

![image](https://user-images.githubusercontent.com/1303760/37766857-86bba902-2dc8-11e8-8a60-4c3ef95da6e4.png)

I know you are busy but if you could spare a couple of minutes, it would be greatly appreciated if you could have a look at the queries for the individual heat section @antw. I'll try to so the same today.

**Comment by antw** [comment]
The first thing that comes to mind is that [the "total individual heat" query](https://github.com/quintel/etsource/blob/master/gqueries/modules/factsheet/technologies_section/individual_heat/factsheet_supply_of_individual_heat_total.gql#L4) includes `supply_heat_from_electricity` (which is not shown anywhere in the individual heat section) but is missing `factsheet_supply_heat_from_ambient_individual` (which *is* shown).

**Comment by ChaelKruip** [comment]
I think you are right @antw! Can you verify? I am in a meeting until 16:00
