### ISSUE TITLE
Primary CO2 calculation

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#1643]
The primary CO2 of ``transport_useful_demand_freight_tonne_kms`` is higher than the primary CO2 of the sum of all freight vehicles. This is also the case for other useful demand nodes, in households, buildings and industry. Is this intended behaviour?

![httpsbeta-engine energytransitionmodel com 2018-03-23 10-29-46 1](https://user-images.githubusercontent.com/32056448/37821969-75eec90c-2e85-11e8-8a4c-f0addd77806c.png)

![energytransitionmodel httpsbeta-engine energytransitionmodel com 2018-03-23 10-28-53](https://user-images.githubusercontent.com/32056448/37821993-89007446-2e85-11e8-83fe-852b4ee8d2ea.png)

![energytransitionmodel httpsbeta-engine energytransitionmodel com 2018-03-23 10-28-24](https://user-images.githubusercontent.com/32056448/37822004-90e276c8-2e85-11e8-8a24-a81f4a7143a6.png)

**Comment by ChaelKruip** [comment]
Very good catch @michieldenhaan! 

I have reduced the issue to a simpler case:

```
V(transport_useful_demand_ships, primary_co2_emission) => 1,417,214.7625738329 (future)
```

but 

```
V( transport_ship_using_lng_mix, transport_ship_using_diesel_mix, primary_co2_emission) => [954,603.1792506288, 0.0] (future)
```
It seems that querying the primary_co2_emission` directly from a technology node gives different results than querying their (left) parent.

@antw can you think of a reason for this?

BTW: the same goes for `primary_demand`!

**Comment by ChaelKruip** [comment]
I don't want to be too alarmist but we need to find out soon if our primary_demand and related methods are broken for some reason as the whole model hinges on them. 

Added labels "Bugs" and "Priority"...

**Comment by antw** [comment]
> @antw can you think of a reason for this?

Yes. The output conversion of some transport nodes is greater than 1.0. For example [transport_ship_using_diesel_mix](https://beta-engine.energytransitionmodel.com/data/836242/converters/transport_ship_using_diesel_mix) has an output conversion of 1.0116. These output conversions are the only thing which modify the amount of energy flowing between the technology nodes and the useful demand nodes, so it surely has to be this.

**Comment by ChaelKruip** [comment]
> The output conversion of some transport nodes is greater than 1.0

Good point! Mental note for everyone: useful demand is often not really energy but rather 'transport of people' or something other useful. We should not use useful demand in queries unless we really know what we are doing. 

Closing this.

Including @AlexanderWirtz @DorinevanderVlies @MartLubben @grdw @marliekeverweij
