### ISSUE TITLE
Primary demand of (imported) hydrogen queries refer to incorrect carrier

### ISSUE THREAD

**Issue by antw** [quintel/etsource#1658]
[Queries used by the "Primary energy use"](https://github.com/quintel/etsource/tree/22f9ed3ef4689234f551f712fef0e21a7706f338/gqueries/general/primary_demand) chart refer to `primary_demand_of_imported_hydrogen` but no such `imported_hydrogen` carrier exists. I'm guessing this was a temporary thing while hydrogen was in development, and that it should now be `primary_demand_of_hydrogen`?

Ref https://github.com/quintel/etsource/commit/d7ef0589e2587f6b398c8fabd9e1a116e3946e08

**Comment by michieldenhaan** [comment]
The ``imported_hydrogen`` carrier will be added in this PR: https://github.com/quintel/etsource/pull/1657. I'll merge it rightaway
