### ISSUE TITLE
Variable costs of H2 infrastructure is not taken into account

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#1710]
The cost query used in the dashboard refers to the fixed costs:

[https://github.com/quintel/etsource/blob/master/gqueries/general/costs/costs_of_used_hydrogen.gql#L6](https://github.com/quintel/etsource/blob/master/gqueries/general/costs/costs_of_used_hydrogen.gql#L6)

There is more cost associated with the nodes, this is not taken into account....

**Comment by michieldenhaan** [comment]
The only non-fixed costs are fuel costs (hydrogen passing through these nodes), which shouldn't be taken into account to avoid double-counting. 

![variable costs of h2 infrastructure is not taken into account issue 1710 quinteletsource httpsgithub com 2018-05-18 13-17-07](https://user-images.githubusercontent.com/32056448/40232120-d27251a0-5a9d-11e8-9428-b7d3fb8bf2c8.png)

**Comment by ChaelKruip** [comment]
👍
