### ISSUE TITLE
Double counting cost of non energetic oil in transport 

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#1735]
It looks like non-energetic oil for transport(``transport_final_demand_crude_oil_non_energetic``) is included both in ``Q(costs_of_non_energetic_demand)`` and ``Q(costs_of_transport_fuels)``

![energytransitionmodel httpsbeta-engine energytransitionmodel com 2018-06-14 14-46-29 1](https://user-images.githubusercontent.com/32056448/41412971-fe291140-6fe1-11e8-99bb-677ec0f54afd.png)
![energytransitionmodel httpsbeta-engine energytransitionmodel com 2018-06-14 14-45-25 1](https://user-images.githubusercontent.com/32056448/41412978-01123616-6fe2-11e8-9268-ac533d3e47b9.png)

**Comment by DorinevanderVlies** [comment]
Good catch.
Let's remove it from `Q(costs_of_transport_fuels)`
