### ISSUE TITLE
Groups used for multiple purposes

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#1738]
Currently, some of the groups we use serve multiple purposes. E.g. nodes in the ``cost_traditional_heat`` group are included in the cost calculation but this group also determines which technical and financial parameter table shows up in ETModel. This is inconvenient because adding/removing a group from a node for one purpose may have unintended side effects. For example, I want to remove the burner nodes in the refineries sector from the ``cost_traditional_heat`` group (see https://github.com/quintel/etsource/issues/1386) but this also means that the specs table won't show up in ETModel any more. 

My proposal is to use each group for one purpose only. For this specific example this would mean that we create a new group called ``table_traditional_heat`` (for instance).

Like to hear your thoughts @antw, @ChaelKruip

![converter_presenter_data rb etsource-etlocal 2018-06-15 10-00-17](https://user-images.githubusercontent.com/32056448/41457457-fa835044-7083-11e8-9e91-29a033a72188.png)

**Comment by antw** [comment]
Fine with me.

An alternative is to add a new Node attribute that sets which table to show:

```
- presentation_group = traditional_heat
```

This might be a better fit since a node should belong to only 0-1 of these groups.

**Comment by michieldenhaan** [comment]
Good idea! 

Added the new attribute to all nodes here: https://github.com/quintel/etsource/tree/cost-calculation-update
And changed method in the engine here: https://github.com/quintel/etengine/tree/cost-calculation-update

Not yet working tho, is there anything else I need to do?
