### ISSUE TITLE
Mechanical turk fails - primary demand calculation

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#1760]
The ``transport_spec`` of mechanical turk fails on the following: when merit is off and the e-bike share goes up primary demand is expected to go up as well. Currently on BETA primary demand stays the same. The idea behind this spec is that 'human powered' bikes don't consume energy whereas e-bikes do, so increasing e-bikes should lead to more (primary) energy demand.

It looks like primary demand of imported electricity is always zero on BETA (both with merit on and off). On PRO it isn't. See below for screenshots of the same scenario with (almost all) electricity coming from imports.

The culprit seems to be https://github.com/quintel/etsource/commit/610d071389ab63ae8eb320ff6ac1bcc10ec03671. When I revert this commit, primary demand of imported electricity becomes non-zero again and Mechanical Turk passes. However, as @ChaelKruip pointed out, when doing a global search in ETEngine and Merit on ``import_electricity_primary_demand_factor`` no results show up.. So it isn't entirely clear to us how this attribute is used. Maybe you can shine your light on this @antw? 

We also may want to keep https://github.com/quintel/etsource/commit/9b98e4c2ed1b57f53b043f4bc6bf9caf9bc71d06, i.e. ``export_electricity_primary_demand_factor``.

BETA (https://beta-pro.energytransitionmodel.com/scenarios/886414):
![energy transition model - your free independent comprehensive fact-based scenario builder httpsbeta-pro energytransiti 2018-06-25 09-22-22 1](https://user-images.githubusercontent.com/32056448/41836281-83546560-785a-11e8-8b5f-c0dc921bfd4c.png)

PRO (https://pro.energytransitionmodel.com/scenarios/369485):
![energy transition model - your free independent comprehensive fact-based scenario builder httpspro energytransitionmod 2018-06-25 09-26-10 2](https://user-images.githubusercontent.com/32056448/41836385-d5bc6d7a-785a-11e8-98b0-b1735165d0bb.png)

Local:
![energy transition model - your free independent comprehensive fact-based scenario builder httpetmodel test 2018-06-25 09-44-51 1](https://user-images.githubusercontent.com/32056448/41836938-77cfc976-785c-11e8-807e-635ac90ee853.png)

**Comment by ChaelKruip** [comment]
Well spotted @michieldenhaan and thanks for the clear description!

**Comment by michieldenhaan** [comment]
Made a mistake in the global search, ``import_electricity_primary_demand_factor`` is used here:
https://github.com/quintel/etengine/blob/edb364f289f61e812567a3be991f5215e9fd3579/app/models/qernel/recursive_factor/primary_demand.rb

Not sure why we use a factor of 1.82 tho. For imported hydrogen we don't take a primary demand factor into account.

**Comment by michieldenhaan** [comment]
Discussed this with @AlexanderWirtz and @ChaelKruip and we agreed to use a factor of 1.0 instead. This is in line with statistical conventions which state that imported electricity is to be considered primary demand. We tried to trace back the 1.82 factor but it dates back to the pre Github era.
