### ISSUE TITLE
The CO2 emissions of imported electricity should be dataset dependent. 

### ISSUE THREAD

**Issue by MartLubben** [quintel/etsource#1766]
The CO<sub>2</sub> emissions of imported electricity should be dataset dependent, but is independent, see
[this issue](https://github.com/quintel/etmodel/issues/2817).

The carrier [imported electricity](https://github.com/quintel/etsource/blob/master/carriers/imported_electricity.ad#L4) has as attribute `co2_conversion_per_mj`

How could we set the attribute`co2_conversion_per_mj` of the carrier [imported electricity](https://github.com/quintel/etsource/blob/master/carriers/imported_electricity.ad#L4) with the dataset?

The FCE method could be a possible direction of a solution. @ChaelKruip or @antw Do you have an idea how we could do this?

**Comment by antw** [comment]
Adding an imported_electricity.yml file in [datasets/??/fce](https://github.com/quintel/etsource/tree/master/datasets/nl/fce) would probably do the trick; the [wood_pellets.yml](https://github.com/quintel/etsource/blob/master/datasets/nl/fce/wood_pellets.yml) file provides a good example. I'd also have to enable it in ETEngine but that's simple enough...

**Comment by michieldenhaan** [comment]
Will this also work for countries with ``has_fce = false``? It looks like NL is the only country with an FCE analysis. And is it possible to specify imported electricity emissions for local datasets? All FCE carriers are currently symlinked to NL2015. I suspect this might become relevant for a project.

**Comment by antw** [comment]
> Will this also work for countries with `has_fce = false`?

Should do. `has_fce = false` will remove the "Fuel chain emissions" checkbox and sidebar item in ETModel, but won't affect the behaviour in ETEngine. `co2_conversion_per_mj` will be calculated, but [the other attributes](https://github.com/quintel/etengine/blob/master/app/models/qernel/carrier.rb#L11-L15) (exploration, extraction, treatment, etc) will not be.

**Comment by AlexanderWirtz** [comment]
@michieldenhaan it looks like we have a few days to fix this in the Antwerp project, no? The work for that project is scheduled to be done in March.

**Comment by michieldenhaan** [comment]
Yes, I might need a little help from @antw to make the required ETEngine changes. I'll write up a small plan in due course.

**Comment by marliekeverweij** [comment]
We would like to have the `co2_conversion_per_mj` dataset dependent for the following carriers:

- imported_heat
- imported_electricity
- biogenic_waste
- non_biogenic_waste

To accomplish this we need to:

- [ ] add FCE-tabs for all countries to the carrier_source_analysis of these carriers on ETDataset (@marliekeverweij)
- [ ] export the .yml-files from the carrier_source_analysis to the FCE-folders of all national datasets
(@marliekeverweij)
- [ ] enable the co2_conversion-calculation for these carriers in ETEngine (@antw)

How much time would this last step take you @antw? Or is there a list on ETEngine to which we could add the new carriers ourselves?

**Comment by ChaelKruip** [comment]
@marliekeverweij in light of recent discussions on (partially) removing/replacing the FCE module of the ETM I wonder if we should extend the FCE functionality. Perhaps we could seize this opportunity to simplify/replace the FCE sliders and calculations which are not used by many (I think) and are prone to breaking and maintenance (I know)?

**Comment by AlexanderWirtz** [comment]
>  wonder if we should extend the FCE functionality. Perhaps we could seize this opportunity to simplify/replace the FCE sliders and calculations which are not used by many (I think) and are prone to breaking and maintenance (I know)?

The CO2 content of these carriers concerns the emissions associated with using the carriers. That was precisely the part of the FCE functionality that we think may be worth preserving.

**Comment by antw** [comment]
> Or is there a list on ETEngine to which we could add the new carriers ourselves?

[The list of FCE carriers is here](https://github.com/quintel/etengine/blob/4ca6f506cd430213db9374988fdc2eb7bf62a811/app/models/qernel/plugins/fce.rb#L17-L29). If you're not comfortable changing it, I can certainly do it.

**Comment by marliekeverweij** [comment]
I've added `.yml`-files for imported electricity and heat to the FCE-folder of the NL dataset and added the carriers to the list of FCE carriers on ETEngine. This enables the CO2 emissions of imported electricity and heat to be set in the start year 🙂

**However**, the CO2-sliders for imported electricity cannot update the `co2_conversion_per_mj` in the `imported_electricity.yml` file, so the sliders don't do anything now! This is the update-statement:

`UPDATE(CARRIER(imported_electricity), co2_conversion_per_mj, USER_INPUT() / 1000 / MJ_PER_KWH)`

@antw, do you maybe know what I could do to fix this?

FYI these are the branches where I've worked on (I've pushed the changes that I've made):
https://github.com/quintel/etsource/tree/update_fce
https://github.com/quintel/etengine/tree/update_fce

**Comment by antw** [comment]
> @antw, do you maybe know what I could do to fix this?

This is my mistake for not realising that there is a slider to set the future emissions. The value set by the input will be getting overwritten by the value calculated by the FCE module (which will just be taking the number out of the YML file). The FCE module expects to calculate values itself using shares of countries of origin and will therefore overwrite any value already set, assuming it to be incorrect.

I'm afraid that I cannot think of a solution to this right now; there's no way for the FCE module to know that a custom value has been set and that it shouldn't be overwritten.

**Comment by marliekeverweij** [comment]
Okay, thanks for taking a look at it, I understand the issue. 

> I'm afraid that I cannot think of a solution to this right now; there's no way for the FCE module to know that a custom value has been set and that it shouldn't be overwritten.

Then we should go back to the drawing board and think of a different solution. Notifying @michieldenhaan & @AlexanderWirtz as this has influence on the Antwerp project, I will organise a short meeting this week.

**Comment by marliekeverweij** [comment]
This morning @Chael and I thought of a solution to this issue, which I am now going to implement:

1. In the `imported_electricity.yml` can differentiate between CO2-emissions of 'clean' and 'dirty' electricity. Clean electricity has zero co2_conversion_per_mj and dirty electricity has 0.277778 kg/MJ emissions, which is the same as the slider max of 1000 g/kWh. 
2. With the input statement of the CO2 of imported electricity slider we can set the `start_value` of these two forms of electricity, something like this: 

```
- query =
    share_dirty_imported_electricity = USER_INPUT / 1000
    share_clean_imported_electricity = 1 - share_dirty_imported_electricity

    EACH(
      UPDATE_FCE(CARRIER(imported_electricity), clean_imported_electricity, share_clean_imported_electricity),
      UPDATE_FCE(CARRIER(imported_electricity), dirty_imported_electricity, share_dirty_imported_electricity)
    )

```
