### ISSUE TITLE
Update datasets with data currently shown on ETLocal

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etsource#1862]
There are currently two ways in which the demand of industry and agriculture is detemined for local datasets (on beta and on live):

- Old method: use CO2-emissions to scale national energy use of the sector to the municipality
- New method: use total demand (from klimaatmonitor) and divide this using the CO2-emissions of the sectors in the municipality

The numbers on ETLocal show the results of the new method.

### Proposal
Update all local dataset with the new method.

I know that at least the datasets of the municipalities of West- and Midden-Brabant use numbers determined with the old method. This might be the case for more datasets

**Comment by michieldenhaan** [comment]
Closing, overview issue can be found here: https://github.com/quintel/etlocal/issues/126
