### ISSUE TITLE
Old datasets should be replaced with new ones (incl migration for scenario's)

### ISSUE THREAD

**Issue by MartLubben** [quintel/etsource#1876]
do a migration so that all scenarios which are made with dataset A, are replaced by dataset B:
A -> B, then remove A.

flevoland -> PV24_flevoland
friesland -> PV21_friesland
stichtse_vecht -> GM1904_stichtse_vecht
GM0393_haarlemmerliede_en_spaarnwoude -> GM0394_haarlemmermeer
noorderplantsoen -> BU00140201_noorderplantsoenbuurt
reitdiep -> BU00140904_reitdiep

**Comment by antw** [comment]
@MartLubben I've sent [a pull request](https://github.com/quintel/etengine/pull/1034) which will update all user-created scenarios to use the new dataset names. When that's merged, I expect it should be safe to remove the datasets from ETSource.

**Comment by michieldenhaan** [comment]
The old datasets are hidden. I'll remove them on the heat_project branch
