### ISSUE TITLE
Improve infrastructure costs based on publicly available data

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#1942]
There is public data about the gas network in the Netherlands which can be used on national, ..., neighbourhood level to get a very realistic sense of the length of pipes etc. for each region that we currently support in the ETM. Using this data we can improve
* The investment costs for local gas infra
* The typical investment costs for local heat infra (length will be likely closely related to gas infra)

**Comment by marliekeverweij** [comment]
Associated with this issue is the addition of **gas storage costs** (as we are now also modelling storage)!
