### ISSUE TITLE
Should we remove the initializer_inputs and inputs/adjust_scaling folders?

### ISSUE THREAD

**Issue by redekok** [quintel/etsource#1972]
When I worked on the [issue](https://github.com/quintel/etmodel/issues/2992) about changing the solar park slider units from number of units to installed capacity, I encountered two (deprecated?) `number_of_energy_power_solar_pv_solar_radiation` files in the `initializer_inputs` and `inputs/adjust_scaling` folders. These files didn't have to be updated for the fix to work properly. Hence, I'm raising the question whether other files in these folders are still relevant. If not, would it be an idea to remove them? 

Notifying @antw @AlexanderWirtz @ChaelKruip @jorisberkhout @michieldenhaan @marliekeverweij @MartLubben

**Comment by ChaelKruip** [comment]
This is related to the migration of old scenario's. @michieldenhaan knows about the details of this.

**Comment by michieldenhaan** [comment]
The ``initializer_inputs`` are used by some old datasets which we hope to replace soon. There's already an issue about this here: https://github.com/quintel/etlocal/issues/126

AFAIK the ``adjust_scaling`` queries are the territory of @AlexanderWirtz
