### ISSUE TITLE
Shall we remove the NL2012 and NL2013 dataset from ETSource?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#1995]
Currently we are still updating the NL2012 and NL2013 datasets on ETSource, which is quite time-consuming. Would be nice to clean them up!

We know that Paddepoel Noord is still using the N2013 dataset as basis, but we are planning to import that dataset into ETLocal soon. When that is done, could we then remove the NL2012 and NL2013 dataset from ETSource? (Note: they will still be available on ETDataset)

Any objections? @jorisberkhout @AlexanderWirtz @ChaelKruip @antw @MartLubben @DorinevanderVlies @redekok @michieldenhaan

**Comment by AlexanderWirtz** [comment]
no objections on my part

**Comment by marliekeverweij** [comment]
Closed with https://github.com/quintel/etsource/commit/2e6fb6ffba34c81456c52a99c3a77af26ffd9982
