### ISSUE TITLE
Final demand energy sector is overestimated

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2030]
Because of the new chart (with the final energy demand per sector) @michieldenhaan and I were looking into the final demand gqueries and we found out that there was a different outcome for the following queries:

1. `SUM(V(INTERSECTION(G(final_demand_group),SECTOR(energy)),demand)`
this method uses the node group `final_demand_group`
2. `SUM(V(FILTER(LG(final_demand),"sector == :energy"),value))` 
this method uses the edge group `final_demand` and is used in the final energy demand mekko

![Screen Shot 2019-05-23 at 13 46 12](https://user-images.githubusercontent.com/32833996/58250273-51d93580-7d61-11e9-932a-2aef9257e0e1.png)
![Screen Shot 2019-05-23 at 13 46 56](https://user-images.githubusercontent.com/32833996/58250324-7208f480-7d61-11e9-8e04-409650061999.png)
![Screen Shot 2019-05-23 at 13 48 48](https://user-images.githubusercontent.com/32833996/58250542-e93e8880-7d61-11e9-97a4-afbfe58037b2.png)

Apparently the second query also takes into account the demand of the edge [energy_export_coal_gas ---> energy_distribution_coal_gas] and that makes the difference between the two queries! So currently the final demand in the final demand mekko is overestimated (2x).

I think the `final_demand` group should be removed from that edge, don't you think @michieldenhaan ?

**Comment by michieldenhaan** [comment]
> I think the final_demand group should be removed from that edge, don't you think @michieldenhaan ?

Yes! It has been removed from the ``final_demand_group`` as well (https://github.com/quintel/etsource/commit/21749d91caa5f853ad43e331b739b9d7ea1c27ca)

**Comment by marliekeverweij** [comment]
Related to this issue: 
The unused heat from the heat network is now also included in the `final_demand_group`. In the start year this is 27PJ and in the future year it is zero, which is kind of strange.

![Screen Shot 2019-05-24 at 10 01 30](https://user-images.githubusercontent.com/32833996/58313568-28c2ae80-7e0e-11e9-8dac-c065bd2f8a39.png)
