### ISSUE TITLE
Should energy_export_coal_gas be removed from the node-group energy_export?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2036]
We currently model coal-gas as if it is exported. In reality the produced coal-gas is burned and converted into electricity/heat, but we cannot model this proces correctly. Therefore, we have chosen in the past to export the coal-gas and produce the electricity/heat by using coal.

Should `energy_export_coal_gas` be removed from the node-group `energy_export`? 

@AlexanderWirtz @ChaelKruip @michieldenhaan

**Comment by ChaelKruip** [comment]
> Should energy_export_coal_gas be removed from the node-group energy_export?

I think so yes. @marliekeverweij can you make an estimate of the impact of removing it from the group? 

* Is the import-dashboard item affected and its associated water-fall chart?
* Is the export group used for other 'fundamental' calculations (CO2, primary demand)?
* If we remove it from this group, does that energy appear anywhere in the output of the ETM at all? If not, do we still want to include this node in the graph?

**Comment by marliekeverweij** [comment]
> Is the import-dashboard item affected and its associated water-fall chart?

The import-dashboard item is not affected (change is not significant enough), but the waterfall-chart is affected. In the waterfall-chart you can see that there is more "coal" imported in the present and future, because the exported `coal_gas` is not taken into account when the node-group `energy_export` is removed from `energy_export_coal_gas`.

| 'coal' in waterfall | 2015 | 2050 | 
| -- | -- | -- | 
| Incl. `coal_gas`| 0.47 PJ | 0.52 PJ | 
| Excl. `coal_gas`| 0.5 PJ | 0.54 PJ | 

> Is the export group used for other 'fundamental' calculations (CO2, primary demand)?

Yes, the `energy_export` group is used to calculated the primary demand of export for the primary demand mekko (and will be used to calculate the primary demand of export losses when this PR is merged: https://github.com/quintel/etsource/pull/2047)

The group is also used in these queries `primary_co2_of_....._in_export_and_curtailment`, but these queries doesn't seem to be used anywhere.

> If we remove it from this group, does that energy appear anywhere in the output of the ETM at all? If not, do we still want to include this node in the graph?

No, the energy will not appear anywhere when we remove it from the group. However, I do not think we can remove the node, because the energy has to flow _somewhere_. It cannot go to final demand `industry_final_demand_coal_gas` or `energy_cokesoven_consumption_coal_gas`:
![Screen Shot 2019-06-07 at 17 25 49](https://user-images.githubusercontent.com/32833996/59115424-906a1500-8949-11e9-8641-c0fcb367fbda.png)


I actually also think that the node `energy_import_coal_gas` should be removed from the `energy_import` node-group

**Comment by ChaelKruip** [comment]
> The group is also used in these queries primary_co2_of_....._in_export_and_curtailment, but these queries doesn't seem to be used anywhere.

👍 

> No, the energy will not appear anywhere when we remove it from the group. However, I do not think we can remove the node, because the energy has to flow somewhere.

I have a bit of a bad feeling about having energy flowing in the graph which is not represented in the front-end and cannot be manipulated by the user. 
@AlexanderWirtz @jorisberkhout I'm curious about your opinions on this more philosophical topic!

> I actually also think that the node energy_import_coal_gas should be removed from the energy_import node-group

Sounds logical. Have you checked the impact of that change?

**Comment by AlexanderWirtz** [comment]
philosophically agree with @ChaelKruip. When removing, please include @michieldenhaan who has looked at the impact on CO2 of this `coal_gas` issue. The unused/expected `coal_gas` results in higher demand for `coal` for electricity production. I assume the same amount (energetically), so the import and export should balance out. No, this old solution not pretty, but removing one without the other could result in imbalance. It is worth looking into at least. 

**Solution involving better modeling of what happens with coal_gas**
Adding `coal_gas` to the gas mixture used in gas-fired power plants or CHPs is an option. In that case, everything would just work itself out magically through the graph, but it would also result in all `network_gas` users using a tiny amount of `coal_gas`. 

Putting the `coal_gas` into a gas_fired heater which provides heat for the steel making process is an option, except we know that is not what happens with it in the Netherlands (it is put into a power plant owned by Nuon) and would lead to higher emissions for steel making and lower ones for power production. I frankly don't know how to solve this.

**Comment by michieldenhaan** [comment]
Closed in recent steel update: https://github.com/quintel/etsource/pull/2576
