### ISSUE TITLE
Solar PV FLH are currently too low because of performance ratio

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2049]
### Background
**How are full load hours currently calculated in the ETM?**

Solar PV FLH are country-specific and based on a calculation in [this solar_source_analysis - excel](https://github.com/quintel/etdataset/blob/master/source_analyses/eu/2012/2_power_and_heat_plant/solar_source_analysis.xlsx). The current FLH-calculation summarized:

1.  The yearly global irradiation [kWh/m2] in the horizontal, vertical and optimal plane is taken from this source: [European Commision - Photovoltaic Geographical Information System (PVGIS)](http://re.jrc.ec.europa.eu/pvgis/). (However, I cannot acces the interactive map with Yearly Global Irradiation (kWh/m2): http://re.jrc.ec.europa.eu/pvgis/apps/pvreg.php?lang=en&map=europe) 
2. It is assumed that an average solar panel is installed in between the horizontal and optimal plane, therefore the average is taken of the average horizontal and average optimal yearly global irradiation.
3. A performance ratio of 83% is assumed. Specifically, the performance ratio is the ratio of the actual and theoretically possible energy outputs ([source](http://files.sma.de/dl/7680/Perfratio-TI-en-11.pdf)). So in other words: the losses in the converters and cables of the entire solar PV system.
3. From the yearly global irradiation and the performance ratio, we calculate the full load hours: 
**Global Irradation x Performance Ratio = FLH**

**Where are FLH used for?**

For datasets the calculated FLH are used to calculate the **electricity output capacity** of the installed solar PV panels:

- For country datasets the produced solar electricity originates from the IEA Energy Balance
- For regional datasets the produced solar electricity is defined in ETLocal

### Issue

@AlexanderWirtz and I had a discussion about this a few weeks ago and concluded that:

**We should not take into account the performance ratio of solar panels in the FLH-calculation.**

In the ETM only the electricity **output** of solar PV panels is used for calculation: we get the generated electricity (**output**) from the energy balance/ETLocal and, together with the FLH, we set the electricity **output** capacity of solar panels. We do not have to deal with efficiencies, so taking into account the performance ratio is wrong. And therefore the solar PV FLH in the ETM are currently too low. 

**How we do want to calculate the country-specific FLH?**

When we would not take into account the performance ratio for the Netherlands, then the FLH would be 1044 when we would use the current source (which is high!).

Therefore, I think we should find a new source(s)! 

- For Denmark we already use Energinet-input for the FLH. 
- For the Netherlands we could for example use the [PBL-assumption](https://www.pbl.nl/sites/default/files/cms/publicaties/pbl-2019-conceptadvies-sde-plus-plus-2020-zonne-energie_3690.pdf): 950 FLH.

What do you think of this issue? And do you have ideas for good sources? @ChaelKruip @jorisberkhout @DorinevanderVlies @MartLubben @redekok @michieldenhaan @antw?

NOTE: adjusting the FLH will have a huge impact on current scenario's as they are based on installed capacities!

**Comment by michieldenhaan** [comment]
I think FLH should be as close as possible to measured data. Maybe we could use [CBS](https://statline.cbs.nl/Statweb/publication/?DM=SLNL&PA=82610ned&D1=a&D2=5&D3=24-27&HDR=T&STB=G1,G2&VW=T). They report installed capacity and produced electricity. Note that installed capacity is measured at the end of the year while produced electricity is the total throughout the year. For 2015 we could take the average installed capacity of 2014 and 2015 (i.e. average of the start and end of 2015). This gives 1,109,000 MWh production / 1,226 MW installed capacity (average of 1,009 and 1,526) = 876 FLH in 2015.

**Comment by redekok** [comment]
Our solar PV curves are based on the [Open Power System Data](https://data.open-power-system-data.org/time_series/), which among others provides data about the yearly actual solar generation in a country in MW. According to this source, the total production for the Netherlands in 2015 was 980,804 MWh (i.e., slightly less than CBS' 1,109,00 MWh production).

However, I'm not sure if our curve script is somehow based on the FLH defined at ETSource? If so, we would create some kind of circularity by basing our FLH on the production, I guess?

@marliekeverweij, are our solar pv profiles somehow based on the FLH? Or just on the actual solar generation data?

**Comment by marliekeverweij** [comment]
> I think FLH should be as close as possible to measured data. 

I agree! Let's not loose ourselves in theoretical FLH and keep it practical. I think the approach you mention is very logical and easy to explain to others :) 

> @marliekeverweij, are our solar pv profiles somehow based on the FLH? Or just on the actual solar generation data?

No, they are not based on the FLH. We've only normalised the solar (generation) profile from open power system data.

**Comment by MartLubben** [comment]
More important than the best 'number' is a clear and short logic. I like the solution of @michieldenhaan

**Comment by redekok** [comment]
> No, they are not based on the FLH. We've only normalised the solar (generation) profile from open power system data.

Perfect! In that case I'm totally down for @michieldenhaan's solution. 

Btw: is this issue only relevant for solar PV FLH? Or also for other suppliers?

**Comment by AlexanderWirtz** [comment]
> Note that installed capacity is measured at the end of the year while produced electricity is the total throughout the year. 

This is precisely what we use FLH for: to calculate effective average installed capacity for a year, using total production as reported by CBS (this number is more accurate than the number from the Open Power System Data, which relies on the network companies' measured data). 

> For 2015 we could take the average installed capacity of 2014 and 2015 (i.e. average of the start and end of 2015). This gives 1,109,000 MWh production / 1,226 MW installed capacity (average of 1,009 and 1,526) = 876 FLH in 2015.

This is an alternative, indeed. It is interesting to do this for a few years running and see how large the standard deviation would be, otherwise you cannot be sure you aren't using an a-typical year.

The challenge isn't necessarily knowing the FLH for a particular country. A bit of research would help us determine that for the NL: it is based on the actual insolation, deviations from ideal orientations of solar panels vs the incident sunlight etc etc. For the NL you would end up with ~1000 kWh/kWp, a number everyone knows. Then you deviate from that due to a yearly average drop in efficiency (like PBL does) and end up with effective FLH (according to @marliekeverweij PBL uses 950 kWh/kWp). 

In my opinion, the challenge is doing this in a way that doesn't rely on national statistics, but on an international standardizes source.

**Comment by AlexanderWirtz** [comment]
@redekok this is mostly relevant for solar PV. Average effective installed capacity and FLH for wind are also an issue, though.

So, I like @michieldenhaan 's idea IF this method does not lead to a high variance in FLH numbers when done for all years since ~2010 (or whenever a significant amount of solar PV capacity and good statistics became available).

**Comment by ChaelKruip** [comment]
> So, I like @michieldenhaan 's idea IF this method does not lead to a high variance in FLH numbers when done for all years since ~2010 (or whenever a significant amount of solar PV capacity and good statistics became available).

Who has a bit of time to pick this up?

**Comment by marliekeverweij** [comment]
> Who has a bit of time to pick this up?

I can do it!

**Comment by michieldenhaan** [comment]
I checked the variance as suggested by @AlexanderWirtz and the FLHs are surprisingly stable:

![Book1 2019-06-26 12-57-28](https://user-images.githubusercontent.com/32056448/60174808-2ccd5c00-9812-11e9-87d2-49eb578dcb9a.png)


A bit too stable maybe.. 🤔

In any case, I would suggest not updating the current NL2015 FLH for solar. We currently use 867 hours and these CBS numbers suggest 875-876 hours. The difference is very small and not updating would save us a lot of trouble (for example, the energy mix factsheet shows both produced electricity and installed capacity for solar, so if we update FLHs at least one of these numbers will change).

**Comment by michieldenhaan** [comment]
> A bit too stable maybe.. 🤔

The weird thing is that CBS does some kind of correction to filter out weather influences, but they explicitly state that they don't use this for solar:

![Screenshot 2019-06-26 at 13 30 02](https://user-images.githubusercontent.com/32056448/60176511-c5fe7180-9816-11e9-8417-3a78e797e6c8.png)

**Comment by michieldenhaan** [comment]
I sent an email to CBS and they replied that installed solar capacity isn't measured data. It is estimated using electricity production data for each year and assuming the same, fixed FLHs per year (875 FLHs).. In reality FLHs can vary +/- 10% each year. They hope to come up with more accurate data by the end of the year using data from GVOs. However, this data is only available for large-scale PV, for small-scale PV they will continue to use the method described above.

**Comment by AlexanderWirtz** [comment]
875 FLH is really low and it almost seems like they also use some kind of performance ratio here.

**Comment by marliekeverweij** [comment]
The RVO researched the average FLH of solar panels located in the Netherlands in 2014 (report 'Opbrengst van zonnestroomsystemen in Nederland'). They came to 875 FLH based on real generation data. CBS uses these FLH to calculate the solar generation based on installed capacity: 
![Screen Shot 2019-06-27 at 14 56 25](https://user-images.githubusercontent.com/32833996/60268031-c288ea00-98eb-11e9-8aeb-1c3b59508977.png)


So shall we keep the FLH that we have now (867) since the difference is so small?
Please 👍 when you agree! And comment when you disagree.

**Comment by ChaelKruip** [comment]
> 875 FLH is really low and it almost seems like they also use some kind of performance ratio here.

I upvoted the last comment but I think we should consider updating (and thus increasing) the FLH. If @AlexanderWirtz thinks 875 is low, he must agree that our current 867 is *very* low. Me must not be that model which is 'anti-solar' or something in that direction.

**Comment by michieldenhaan** [comment]
ECN has made factsheets about this:
https://energy.nl/category/technology-matrix-nl/sources-nl/solar-nl/

They report 920 FLHs for south oriented PV and 820 for east west (average over a 25 year lifetime).

**Comment by AlexanderWirtz** [comment]
> They report 920 FLHs for south oriented PV and 820 for east west (average over a 25 year lifetime).

Now if we could only work out the average orientation we would have a great nit of documentation on our hands. Is that mentioned anywhere? It looks like 875 is not that bad, after all.
