### ISSUE TITLE
Potential future households roof surface available for solar PV could be calculated more exact

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2062]
Currently the `residences_roof_surface_available_for_pv` is scaled with the total number of residences. We actually do have information available in the AREA-file about the roof surface available for pv **per housing type**: 

![Screen Shot 2019-06-24 at 16 06 00](https://user-images.githubusercontent.com/32833996/60025472-fe2c7580-9699-11e9-81b4-e1435a6a7207.png)

So we could make a more exact calculation of the future potential for pv in households if we want! But I do not know what the priority of this issue is.

**Comment by ChaelKruip** [comment]
Good observation!

@marliekeverweij can you make this more actionable and assign someone? Or perhaps initiate a meeting to force a decision?

**Comment by marliekeverweij** [comment]
We could calculate it better, but that will be kind of hassle:
We have a total roof surface for solar pv in the start year in the AREA-file (`residences_roof_surface_available_for_pv`) Everytime an extra detached house is built we could add the `typical_roof_surface_detached_house_available_for_pv` and when an apartment is broken down we could subtract `typical_roof_surface_apartment_available_for_pv`. But the `residences_roof_surface_available_for_pv` is not calculated with these roof surfaces per housing type, so we will run into problems when a lot of houses are broken down. However, it's not very realistic that that will happen in the future!

Mmmm, I think this does not have priority at the moment. I wanted to identify the issue, so people know who are calculate potential roof surface at the moment, namely: 
`future_residences_roof_surface_available_for_pv = present_residences_roof_surface_available_for_pv * (future_number_of_residences / present_number_of_residences)`
(no distinction made between housing types)

Shall I close the issue again?

**Comment by ChaelKruip** [comment]
> Shall I close the issue again?

Probably best to leave this for now yes.
