### ISSUE TITLE
The flh of curves of CHPs do not correspond with the flh of the CHPs in the ETM

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etsource#2083]
### Problem
The flh of curves of CHPs do not correspond with the flh of the CHPs in the ETM

- The installed capacity (number of units) follows from total demand and flh.
- The curve defines how the total production is divided over the year.
- For households and buildings the heat demand curve is more seasonal than the flh allow. This results periodically (in winter) in more heat and electricity production than can be expected from the number of units installed.
- For industry and agriculture flh of CHPs is lower than can defined by the (flat) curve.

### Details
Full load hours of CHPs are currently defined in the central producers table (see node, example [biogas chp households](https://github.com/quintel/etsource/blob/master/nodes/households/households_collective_chp_biogas.central_producer.ad#L41)).

They are based on information from [EnergyMatters](https://refman.energytransitionmodel.com/publications/1937). 

![image](https://user-images.githubusercontent.com/19907658/60725810-4cfbca00-9f3a-11e9-8876-c18f66367bfc.png)

|Sector||chp curve|flh in ETM|flh corresponding to curve*|
|---|---|---|---|---|
|Households|CHP biogas|G1A|8000|2000|
||CHP network gas|G1A|4500|2000|
||CHP wood pellets|G1A|6000|2000|
|Buildings|CHP network gas|G2A|4500|2450|
||CHP wood pellets|G2A|6000|2450|
|Agriculture|CHP engine biogas|Flat|8000|8000**|
||CHP engine network gas|Flat|3200|8000**|
||CHP engine wood pellets|Flat|6000|8000**|
|Industry|CHP combined cycle gas|Flat|1600|8000**|
||CHP engine gas|Flat|1300|8000**|
||CHP turbine gas|Flat|3200|8000**|
||CHP ultra supercritical coal|Flat|4500|8000**|

\* Average flh of curves for nl2015, nl2016 and nl2017.
** With a flat curve 8760 flh is expected. This is decreased by availability (usually ~0.95). 

### Possible actions

**1. Change flh of technologies to the value that corresponds to the curve**
- Advantage: this will make the ETM is internally consistent.
- Advantage: the peaks of the output will no longer be higher than installed capacity
- Effect: we will not use the flh from EnergyMatters any more
- Effect: datasets and scenarios will not change energetically
- Effect: Installed capacity will change in datasets and scenarios

**2. Change curves to something that corresponds to the flh**
- Disadvantage: for built environment this will lead to very unrealistic curves (less seasonal than actual heating demand)
- Curves will be very fuzzy

**3. Do nothing** 

Curious about your thoughts @AlexanderWirtz @ChaelKruip @jorisberkhout @marliekeverweij @michieldenhaan @redekok @MartLubben @antw

**Comment by michieldenhaan** [comment]
1

**Comment by AlexanderWirtz** [comment]
> Full load hours of CHPs are currently defined in the central producers table (see node, example biogas chp households).

> They are based on information from EnergyMatters.

Wrong. They originate from the CHP analysis step, which passes them to the `energy_producers` table. The _default_ value is that from the EnergyMattters table.

**Comment by AlexanderWirtz** [comment]
This means option #1 is not an option, as this would make it impossible to reproduce the energy balance. Unless I do not understand option 1.

FLH for the built environment will have to change anyway, once we start the Heat networks project. Only then will heat networks (and therefore CHPs) actually respond to actual heat demand curves. The CHPs will then run in a way that either meets these curve, or follow a flatter curve and fill the seasonal heat storage. 

This leads to the solution for all CHPs: my preferred solution would be to get rid of the curves and have all CHPs be dispatchable, with _fair_ marginal costs that take into account that not only electricity is worth something but the heat produced is too. I mean marginal costs where (for CHPs with a steam cycle) only the fuel costs for E-production are used to determine marginal costs.

**Comment by DorinevanderVlies** [comment]
> This means option #1 is not an option, as this would make it impossible to reproduce the energy balance. Unless I do not understand option 1.

The energy part of the energy balance will be reproduces. The number of units installed will differ from the energy balance.

> my preferred solution would be to get rid of the curves and have all CHPs be dispatchable

How will we determine the installed capacity of CHPs? If we set that xx % of demand from the heat network is supplied with CHP's we will first need to determine how many we install (for example using FLH) and after that use Fever (or something alike) to make sure the CHPs respond to heat demand curves. Or will it be possible to let installed capacity follow from annual peak heat demand?

**Comment by AlexanderWirtz** [comment]
> The energy part of the energy balance will be reproduces. The number of units installed will differ from the energy balance.

Of course, I meant the installed capacities are not reproduced. These are obtained (quite accurately) from CBS. In fact, the FLH are so lousy precisely because there are concrete data on the installed capacities of power plants and CHPs in the CBS data. This answers your other question too @DorinevanderVlies

**Comment by DorinevanderVlies** [comment]
> FLH for the built environment will have to change anyway, once we start the Heat networks project. 

After a discussion with @ChaelKruip @AlexanderWirtz @michieldenhaan @DorinevanderVlies we decided to wait for the heat networks project
