### ISSUE TITLE
(How) Should we increase power plant slider maxes?

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#2085]
**Problem**
As pointed out by @MartLubben, in some local datasets the slider max for power plants is too restrictive to display installed capacity in the present. This is generally the case when a large power plant is present in a small region. E.g. one local dataset in Groningen has a 1.8 GW coal plant but the slider only goes up to 500 MW, suggesting that the area only has 500 MW installed.

**Current max**
The current slider max is based on electricity consumption in the present. For most power plants the slider max equals 0.5 times current electricity consumption.

**Proposal for new max**
Let slider max be determined by the _maximum_ of electricity consumption and production. In that way the slider max can never be too small to display installed capacity in the present. To ensure that the user can always increase installed capacity, we can set the slider max equal to 2-3 times present electricity consumption/production (whichever is bigger).

The query for this could look like this:
```present:PRODUCT(DIVIDE(MAX(Q(total_electricity_consumed)*3, Q(total_electricity_produced)*3), V(energy_power_ultra_supercritical_coal,maximum_yearly_electricity_production_per_unit)), V(energy_power_ultra_supercritical_coal, electricity_output_capacity))```

Pros:
- Slider will always correctly display installed capacity
- Slider max will probably never be too restrictive

Cons:
- Slider max may be unrealistically high

@ChaelKruip What do you think about this proposal?
@marliekeverweij Shall I pick this up before or after the deploy?

**Comment by MartLubben** [comment]
I would like to let it happen before the deploy, because W&B is waiting for it with the Hogeland dataset and it is a bug.

**Comment by ChaelKruip** [comment]
> Let slider max be determined by the maximum of electricity consumption and production.

As with Groningen, the local power plant may actually be much larger than the local energy consumption/production. Perhaps it is more robust to set the max to 2 typical power plants? 

>Slider max may be unrealistically high

This downside might be even worse though. 

> What do you think about this proposal?

I think it is probably an improvement although for the long term we might consider something out of the box like allowing the user to fill in a number outside of the slider range...

**Comment by michieldenhaan** [comment]
> the local power plant may actually be much larger than the local energy consumption/production

What I meant is that if we allocate a 1.8 GW plant to an area, then setting the slider max equal to local production will ensure that the max will be at least 1.8 GW

> Perhaps it is more robust to set the max to 2 typical power plants?

Problem is that for larger areas/countries this is probably not enough.

> This downside might be even worse though.

We can try to limit this, e.g. rather than using 3 times current consumption we can make it 1 or 1.5 times and rather than 3 times current total production we can make it 1/1.5 times production of the specific power plant the slider is concerned with. In this way the production part of the MAX operator only becomes relevant when a large plant is present in the area.

> for the long term we might consider something out of the box like allowing the user to fill in a number outside of the slider range...

Like it!
