### ISSUE TITLE
Households biogas CHP should not be in both must-run and dispatchable groups

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#2094]
[This line](https://github.com/quintel/etsource/blob/master/nodes/households/households_collective_chp_biogas.central_producer.ad#L7) contains mutually exclusive groups

[The same goes for Agriculture](https://github.com/quintel/etsource/blob/master/nodes/agriculture/agriculture_chp_engine_biogas.central_producer.ad#L7)

**Comment by marliekeverweij** [comment]
I guess the CHPs should only have the `must_run_electricity_production` group and not the `dispatchable_production` group, right?
