### ISSUE TITLE
Slider max of wind turbines and elektrolyzers are too low for Groningen-Drenthe

### ISSUE THREAD

**Issue by MartLubben** [quintel/etsource#2104]
For the Groningen and Drenthe project the automatically generated slider maxes for wind offshore, elektrolyzers and PtH industry are too low. 

Wind offshore max = 18 GW, scenario demands 19,5. 
Elektrolyzer max = 10 GW, scenario demands ~15 GW

**Comment by michieldenhaan** [comment]
Closed via https://github.com/quintel/etsource/pull/2106
