### ISSUE TITLE
Resetting a slider should return the original values

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2128]
One of our clients found an interesting bug in this scenario: https://pro.energytransitionmodel.com/scenarios/427184

This scenario has -55.0% CO2 reduction. The slider `transport_useful_demand_passenger_kms` is set to 0.7 % / year. When the user changes the value and then hits the reset-button the CO2 reduction is -56.2% and you would expect it to be -55.0% again (and all other dashboard values have also changed from the original values) . 

The interesting thing is, is that when you change the slider value and then type `0.7` instead of resetting the slider; then the CO2 reduction is -55.0% again!

Do you know what's going on?

Notifying @jorisberkhout

**Comment by michieldenhaan** [comment]
This has been fixed already on BETA, see https://github.com/quintel/etmodel/issues/3121

**Comment by antw** [comment]
> This has been fixed already on BETA

Can confirm. I double checked for my own peace of mind, and the original value from the parent scenario _is_ restored when pressing "reset".
