### ISSUE TITLE
Do large-scale batteries have correct storage volume?

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#2134]
When comparing large-scale batteries with underground pumped storage I noticed that the former store much less electricity than the latter with the same installed capacity:

![beta-pro energytransitionmodel com - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario build… 2019-10-11 15-29-26](https://user-images.githubusercontent.com/32056448/66655475-69478b00-ec3c-11e9-8534-57a9092272ae.png)

![beta-pro energytransitionmodel com - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario build… 2019-10-11 15-29-39](https://user-images.githubusercontent.com/32056448/66655479-6b114e80-ec3c-11e9-8c7d-ca11545b70c1.png)

When looking at the specs, it turns out that both batteries and pumped storage have a ``typical_input_capacity`` of 500 MW. The ``storage.volume``, on the other hand, differs a lot: 129 MWh for large-scale batteries and 8400MWh for pumped storage.

@marliekeverweij , @redekok Do you know if this is correct?

![energy_flexibility_mv_batteries_electricity converter ad — etsource-etlocal 2019-10-11 15-33-32(1)](https://user-images.githubusercontent.com/32056448/66655725-deb35b80-ec3c-11e9-96d6-5a99242b5cb3.png)

![energy_flexibility_hv_opac_electricity converter ad — etsource-etlocal 2019-10-11 15-33-59(1)](https://user-images.githubusercontent.com/32056448/66655714-d4915d00-ec3c-11e9-8216-54a38a9d1372.png)

**Comment by redekok** [comment]
I am not really sure what the sources behind these specs are, actually.. @marliekeverweij would you know this?

**Comment by marliekeverweij** [comment]
Good one!

The `electricity_output_capacity` is correct for both, but I forgot about the input capacity!

OPAC

-  output capacity = 1400
- efficiency = 80%
- input capacity = 1400/0.8 = 1750

MV Batteries

- output capacity = 100
- efficiency = 85%
- input capacity = 100/0.85 = 117.65

I will adjust it!
