### ISSUE TITLE
NL2017 total demand curve has too many points

### ISSUE THREAD

**Issue by antw** [quintel/etsource#2152]
d9d6bc6 added new demand curves for NL2017. [The total_demand.csv curve](https://github.com/quintel/etsource/blob/07b13e97dc433e6ac2a7e869f3ba03c2f5d3881e/datasets/nl2017/curves/total_demand.csv) contains 8808 points instead of 8760 which prevents it from being useable in ETEngine. This affects any dataset which uses NL2017 curves.

@redekok Would you mind checking the source of this curve (in ETDataset?) and import a fresh copy to ETSource?

I'll add an ETSource test to prevent this recurring (#2151).

Sentry ref ETENGINE-2J

**Comment by redekok** [comment]
Good catch! It seems as if the [NL2016 total_demand.csv curve](https://github.com/quintel/etsource/blob/07b13e97dc433e6ac2a7e869f3ba03c2f5d3881e/datasets/nl2016/curves/total_demand.csv) only contains `nan` values so I'll look into that one as well.
