### ISSUE TITLE
All nodes in biomass sankey should balance again

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2173]
After the heat network merge some nodes in the biomass sankey do not balance anymore: central heat production and electricity production. @redekok and I discovered this because of failing MT tests :boom: However, we cannot figure out where this imbalance comes from...

![Screen Shot 2019-12-31 at 15 07 51](https://user-images.githubusercontent.com/32833996/71623814-5a3efc00-2bdf-11ea-9fb4-196d6d68d4e4.png)

@michieldenhaan do you have an idea?

**Comment by michieldenhaan** [comment]
It looks like ``energy_heat_burner_waste_mix`` is the culprit. This heater has an efficiency of 104%, which causes output to be greater than input

![beta-engine energytransitionmodel com - EnergyTransitionModel 2020-01-02 17-35-41](https://user-images.githubusercontent.com/32056448/71678878-7fba3a00-2d86-11ea-98be-c64abe59f3a7.png)

**Comment by michieldenhaan** [comment]
I suspect the same to occur with the gas heater and back-up heater btw if the greengas share in network gas is > 0 as these heaters also have efficiencies > 100%. This also occurs on PRO but has gone unnoticed so far as the MT spec only checks an empty NL scenario and an NvdT scenario, both of which don't have gas heaters installed

**Comment by michieldenhaan** [comment]
Closed via https://github.com/quintel/mechanical_turk/commit/4fcbea28686382d92c6ce1c6ea51ff133c4f2c8a
