### ISSUE TITLE
Electricity production should not be lower than electricity demand in chart 99 on BETA

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2178]
Electricity production is lower than demand in chart 99 for the`nl` dataset on BETA

![Screen Shot 2020-01-10 at 14 47 42](https://user-images.githubusercontent.com/32833996/72159796-7439c500-33bd-11ea-8898-baf6a6a2fcd8.png)
![Screen Shot 2020-01-10 at 14 48 29](https://user-images.githubusercontent.com/32833996/72159842-89aeef00-33bd-11ea-9186-d1e685852830.png)

**Comment by michieldenhaan** [comment]
This has been fixed by @antw with: https://github.com/quintel/etengine/pull/1089
