### ISSUE TITLE
Output capacities are inconsistent for energy_chp_combined_cycle_network_gas

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#2191]
Current specs of energy_chp_combined_cycle_network_gas:
``- output.electricity = 0.42``
``- output.steam_hot_water = 0.43``
``- electricity_output_capacity = 120.0``
``- heat_output_capacity = 117.2093``

When calculating the input capacity of this plant, we can either do:
120.0 / 0.42 = 285.7 MW
or
117.2093 / 0.43 = 272.6 MW
Which gives different results

Maybe the output capacity calculation in ETDataset is refering to the wrong cells. If we do:
120.0 / 0.43 = 297.1 MW 
117.2093 / 0.42 = 279.1 MW (swap the output efficiencies)

Might be the case for more nodes.

**Comment by ChaelKruip** [comment]
Good catch @michieldenhaan! Perhaps we can make a spec for this @antw @noracato ?

**Comment by marliekeverweij** [comment]
Putting this issue on hold for after the heat project merge. See: https://github.com/quintel/etsource/pull/2197#issuecomment-580219366
