### ISSUE TITLE
Weather conditions feature is broken on BETA

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#2214]
I get this error when trying to change weather curves:

![beta-pro energytransitionmodel com - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario build… 2020-02-13 09-08-34](https://user-images.githubusercontent.com/32056448/74413827-753c9700-4e40-11ea-9269-b8155104f008.png)

Caused by this commit? https://github.com/quintel/etsource/commit/4333023a05c91243c6f2b98bb4527f30b4772802

**Comment by redekok** [comment]
I'm on it! I'm partly fixing it manually right now so it would be nice if you could take a look at https://github.com/quintel/etsource/issues/2216 to make sure the import:curve task works well in the future @noracato. :-)
