### ISSUE TITLE
The import:curves task shouldn't symlink NL weather_conditions.csv to other country datasets

### ISSUE THREAD

**Issue by redekok** [quintel/etsource#2216]
The weather conditions feature should only be available for NL country and regional datasets, not for other country datasets. If a country lacks a curves-related csv file on ETDataset, the import:curves task creates a symlink to the NL file. This shouldn't happen for `weather_conditions.csv`.

**Comment by noracato** [comment]
Closed by quintel/etdataset#839 and #2220
