### ISSUE TITLE
The heat demand profile in buildings should be updated

### ISSUE THREAD

**Issue by MartLubben** [quintel/etsource#2256]
During the meeting of Martijn we discussed that the heat demand profile in buildings should match the household heat demand profile. At this moment the peaks take place in other weeks, especially when the dunkelflaute is activated.

![Screenshot 2019-11-21 at 12 24 43](https://user-images.githubusercontent.com/33415156/69333929-f2011000-0c59-11ea-8ea0-e3c656ae06ca.png)
![Screenshot 2019-11-21 at 12 24 35](https://user-images.githubusercontent.com/33415156/69333930-f2011000-0c59-11ea-9f94-72600b85469d.png)

Notifying @chael, @marliekeverweij, @DorinevanderVlies @michieldenhaan and @AlexanderWirtz

**Comment by michieldenhaan** [comment]
AFAIK only household profiles are currently affected by the weather years right?

**Comment by marliekeverweij** [comment]
Another improvement that should be made to the buildings heat demand curve: 

It should be depended on the outside temperature curve, just as for households. Currently the buildings do not respond to different weather years

**Comment by DorinevanderVlies** [comment]
Indeed, for buildings we currently use the G2A gas curve. There are no proper curves available for buildings. AFAIK, this is work in progress at TNO. @ChaelKruip attended the last meeting about this.

https://github.com/quintel/etdataset/tree/master/curves/demand/buildings/space_heating
