### ISSUE TITLE
Some technologies are installed for **three** different purposes

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#226]
A ground heatpump can be chosen in households in the slides for **heating, hot water and cooling**. The **costs of such a technology is currently counted more than double!**
Double because of heating and hot water (See #225) and more than double (but not triple) because of cooling. In the last case, the number of units of the technology does not scale with the number of households (as is the case in heating/hot water) but with the demand itself. The error made by cooling technologies is therefore smaller.

**Comment by jorisberkhout** [comment]
Removing milestone.

**Comment by jorisberkhout** [comment]
Superseded by https://github.com/quintel/etmodel/issues/2185

**Comment by ChaelKruip** [comment]
Closing.
