### ISSUE TITLE
Should we use a  profile (E3D instead of G2C) for the ICT sector?

### ISSUE THREAD

**Issue by redekok** [quintel/etsource#2294]
Recently, a client asked for our motivation to use the NEDU G2C profile for the other industry. Since the G2C profile is a gas profile, it seems a bit odd to use it for the electricity demand as well. The client suggested to use the "flatter" NEDU E3D profile for the ICT sector, since the electricity demand of datacenters is presumably rather constant. 

![image](https://user-images.githubusercontent.com/5946498/84012008-2f6b8780-a977-11ea-8df3-d4d0eb4cccd8.png)

**Comment by ChaelKruip** [comment]
Closing this as https://github.com/quintel/etsource/issues/2295 seems to be a better duplicate :)
