### ISSUE TITLE
We should use a "flatter" profile (NEDU E3D instead of G2C) for the ICT sector

### ISSUE THREAD

**Issue by redekok** [quintel/etsource#2295]
Recently, a client asked for our motivation to use the NEDU G2C profile for the other industry. Since the G2C profile is a gas profile, it seems a bit odd to use it for the electricity demand as well. The client suggested to use the "flatter" NEDU E3D profile for the ICT sector, since the electricity demand of datacenters is presumably rather constant. The E3D profile concerns a load profile for electricity demand of large consumers with a high number of full load hours. It sounds as if this profile (E3D) better matches data centers than the one we currently use (G2C).

![image](https://user-images.githubusercontent.com/5946498/84012008-2f6b8780-a977-11ea-8df3-d4d0eb4cccd8.png)

I'm very curious what @ChaelKruip @AlexanderWirtz @DorinevanderVlies and @michieldenhaan think.

**Comment by ChaelKruip** [comment]
> The client suggested to use the "flatter" NEDU E3D profile for the ICT sector, since the electricity demand of datacenters is presumably rather constant.

I agree that this profile would be an improvement 👍

**Comment by michieldenhaan** [comment]
Me too! Let's also use E3D for the (not heat related) electricity demand of the other industry sectors currently using G2C (food, paper, non-specified)

**Comment by DorinevanderVlies** [comment]
> Let's also use E3D for the (not heat related) electricity demand of the other industry sectors currently using G2C (food, paper, non-specified)

I'm not sure about this. For "pure" electricity demand, yes. But, for electricity which is used for heating the current gas curve probably reflects the heat demand more accurately than the current electricity curve.

Therefor I would propose to only change the curve for the ICT sector.

**Comment by michieldenhaan** [comment]
That's what I meant, use it for the non-heat related demand nodes like the useful demand nodes (not the boiler nodes)

**Comment by marliekeverweij** [comment]
Removing deploy milestone as there was still some discussion about how to implement this last Friday. Main question was: should it be added to the weather year feature? The client was suggesting this.

As @DorinevanderVlies mentioned the E3D profile has no week/weekend-rythm and baseload electricity demand is not influenced by the weather / outside temperature. So there is no point in adding it to the weather year feature! This should be communicated with the client and then we can just update the profile. But not before this deploy, as it will need some testing :) Adding it to next deploy.

**Comment by DorinevanderVlies** [comment]
The E3D profile does have a week/weekend rythm. 
However, the weather year does not have a week/weekend rythm.
> As @DorinevanderVlies mentioned the E3D profile has no week/weekend-rythm and baseload electricity demand is not influenced by the weather / outside temperature.

Small correction: E3D does have a week/weekend-rythm. But, so do most of our curves which are not part of the weather years.

The main point is that E3D is not weather dependent.
