### ISSUE TITLE
Rename gquery files from *.gql to *.ad

### ISSUE THREAD

**Issue by antw** [quintel/etsource#2309]
It's inconsistent that our gquery files have a `.gql` extension instead of `.ad`; everything else loaded by Atlas uses `.ad`. I propose renaming the gquery files to also use .ad.

Advantages:

* More consistent.
* Slightly simpler in Atlas.

Disadvantages:

* Tracking file history is harder. `git log -u [PATH]` will only show changes since the file was renamed. You have to remember to add `--follow` to also include changes before the file was renamed: `git log -u --follow [PATH]`.

Opinions @quintel/core?

**Comment by redekok** [comment]
Fine with me!

**Comment by michieldenhaan** [comment]
I'm a bit worried about potential duplicate file names. E.g. `energy_heat_flexibility_p2h_boiler_electricity` is both a node name (ad file) and a query (gql file). At the moment the file extension makes it easy to distinguish the query from the node/input.

If we decide to ditch gql I would prefer not to have files with identical names. But renaming various queries is something we have to think through carefully.

See:
https://github.com/quintel/etsource/blob/master/nodes/energy/energy_heat_flexibility_p2h_boiler_electricity.ad
and
https://github.com/quintel/etsource/blob/master/gqueries/output_elements/output_series/d3_173_merit_order_hourly_flexibility/energy_heat_flexibility_p2h_boiler_electricity.gql

**Comment by antw** [comment]
> At the moment the file extension makes it easy to distinguish the query from the node/input.

Fair point; I hadn't considered that. The first directory name helps distinguish one from the other, but I imagine that's not as easy when looking at file names, and those names are as long as gquery paths tend to be.

@michieldenhaan In what situations might this apply? Most command line tools will have workarounds if you're looking for one of these files specifically, but I can see how the .gql extension would be useful if you use Cmd+T/Ctrl+P in your text editor (personally I often don't with ETSource; there are so many files it's worse than useless, but YMMV).

**Comment by michieldenhaan** [comment]
Yes mainly Cmd+T in my text editor. One thing I disliked about the (no longer existent) initializer inputs was that the file names were identical to the file names of the regular inputs, causing them to pop-up in my editor constantly. For queries this issue will be less prominent as the file paths and file content are more distinct from nodes/inputs but it could be annoying nonetheless.

Ideally, I think we should try to avoid using query names that are identical to node or input names. For queries, such a name is usually not very informative. E.g. the name `energy_heat_flexibility_p2h_boiler_electricity` does not tell you whether the query returns a demand or a curve or something else. But it could be a pain to rename them.
