### ISSUE TITLE
CO2 emissions of non-biogenic waste should be consistent in non_biogenic_waste.ad, carrier overview (beta-engine) and documentation.

### ISSUE THREAD

**Issue by MartLubben** [quintel/etsource#2339]
Our documentation states that non-biogenic waste has no CO2-emissions: https://docs.energytransitionmodel.com/main/co2-calculations/

In the ETM is has emissions, see:

- example scenario:  https://beta-pro.energytransitionmodel.com/saved_scenarios/4530
- non_biogenic_waste.ad:
![image](https://user-images.githubusercontent.com/33415156/91275993-2e314600-e781-11ea-8389-6a6417f8b178.png)

- The carrier overview in beta: https://beta-engine.energytransitionmodel.com/inspect/1340219/carriers 

It the kg CO2 / MJ differs between the latter two. Which one is right?

**Comment by michieldenhaan** [comment]
The documentation is outdated, we do take non-biogenic emissions into account. These emissions can be region/country-dependent. The carrier overview shows the correct number for that specific scenario.
