### ISSUE TITLE
Cost calculations for power plants for district heat need to be reassessed

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etsource#236]
We need to come up with a long-term and short-term solution to the problem that these power plants (`energy_chp_...`) are unfairly represented in the Merit Order calculation, because additional fuel costs are taken into account, whereas additional income for heat sold is not.

We have already decided after discussion with Sytse Jelles that these plants should not have higher marginal costs than their `energy_power_...` technological equivalents.

**Comment by ChaelKruip** [comment]
Isn't the IEA convention the same as what I propose [here](https://github.com/quintel/etsource/issues/236#issuecomment-31345863)?

This is the info in the Introduction page of the CHP analysis:
![screenshot_13_04_16_12_27](https://cloud.githubusercontent.com/assets/1303760/14491256/0c4113de-0178-11e6-8534-98b8046608d8.png)
I could not find the 'documentation' which it refers to...

@AlexanderWirtz can you please comment on these two points?

**Comment by AlexanderWirtz** [comment]
I must admit I am also looking through the documentation and conot find it now. There is some elaborate document explaining it though. Good thing GitHub now has a wiki, as the documentation is pretty hard to navigate. I owe you this one.

IEA says:
`fuel_used_for_heat = total_fuel_input * (heat_efficiency / (heat_efficiency + electrical_efficiency))`

This is not quite the same as the method you propose as that would allocate fuel use to 
- electricity output
- heat ouput
- losses

The IEA method effectively shares the fuel use for losses between the two other outputs.

**Comment by ChaelKruip** [comment]
> The IEA method effectively shares the fuel use for losses between the two other outputs.

I like that better and is a refinement I was about to suggest :smile:

**Comment by AlexanderWirtz** [comment]
Great minds etc

**Comment by michieldenhaan** [comment]
Closing, CHPs are now dispatchable in Merit, marginal costs for steam cycle CHPs have been adjusted
