### ISSUE TITLE
Number of residences doesn't update many sources of household demand

### ISSUE THREAD

**Issue by antw** [quintel/etsource#2371]
* **Expectation:** Changing the number of residences should change the demand for cooking heat, cooling, hot water, etc.

* **Actual result:** Demand for cooling and space heating is adjusted, but cooking, hot water, and lighting demands are unchanged.

* **Steps to reproduce:** Start a new NL2050 scenario and reduce the "Number of residences" slider to 1. Setting it to zero results in an error due to the hybrid heat pump having no profile (zero number of units) with a non-zero demand.

---

| Key | Present | Future |
| :-- | --: | --: |
| households_useful_demand_cooking_useable_heat | 9.28 B | 9.28 B ❌ |
| households_useful_demand_for_cooling | 28.27 B | 3,726.1 ✅ |
| households_useful_demand_for_space_heating_after_insulation | 272.95 B | 35,971.6 ✅ |
| households_useful_demand_hot_water | 47.49 B | 47.49 B ❌ |
| households_useful_demand_light | 824.95 M | 824.95 M ❌  |

[Example scenario](https://beta-pro.energytransitionmodel.com/saved_scenarios/4686) (beta). [ETEngine query](http://localhost:3000/inspect/1338053/gqueries/test?query=TXT_TABLE(V(households_useful_demand_cooking_useable_heat,%20households_useful_demand_for_cooling,%20households_useful_demand_for_hot_water_after_solar_heater,%20households_useful_demand_for_hot_water_for_houses_with_solar_heater,%20households_useful_demand_for_space_heating_after_insulation,%20households_useful_demand_hot_water,%20households_useful_demand_light),%20key,%20demand)) (beta). The issue also occurs in the production environment.

I think this is because the households_number_of_residences input [has lines for cooling and space heating (22-23)](https://github.com/quintel/etsource/blob/24f1a1b0742e75cb983f0384e62a1df3f7e09fe4/inputs/demand/households/households_misc/households_number_of_residences.ad#L22-L23), but not other demands.

@marliekeverweij I'm not sure if you're the correct assignee for this. Please reassign as you see fit.

Including @michieldenhaan.

**Comment by redekok** [comment]
> Expectation: Changing the number of residences should change the demand for cooking heat, cooling, hot water, etc.

Aren't these all dependent on the number of inhabitants (instead of the number of residences)? In theory, there is no linear relation between the number of inhabitants and number of residences I guess. Therefore, increasing or decreasing the number of residences doesn't have to affect the demands for cooking, hot water and lighting. It does imply that the average number of people per residence changes.

**Comment by marliekeverweij** [comment]
> Aren't these all dependent on the number of inhabitants (instead of the number of residences)?

Yes that's indeed the case! See the input statement for number of inhabitants: https://github.com/quintel/etsource/blob/master/inputs/demand/households/households_misc/households_number_of_inhabitants.ad 
That slider updates:
        households_useful_demand_light,
        households_useful_demand_cooking_useable_heat,
        households_appliances_dishwasher_electricity,
        households_appliances_fridge_freezer_electricity,
        households_appliances_vacuum_cleaner_electricity,
        households_appliances_washing_machine_electricity,
        households_appliances_clothes_dryer_electricity,
        households_appliances_television_electricity,
        households_appliances_computer_media_electricity,
        households_appliances_other_electricity,
        households_useful_demand_hot_water

So I think that gives an answer to this issue right @antw ?

I do think that's not realistic to demolish all houses in a region. For inhabitants it's limited by half of the current number of inhabitants. I would propose to set the minimum number of residences to 025*the current number residences. This would also solve the HHP error

**Comment by antw** [comment]
> Aren't these all dependent on the number of inhabitants

I see! I think what tripped me up was that decreasing the number of households would eventually cause deficits in the supply of hot water, but in the light of a fresh day I realise this makes perfect sense: fewer households = fewer heaters installed = less capacity to generate heat.

**Comment by marliekeverweij** [comment]
Closing this issue. We can create a new one for the HHP error @antw pointed out. I did not get the error, so could you make that issue @antw?

> @antw : Setting it to zero results in an error due to the hybrid heat pump having no profile (zero number of units) with a non-zero demand.
