### ISSUE TITLE
Domestic CO2 emissions should include emissions from exported hydrogen

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etsource#2409]
The query `co2_emissions_of_final_demand_excluding_energy_produced_abroad.gql` is used to calculate the dashboard item "Domestic CO2 emissions". It currently subtracts the CO2 emissions of energy produced abroad from the total CO2 emissions, and then adds the CO2 emissions of exported electricity:

```
- query =
    Q(total_co2_emissions) + Q(co2_emissions_of_exported_electricity) - Q(co2_emissions_of_energy_produced_abroad)
- unit = kg
```

The query `co2_emissions_of_energy_produced_abroad.gql` takes into account the emissions of imported heat, hydrogen and electricity. The emissions of energy 'consumed' abroad should therefore logically not only take into account the emissions of exported electricity, but also those of heat and hydrogen.

Given that the ETM has no export function for heat, only the emissions for exported hydrogen need to be added. The proposed solution is to add a new query `co2_emissions_of_energy_consumed_abroad.gql` and put the emissions of exported electricity en export hydrogen in that new query.

@michieldenhaan what do you think of this solution?

**Comment by michieldenhaan** [comment]
Yes I agree! Two remarks:

- I think the issue title should be 'include' rather than 'exclude'
- `co2_emissions_of_energy_consumed_abroad.gql` can be a bit confusing. We are only interested in the energy that is _produced_ domestically but _consumed_ abroad. Maybe `co2_emissions_of_exported_electricity_and_hydrogen` would be more informative?

**Comment by mabijkerk** [comment]
I understand the confusion with the title. I meant to show that exported hydrogen needs to be subtracted from the total emissions as well to get the right value for domestic emissions.

I think the same comment you have for `consumed_abroad` applies to `produced_abroad`: we are only interested in the energy that is _produced_ abroad and _consumed_ domestically. I will think some more on fitting names for these queries.

**Comment by marliekeverweij** [comment]
Should this issue be picked up before the deploy?

**Comment by mabijkerk** [comment]
It's relatively easy to fix this issue so I would say that it's preferable to fix it for the coming deploy.
