### ISSUE TITLE
How can the peak load present differ from the peak load future in a new scenario?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2414]
I have just opened a fresh NL scenario and had a look at the peak loads present and future. I would expect these to be the same as the residual load curve (and thus the peaks) hasn’t changed between present and future. However, I see significant differences:
![Electricity network capacity and peaks 810059](https://user-images.githubusercontent.com/32833996/107956375-603c9b80-6f9f-11eb-9083-0d7f62403009.png)

Could somebody explain to me where these differences come from? @quintel/core 
Assigning @jorisberkhout and @MartLubben as you're the electricity network calculation experts :)

**Comment by mabijkerk** [comment]
I encountered a similar issue for the carbon emissions. I opened a blank scenario for the Netherlands and obtained different emissions for 2015 and 2050 - without having made any changes. I would expect these to be the same.

![CO2 emissions undefined](https://user-images.githubusercontent.com/67338510/107956840-08526480-6fa0-11eb-9e43-877dbde731a4.png)

**Comment by antw** [comment]
> I encountered a similar issue for the carbon emissions.

That seems to be related to the merit order, which isn't used for calculating the present. A slightly different mix of (dispatchable) technologies may result in a change in emissions.

The same might be true for the electricity network peak load, but it's not immediately obvious since that table isn't available when hourly calculations are turned off.

**Comment by marliekeverweij** [comment]
Thanks for you quick replies.

I understand now why the peaks change: many CHPs are not running in the future with merit ON and these CHPs are connected to the MV-grid. In the future larger power plants run (coal plants, gas CCGT) and these are connected to the HV-grid. Therefore, the MV peaks in the future are lower and the HV peaks in the future are higher

![Screenshot 2021-02-15 at 15 24 07](https://user-images.githubusercontent.com/32833996/107958203-fa054800-6fa1-11eb-9736-a2d036cf598f.png)

![Screenshot 2021-02-15 at 15 23 26](https://user-images.githubusercontent.com/32833996/107958140-e22dc400-6fa1-11eb-9b7b-3cb7eb2b44a3.png)
