### ISSUE TITLE
Add queries for new P2P hourly stored volume chart

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2417]
This chart should show the hourly stored volumes for all P2P technologies. At the moment there is no chart focusing on this behavior and it's interesting to know what P2P is exactly doing! 

We would like to show the technologies below in the chart:

- [x] household batteries
- [x] vehicle-to-grid
- [x] large-scale batteries
- [x] pumped hydro storage
- [x] underground pumped hydro storage

@antw what is the best way to query the hourly stored volume of a technology?

**Comment by antw** [comment]
> what is the best way to query the hourly stored volume of a technology?

This isn't yet supported since most storage technologies use the simple Reserve, which doesn't offer hourly accounting. However, upon switching to the normal Reserve you will be able to:

```
- query = V(some_node_key, storage_curve)
- unit = curve
```

**Comment by marliekeverweij** [comment]
> However, upon switching to the normal Reserve you will be able to:

Great! Will you do that or should @mabijkerk do that?

**Comment by antw** [comment]
> Will you do that or should @mabijkerk do that?

It's a code change, so I'll take care of it.

**Comment by antw** [comment]
> `V(some_node_key, storage_curve)`

This is now supported [with ETEngine's **tracked-storage** branch](https://github.com/quintel/etengine/compare/tracked-storage).

I was able to add the necessary feature to SimpleReserve at a 30% performance penalty; however it's still roughly twice as fast as the alternative.

### Before

```
!> SimpleReserve without decay  735.983  (± 3.0%) i/s  -  3.723k in 5.063201s
!> SimpleReserve with decay     658.549  (± 2.7%) i/s  -  3.315k in 5.037541s
   Reserve without decay        306.401  (± 4.9%) i/s  -  1.550k in 5.071139s
   Reserve with decay           234.178  (± 4.7%) i/s  -  1.175k in 5.028262s
```

### After

```
!> SimpleReserve without decay  559.834  (± 4.8%) i/s  -  2.800k in 5.014238s
!> SimpleReserve with decay     568.790  (± 3.0%) i/s  -  2.856k in 5.026015s
   Reserve without decay        307.716  (± 3.9%) i/s  -  1.560k in 5.077913s
   Reserve with decay           241.613  (± 3.3%) i/s  -  1.219k in 5.050759s
```
