### ISSUE TITLE
Missing queries for "Heat and electricity sources in agriculture" chart

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etsource#2443]
When I try to open the chart "Heat and electricity sources in agriculture" in ETM-pro, the model freezes and I get the following error:

<img width="583" alt="Screenshot 2021-04-16 at 13 52 29" src="https://user-images.githubusercontent.com/67338510/115020517-fd8e5000-9eba-11eb-8110-21dbc9e2cde1.png">

When I try to open the chart in ETM-beta it actually shows me the nature of the error from ETEngine as well. It states that for both the present and the future the following two queries are missing:

- `chp_electricity_in_source_of_heat_and_electricity_in_agriculture`
- `chp_heat_in_source_of_heat_and_electricity_in_agriculture`

These queries are used in the following two queries:

- `centrally_produced_electricity_in_source_of_heat_and_electricity_in_agriculture `
- `centrally_produced_heat_in_source_of_heat_and_electricity_in_agriculture`

 My proposed solution is to see if these queries have been deleted accidentally in the past and write new queries if I cannot find them.

**Comment by mabijkerk** [comment]
The missing queries were deleted as part of commit 3c52f35e63daf5f8110f18c69b72b62f45044515. @michieldenhaan did you delete the queries (`chp_electricity_in_source_of_heat_and_electricity_in_agriculture` and `chp_heat_in_source_of_heat_and_electricity_in_agriculture`, see issue description above) because they were incorrect or because you thought they were redundant?

If you though they were redundant then we can simply restore the queries to fix the chart.

**Comment by mabijkerk** [comment]
It seems as though the chp nodes that the queries refer to do not exist anymore. These nodes are:

- `agriculture_chp_engine_network_gas`
- `agriculture_chp_engine_biogas`
- `agriculture_chp_supercritical_wood_pellets`

Updated proposed solution is to rewrite the queries currently still used in the graph.

**Comment by michieldenhaan** [comment]
Yes I'm in favour of deleting this chart (rather than setting to hidden). In the past, agriculture had it's own dedicated CHPs. The chart showed how much electricity/heat was produced locally and how much was drawn from the grid. With the 2020 heat network update, the distinction between sector specific and central CHPs no longer applies to agriculture, so the chart does not provide much value.
