### ISSUE TITLE
Regions without "*_net_capacity_per_step" cause division by zero

### ISSUE THREAD

**Issue by antw** [quintel/etsource#2454]
Reported in the past few days by a user, it was noticed that the "Breakdown of total costs per household" chart would not work in a Germany scenario. I've tracked this down to electricity network queries which divide the capacity needed by the area "*_capacity_per_step" attributes.

Many of these attributes [are set to zero](https://github.com/quintel/etsource/blob/09cef7699d2b586f5962cb0e7bcae716f94990a2/datasets/de/de.full.ad#L121-L140) in the German dataset, which causes a division-by-zero. This results in Infinity, which cannot be serialized as JSON, and thus the chart cannot load. This happens in a default German scenario (with no sliders set).

For example, see the [lv_net_capacity_steps_built](https://engine.energytransitionmodel.com/inspect/832817/gqueries/lv_net_capacity_steps_built) query. The originating query for the cost chart is [network_in_breakdown_of_total_costs_per_household](https://engine.energytransitionmodel.com/inspect/832817/gqueries/network_in_breakdown_of_total_costs_per_household).

### Solution one: `IF`

I expect these queries should be wrapped in an `IF`:

```ruby
IF(
  AREA(use_network_calculations),
  -> {
    # original query
  },
  -> { 0.0 }
)
```

These datasets would be affected; their costs would be zero even if the dataset has attributes defined:

* br
* de
* es
* eu
* example
* fr
* pl
* uk
* UKNI01_northern_ireland

I'm not too familiar with the network calculation queries, but I'm not convinced this is desirable.

Another alternative is to check in the LV/MV/HV queries for zeroes. For example:

```diff
# gqueries/modules/network_calculation/lv_net/capacity/lv_net_capacity_steps_built.gql
- IF(
-   QUERY_FUTURE(lv_net_extra_capacity_needed) > 0.0,
-   CEIL(QUERY_FUTURE(lv_net_extra_capacity_needed) / AREA(lv_net_capacity_per_step)),
-   0.0
- )
+ IF(
+   QUERY_FUTURE(lv_net_extra_capacity_needed) > 0.0 && AREA(lv_net_capacity_per_step) > 0.0,
+   -> { CEIL(QUERY_FUTURE(lv_net_extra_capacity_needed) / AREA(lv_net_capacity_per_step)) },
+   -> { 0.0 }
+ )
```

### Solution two: Add data for DE

Data was present for these attributes in the German dataset until https://github.com/quintel/etsource/commit/80ceb595d915868c24e40da7d032b29ec7bbbec1 (8 months ago) when they were set to zero.

Other country datasets seem to use the same values as the Netherlands. Could this also be the case for Germany?

---

@michieldenhaan @redekok Do you have a better idea or a preference?

**Comment by michieldenhaan** [comment]
I see that on ETDataset all data is zero for DE (not just step size but also cost). So importing to ETSource with `rake import:dataset` results in the current numbers. I guess that's why `use_network_calculations` is set to false for DE.

For the corresponding 'Breakdown of total cost' chart we set the network [series](https://github.com/quintel/etmodel/blob/d6619effdfdd3468665909a947793b4e24401303/config/interface/output_element_series/breakdown_of_total_costs.yml#L59) to be dependent on 'use_network_calculations'. For the 'Breakdown of total cost chart per household' we don't. So maybe doing so as well would be the easiest fix?

**Comment by antw** [comment]
> For the corresponding 'Breakdown of total cost' chart we set the network series to be dependent on 'use_network_calculations'. For the 'Breakdown of total cost chart per household' we don't. So maybe doing so as well would be the easiest fix?

Good call; this does indeed fix the problem. I'd like to send this to production; would you prefer to test a PR first?

**Comment by michieldenhaan** [comment]
👍 I think it's good to go!
