### ISSUE TITLE
include_unattached=true parameter for custom curves not working

### ISSUE THREAD

**Issue by robcalon** [quintel/etsource#2456]
The parameter only seems to return custom_curves that are attached and not the custom_curves that are unattached, see 
e.g. https://engine.energytransitionmodel.com/api/v3//scenarios/833606/custom_curves?include_unattached=true

**Comment by marliekeverweij** [comment]
Thanks for updating us about this, Rob!

@antw could you have a look at this issue?

**Comment by antw** [comment]
This has been fixed on both beta and production servers. The parameter was actually called `show_unattached` and wrongly documented as `include_attached`.

**However** I've changed it to use `include_attached` as this is more consistent with our other API endpoints.

@robcalon The link you posted [should now work as expected](https://hoppscotch.io/?method=GET&url=https://engine.energytransitionmodel.com&path=/api/v3/scenarios/833606/custom_curves&params=%5B%7B%22key%22:%22include_unattached%22,%22value%22:%22true%22,%22active%22:true%7D%5D).
