### ISSUE TITLE
We should update the curves used in the NL2018 dataset

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2466]
When opening the [nl2018/curves-folder](https://github.com/quintel/etsource/tree/master/datasets/nl2018/curves) I see that almost all curves are linked to the `nl`-dataset. Only industry_ict and industry_other_electricity are not linked.

I would expect that more curves would be customized for `nl2018`, especially the production curves in [nl2018/curves/weather/default](https://github.com/quintel/etsource/tree/master/datasets/nl2018/curves/weather/default)

My question is: weren't more curves customized for `nl2018`?

I am not sure who created the curves for nl2018. I assigned @redekok @DorinevanderVlies, because I think you know most about curves :)

**Comment by DorinevanderVlies** [comment]
> My question is: weren't more curves customized for nl2018?

No, the curves project was early 2019. As fas as I remember hardly any data was available for 2018 at that time and 2018 datasets were not yet relevant.

We only made some curves for 2016 and 2017.

I think it will be fairly easy to make curves for 2018 in the same way as they were made for 2016 and 2017. Rough estimate 1-2 days for the whole set.

**Comment by marliekeverweij** [comment]
Okay thanks, good to know!

@redekok will add the curves to the new `nl2019`-dataset in the coming weeks. We could choose to also update the `nl2018`-curves during that effort. I think it's important as more and more ETM datasets are using the 2018 curves. What do you think? @redekok @AlexanderWirtz @michieldenhaan and more people an opinion about this :)

**Comment by redekok** [comment]
Yes that's exactly what I was about to suggest. I guess adding both the 2018 and 2019 curves will cost approximately the same amount of effort as adding solely the 2019 curves. Since most local datasets indeed rely on the 2018 dataset this seems like a valuable thing to do!

**Comment by redekok** [comment]
Closing, the curves for 2018 and 2019 will be updated along with the NL2019 dataset update.
