### ISSUE TITLE
Should transport train efficiency slider also affect hydrogen trains

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etsource#2539]
The [input slider](https://github.com/quintel/etsource/blob/master/inputs/demand/transport/transport_efficiency/transport_trains_efficiency.ad) that sets the future efficiency of trains does not seem to include an update statement voor the recently added nodes `transport_freight_train_using_hydrogen` and `transport_passenger_train_using_hydrogen`:

> - query =
    EACH(
    UPDATE(OUTPUT_SLOTS(V(transport_passenger_train_using_diesel_mix,transport_passenger_train_using_electricity,transport_passenger_train_using_coal),passenger_kms), conversion, USER_INPUT()),
    UPDATE(OUTPUT_SLOTS(V(transport_freight_train_using_diesel_mix,transport_freight_train_using_electricity),freight_tonne_kms), conversion, USER_INPUT())
    )
    
@redekok do you agree that hydrogen trains should be added to this input slider?

**Comment by redekok** [comment]
I agree @mabijkerk, well spotted! @lottevanvlimmeren would you have time to pick this up?
