### ISSUE TITLE
EU countries have a high share of heat pump in the housing sector, is that true?

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etsource#2583]
Many countries that I have checked have a remarkable number of heat pumps compared to electric heating. 

For example Germany 7.8% heat pump air and 4.8% heat pump ground, 1.9% heat electric heater.

Are these values based on literature? It seems too high to me.

**Comment by Charlottevm** [comment]
This is indeed based on literature but also surprised us. We will look for better sources in the future.
