### ISSUE TITLE
Add CCUS to chemical and refinery sector

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2604]
At the moment it is not possible to capture CO2 from the chemical and refinery sector, as you can see [here](https://pro.energytransitionmodel.com/scenario/emissions/ccus/capture-of-co2):

![Screenshot 2022-01-25 at 15 07 10](https://user-images.githubusercontent.com/32833996/150991922-fba95e43-ea91-4cf3-838a-42f2163a0bdd.png)
 
For coupling the CTM to the ETM it is necessary to be able to communicate the captured CO2 of these sectors to the ETM. Otherwise, corrections have to be made in the final demands per sectors, which is less desirable.

Todos here:

- [x] add nodes to the energy and molecules graph
- [x] add sliders to the front-end
- [x] check fall-out in charts
- [ ] check if the same capture potential of 85% can be used that is now assumed for paper, food, fertilizers

@AlexanderWirtz I am interested to know opinion on this improvement. Do you know what the reason was why we didn't implement it during the CCUS project? Is the capture potential relatively low?

**Comment by AlexanderWirtz** [comment]
I don't really know, other than that we don't distinguish very well between CO2 from heat generation (relatively low concentration and so harder to capture) and any other flows. We really know so little about that goes on in these sectprs that we concluded they had to be modeled differently before adding CO2. Perhaps you can ask Michiel if he remembers anything more specific. I am sure he doesn't mind.

**Comment by AlexanderWirtz** [comment]
As far as the capture _rate_  is concerned, I believe that is fairly standard for combustion / flue gases. Any streams of CO2 that are more concentrated have a higher capture potential. I don't understand why we can't ask Kalavasta what they used for the chemical plants and refineries. Or at least why we can't see if they use a range of capture rates. Capture _potential_ we would need to somehow derive from the rates and various kinds of processes found in chemical industry.

We would need to ake clear that this is kind of a temporary addition that we might want to make more sophisticated once we model these sectors better. Not relevant to Kalavasta, but may to NBNL
