### ISSUE TITLE
Flexibility - add hybrid heating to fertilizer industry

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2625]
We want to add hybrid heaters to the fertilizer industry aswell, just like for refineries in the screenshot below:

![Screenshot 2022-02-08 at 16 35 34](https://user-images.githubusercontent.com/32833996/153020798-b5bafdfa-115a-4de4-b640-f7629cad06c4.png)
![Screenshot 2022-02-08 at 16 36 36](https://user-images.githubusercontent.com/32833996/153021010-421aef01-ef1d-465c-9716-951ed05588d8.png)

Todos:

- [x] Add nodes to graph
- [x] Add capacity slider to front-end
- [x] Add NSA to ETDataset
- [x] Check fall-out charts

**Comment by mabijkerk** [comment]
- [ ] Add WTP slider to front-end
- [ ] Add industry_fertilizers_heat demand profile
