### ISSUE TITLE
Missing merit order subtype for two flex nodes

### ISSUE THREAD

**Issue by lottevanvlimmeren** [quintel/etsource#2645]
Two power-to-heat nodes do not have a merit order subtype defined: `energy_heat_flexibility_p2h_heatpump_electricity` and `energy_heat_flexibility_p2h_boiler_electricity`. Tagging @mabijkerk due to your involvement in the flex update; do you know anything about this?

<img width="748" alt="image" src="https://user-images.githubusercontent.com/89903998/157685725-f0a6bebb-ad99-436f-ab56-dd51e2408fe7.png">

**Comment by mabijkerk** [comment]
I don't know why it doesn't have a subtype. They seem to have been functioning without any subtypes since they have been added to the model. They have been added by @marliekeverweij I think, so perhaps she knows more about this?

**Comment by mabijkerk** [comment]
@marliekeverweij could you take a look at this issue?

**Comment by marliekeverweij** [comment]
I have added the group `generic` as most of the demand technologies have this group. Is this correct @antw ?

**Comment by antw** [comment]
TIL we don't validate `subtype` when `type` is set to "flex". 🤔 

I've opened an issue on Atlas.
