### ISSUE TITLE
Adjust max_value for external_coupling inputs

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2647]
Our client expressed the wish (in his email on 9 March) to increase the max_value for the following inputs. The reason for this is that the value in the start year can be quite small and therefore this demand has to be increased with a high factor. He proposed 10ˆ5 or 10ˆ6. @mabijkerk could you check if this works in the ETM and that we do not run in any issues for nl2019?

external_coupling_industry_chemical_other_useable_heat
external_coupling_industry_chemical_other_total_non_energetic
external_coupling_industry_chemical_other_electricity
external_coupling_industry_metal_steel_total_demand
external_coupling_industry_chemical_fertilizers_total_excluding_electricity
external_coupling_industry_chemical_fertilizers_electricity
external_coupling_industry_chemical_refineries_useable_heat
external_coupling_industry_chemical_refineries_total_non_energetic
external_coupling_industry_chemical_refineries_electricity

**Comment by mabijkerk** [comment]
The upper limit for input statement values in ETEngine seems to be at 99900%, see the screenshot below for input statement set at 100000%. The max values are updated according to this upper limit.

<img width="646" alt="Screenshot 2022-03-16 at 09 45 16" src="https://user-images.githubusercontent.com/67338510/158551104-468e37a0-fe25-4d4f-9800-ec1d13f2b048.png">
