### ISSUE TITLE
Gas network costs of ETLocal datasets are unrealistic small 

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2662]
In [this pull request ](https://github.com/quintel/etsource/pull/2661)we have updated all ETSource datasets with the current data on ETLocal 🎉

During this update the gas network costs of all datasets decreased with a factor 1.000.000. This has to be updated before next deploy!

https://github.com/quintel/etsource/pull/2661/files#diff-45886ffb82aaecb57fb53239c521dd307f1e4f4bd8bbec0012cf325e0a684ee7L137-R137

**Comment by marliekeverweij** [comment]
I haven't had the time to look into this issue earlier. The reason that this issue pops up is that we haven't set a value in ETLocal and when there is no value, ETLocal automatically takes the value in the area-file for the ETLocal key `annual_infrastructure_cost_gas` and uses the SGQ `area+annual_infrastructure_cost_gas.ad` which divides it by one million. That's why this area-attribute decreases with a factor 1.000.000 every time we export a dataset.

How can we solve this? We should set a value for each dataset on ETLocal.

@antw / @noracato do you agree with this? Would you have time before the deploy to write a dataset migration for all ETLocal dataset, which scales the Dutch gas network costs with the total final demand gas? The Dutch value is 1,452,000,000 euro and can be found here https://github.com/quintel/etsource/blob/master/datasets/nl2019/nl2019.full.ad#L145

I could provide a list of the total final demand gas per dataset on Monday

**Comment by antw** [comment]
> Would you have time before the deploy to write a dataset migration for all ETLocal dataset

Are you sure that it's right to set a value for each dataset? Would it not be preferred to scale the value from the NL dataset each time, so that if NL were ever updated the regional datasets would automatically reflect this change?

Why does the SQL divide by one million?

**Comment by marliekeverweij** [comment]
Thank for your response @antw, interesting questions

IMO we want to move to the direction that all data is set through the Dataset Manager. Then the Dataset Manager will give a complete overview of the data (very transparent) and no non-transparant scaling (and undesired?) takes place. The datasets will not be "derived" anymore, but stand-alone. We are not there yet and I would like to investigate what we need to do to get there. 

In the past entso-project we have added the key for gas network costs to the Dataset Manager. This way users can see the assumption that has been made for their datasets. For gas network costs they can see that this is not a well researched value, but an estimation based on the Dutch network costs.

> Are you sure that it's right to set a value for each dataset? Would it not be preferred to scale the value from the NL dataset each time, so that if NL were ever updated the regional datasets would automatically reflect this change?

The value for NL has not changed in the past 5 years and I do not expect it to change often. So yes.

> Why does the SQL divide by one million? Neither the SQL file nor the commit which added it provide an explanation for this magic number.

The value in the area is in millions and that is because of [this gquery.](https://github.com/quintel/etsource/blob/master/gqueries/modules/network_calculation/gas_network/gas_network_total_costs.gql) I think we should remove this! In both the query and the SQL! Then the value in the are file will be in euros :)

**Comment by antw** [comment]
> The value in the area is in millions and that is because of [this gquery.](https://github.com/quintel/etsource/blob/master/gqueries/modules/network_calculation/gas_network/gas_network_total_costs.gql?rgh-link-date=2022-04-04T08%3A23%3A30Z)

I see. So the problem is that we have datasets that fall into two categories:

1. Datasets that define a custom value for `annual_infrastructure_cost_gas`. **The value is specified in euros.**
2. Datasets that *do not* define a custom value and instead currently inherit it from the parent dataset. **The parent value is specified in millions of euros.**

The problem is that the SGQ divides the value by 1M, which is correct for datasets in the first category, but not for those in the second.

> This has to be updated before next deploy! [..] I could provide a list of the total final demand gas per dataset on Monday

I'm happy to take a look at this, but as there are several things now competing for "before the deploy" promises can't be made. Worst case it can be done tomorrow afternoon and sent to production shortly after the deploy.

If you have a list of the datasets and values, can this be done [with a dataset migration](https://docs.energytransitionmodel.com/contrib/dataset-manager/data-migrations)?
