### ISSUE TITLE
Should hydrogen import be counted as renewable when carbon content is 0 kg/MWh

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etsource#2709]
When I open a new scenario, create hydrogen demand and the allow that demand to be met with import I get [this scenario](https://pro.energytransitionmodel.com/saved_scenarios/12635). The standard carbon content of imported hydrogen is **281 kg/MWh**. The chart `Renewability of final demand` shows that the resulting renewability of final demand is 7.93% with 0.0% renewable hydrogen:

<img width="622" alt="Screenshot 2022-07-13 at 10 15 41" src="https://user-images.githubusercontent.com/67338510/178685157-d8e1d838-70db-48a3-9ffc-ba49c7f54c2d.png">

When I then set the carbon content of imported hydrogen at **0 kg/MWh,** these values do not change (see [this scenario](https://pro.energytransitionmodel.com/saved_scenarios/12636)):

<img width="621" alt="Screenshot 2022-07-13 at 10 17 42" src="https://user-images.githubusercontent.com/67338510/178685515-920d3be1-b022-43c7-9012-e4886ac20afd.png">

I would expect that imported hydrogen with 0 kg/MWh carbon content counts as 'renewable hydrogen', but instead it's still registered as 'fossil hydrogen'.

@marliekeverweij @AlexanderWirtz what do you think: should zero carbon hydrogen imports be registered as renewable hydrogen?

**Comment by AlexanderWirtz** [comment]
@mabijkerk my 2 cts:
No, I don't there is a difference between renewable and zero emissions. Renewable to me means the energy source in inexhaustible or can at least in theory be replenished quickly (like biomass). But there is actually a European definition. I don't think that relates renewable to emissions, but I am not sure. :-)
