### ISSUE TITLE
Hydrogen output curve should sum to total demand

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etsource#2731]
When I open a blank scenario for `nl2019` and set the car technology to 100% hydrogen, I get [this scenario](https://pro.energytransitionmodel.com/saved_scenarios/12708). All the hydrogen is imported through the backup node, since I have not added any supply. The backup node has a demand of 128.77 PJ and no losses:

![Screenshot 2022-08-11 at 15 29 26](https://user-images.githubusercontent.com/67338510/184144606-2184f182-8140-4108-a3e8-19b130bd7c92.png)

When I then sum the hydrogen output curve and convert it to MJ, I would expect it to equal the output of hydrogen: 128.77 PJ. However, as becomes clear below this is not the case. Am I missing something @antw or is something going wrong here?
 
Query:
```ruby
EACH(
  SUM(V(energy_imported_hydrogen_backup,hydrogen_output_curve))*MJ_PER_MWH,
  V(energy_imported_hydrogen_backup,output_of_hydrogen)
 )
```
Result:
```ruby
[
  127,488,862,267.91734,
  128,773,409,219.03215,
]
```

**Comment by mabijkerk** [comment]
It does not seem to occur for baseload hydrogen import:
```ruby
EACH(
  SUM(V(energy_imported_hydrogen_baseload,hydrogen_output_curve))*MJ_PER_MWH,
  V(energy_imported_hydrogen_baseload,output_of_hydrogen)
 )
```
```ruby
[
  157,680,000,000.00272,
  157,680,000,000.0,
]
```

**Comment by antw** [comment]
I think the problem is caused by the `energy_transport_hydrogen_pipelines` node, which has 1% loss. The hourly hydrogen calculation has no way of knowing about this loss; it knows only about the total amount of hydrogen demanded (by `transport_final_demand_hydrogen `) and imports to meet that demand.

This is why the curve and demand (output of hydrogen) don't match: the curve does not include the loss from pipelines, the demand/output does.

I don't think there's an easy fix for this, I'm afraid. We either need to find a way to include en route losses in the hourly hydrogen calculation, or remove the loss.

**Comment by mabijkerk** [comment]
Thanks for the explanation. So the HV electricity network, the central heating network and the gas network all have loss nodes, which are explicit consumers:

![Screenshot 2022-08-11 at 16 04 38](https://user-images.githubusercontent.com/67338510/184151947-04f1830d-5312-480a-bc70-7d77712d329a.png)![Screenshot 2022-08-11 at 16 06 12](https://user-images.githubusercontent.com/67338510/184152279-4cb7879f-bae5-454b-8d6d-71bd2f344369.png)

I imagine we would have to add a similar node to the central hydrogen network to account for hourly losses. Do you think that this would work @antw?

**Comment by antw** [comment]
Good idea. A loss node would do the trick nicely; we could add that as an H2 consumer.

**Comment by mabijkerk** [comment]
@marliekeverweij do you agree with the solution of implementing a distribution loss node for the central hydrogen network?

**Comment by mabijkerk** [comment]
I notice that the loss nodes all have some kind of subtype to indicate that there's a loss:

```
- heat_network.subtype = consumption_loss
- network_gas.demand_carrier = loss
- merit_order.subtype = electricity_loss
```

Is that something that should be added as well for the hydrogen distribution loss node @antw? If so, could you add that to the relevant `hydrogen` branch? I'll add the nodes, edges and relevant chart curves to ETSource and ETModel.

**Comment by marliekeverweij** [comment]
Thanks for spotting this issue @mabijkerk !

> @marliekeverweij do you agree with the solution of implementing a distribution loss node for the central hydrogen network?

Yes, good solution!

**Comment by mabijkerk** [comment]
I've added an `energy_transport_hydrogen_loss` node and added the attribute `hydrogen.demand_carrier = loss`. This seems to work as the query now gives:

```ruby
EACH(
  SUM(V(energy_imported_hydrogen_backup,hydrogen_output_curve))*MJ_PER_MWH,
  V(energy_imported_hydrogen_backup,output_of_hydrogen)
 )

[
  128,773,409,219.03433,
  128,773,409,219.03215,
]
```

**Comment by mabijkerk** [comment]
Solved on the hydrogen branches on ETModel en ETSource.
