### ISSUE TITLE
Request to increase maximum WTP/WTA of electricity storage

### ISSUE THREAD

**Issue by antw** [quintel/etsource#2732]
I've had a request from an ETM user to increase the maximum allowed value for the WTP/WTA sliders for electric vehicles to 300 EUR. I doubt there would be any side effects, but I'm unsure if the current maximum of 100 EUR was chosen for a particular reason.

Does it sound reasonable to increase these values? If so, should we do it for all storage options?

@mabijkerk I assigned you since you originally added these values, but feel free to reassign as you see fit.

**Comment by MaykThewessen** [comment]
would be great, reasoning behind is that LCOE cost of V2G storage per kWh cycle throughput has a cost ranging from €20-380/MWh depending of cycle life and chemistry

these degradation costs need to be covered by the difference between WTP and WTA; thus WTA = WTP + 20 ie.e.

**Comment by mabijkerk** [comment]
At the time 100 euro/MWh was chosen because it seemed like a reasonable maximum value. There is no reason why it shouldn't be higher, so I've raised the maximum for all the WTP and WTA sliders to 300 euro/MWh. It is now available on beta.
