### ISSUE TITLE
Must-run profile assignment needs to be validated

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#277]
Currently we use these profiles:

```
  agriculture_chp_engine_biogas: industry_chp
  agriculture_chp_engine_network_gas: agriculture_chp
  agriculture_chp_supercritical_wood_pellets: agriculture_chp
  buildings_collective_chp_network_gas: buildings_chp
  buildings_collective_chp_wood_pellets: buildings_chp
  energy_chp_supercritical_waste_mix: industry_chp
  energy_power_supercritical_waste_mix: industry_chp
  households_collective_chp_biogas: industry_chp
  households_collective_chp_network_gas: buildings_chp
  households_collective_chp_wood_pellets: buildings_chp
  households_space_heater_micro_chp_network_gas: buildings_chp
  households_water_heater_fuel_cell_chp_network_gas: buildings_chp
  households_water_heater_micro_chp_network_gas: buildings_chp
  industry_chp_combined_cycle_gas_power_fuelmix: industry_chp
  industry_chp_engine_gas_power_fuelmix: industry_chp
  industry_chp_turbine_gas_power_fuelmix: industry_chp
  industry_chp_ultra_supercritical_coal: industry_chp
  other_chp_engine_biogas: industry_chp
  other_chp_engine_network_gas: buildings_chp
```

NOTE that all biogas CHPs use the (flat) industry_chp profile because it best represents their behavior. Also see https://github.com/quintel/etsource/issues/272

**Comment by TessColijn** [comment]
An update on the current CHPs with merit_order.type = must_run and the profiles that are used:

Must-run CHP | Profile
------------ | -------------
buildings_collective_chp_network_gas | buildings_chp
buildings_collective_chp_wood_pellets	| buildings_chp
buildings_chp_engine_biogas | industry_chp
households_water_heater_micro_chp_network_gas |	buildings_chp
households_collective_chp_biogas |	industry_chp
households_water_heater_fuel_cell_chp_network_gas | buildings_chp
households_collective_chp_network_gas | buildings_chp
households_space_heater_micro_chp_network_gas | buildings_chp
households_collective_chp_wood_pellets | buildings_chp
industry_chp_combined_cycle_gas_power_fuelmix | industry_chp
industry_chp_engine_gas_power_fuelmix | industry_chp
industry_chp_turbine_gas_power_fuelmix | industry_chp
industry_chp_ultra_supercritical_coal | industry_chp
energy_chp_supercritical_waste_mix | industry_chp
energy_power_supercritical_waste_mix | industry_chp
agriculture_chp_engine_biogas | industry_chp
agriculture_chp_supercritical_wood_pellets | agriculture_chp
agriculture_chp_engine_network_gas | agriculture_chp

**Comment by michieldenhaan** [comment]
Closing, CHPs are now dispatchable in the Merit Order and no longer use fixed profiles. Exception is biogas CHP, which still uses a flat curve
