### ISSUE TITLE
FLH for offshore wind turbines for dedicated H2 production are 4000 for all countries

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etsource#2778]
I noticed that in a blanc scenario the full load hours for offshore wind turbines differ from the offshore wind turbines for dedicated H2 production, see screenshot below for `nl2019`.

![Screenshot 2022-10-19 at 13 17 33](https://user-images.githubusercontent.com/32833996/196684512-9da4f511-d965-4b24-80b5-8959f482db13.png)

I was wondering why this is. I have the feeling these should be the same wind turbines. @antw will investigate this, but if anybody has a clue, let us know! @quintel/core

**Comment by antw** [comment]
I misunderstood your question on Slack and thought this was a bug in ETEngine. This does not appear to be the case.

The values you see in ETModel match those read from the central_producers.csv file in ETSource:

| key | demand | full_load_hours | electricity_output_conversion | steam_hot_water_output_conversion |
| --- | --- | --- | --- | --- |
| [energy_hydrogen_wind_turbine_offshore](https://github.com/quintel/etsource/blob/7441f116efdd3522c111c132b3e6a2db7f069299/datasets/nl2019/central_producers.csv#L18) | 0.00000000000000E+00 | 4.00000000000000E+03 | | |
| [energy_power_wind_turbine_offshore](https://github.com/quintel/etsource/blob/7441f116efdd3522c111c132b3e6a2db7f069299/datasets/nl2019/central_producers.csv#L52) | 1.32605396474936E+04 | 3.73354231974922E+03 | | |

**Comment by marliekeverweij** [comment]
Allright, then I have the feeling this is a bug in the ETDataset procedure (and maybe also the ETM Dataset Manager): I see that all newly built dedicated H2 wind turbines have 4000 flh. For the Dutch datasets setting these flh to 4000 might be realistic, but not for all countries.

What do you think? @DorinevanderVlies @mabijkerk @AlexanderWirtz @ChaelKruip 

I think we should pick this up and investigate this further before the deploy

**Comment by AlexanderWirtz** [comment]
Well the H2 producing ones will not be built for a while and when they do 4000 seems fine if a bit low for NL/ NorthSea.
The FLH for normal offshore is a result of the installed cap and energy production so an average across all parks etc. 

So they don’t need to be the same. That leaves the question what to set them to in other countries. For now, I have no indication that 4000 is wrong, but ideally we would base this on an international source. Perhaps Michiel den Haan knows of one that NSWPH uses?

**Comment by marliekeverweij** [comment]
Okay, sounds good, I removed the "Bugs" label! Users can always adjust the flh with the sliders, so I would propose to close this issue now. You can reopen if you feel like we have to change the flh for other countries.
