### ISSUE TITLE
The nl2019 dataset refers to old (2015) electricity and heat demand curves for the other industry sectors

### ISSUE THREAD

**Issue by redekok** [quintel/etsource#2841]
One of our clients pointed out that our electricity demand curves for other industry seem to start on a different weekday (a Thursday) compared to our other demand curves (which start on a Tuesday). After looking in to this, I found out that the `nl2019` dataset refers to old curves from the 2015 dataset: [`industry_other_electricity.csv`](https://github.com/quintel/etsource/blob/master/datasets/nl2019/curves/industry_other_electricity.csv) and [`industry_other_heat.csv`](https://github.com/quintel/etsource/blob/master/datasets/nl2019/curves/industry_other_heat.csv). I noticed that there is [only one curve available for 2019](https://github.com/quintel/etdataset/blob/master/curves/demand/industry/other/data/nl/2019/output/industry_other.csv) in our [etdataset repository](https://github.com/quintel/etdataset/tree/master/curves/demand/industry/other). This curve represents the heat demand. No curve is available for the electricity demand. This is probably due to the fact that our data source ([NEDU](https://www.nedu.nl/cgi-sys/suspendedpage.cgi)) isn't available anymore. The 2019 [`industry_other.csv`](https://github.com/quintel/etsource/blob/master/datasets/nl2019/curves/industry_other.csv) curve has been exported to our nl2019 dataset on ETSource but isn't actually used at the moment.

[MFFBAS](https://www.mffbas.nl/documenten/) also offers the NEDU demand curves. However, they only offer curves starting from 2020. Curves from 2019 doesn't seem to be (publicly) available. In addition, I read [something](https://www.acm.nl/sites/default/files/documents/2019-06/ontwerp-codebesluit-uitfaseren-profielsegment-e3.pdf) about phasing out the E3A, E3B, E3C, and E3D curves and aggregating those to an overarching E3 curve. For the last couple of years MFFBAS still seems to offer the more detailed E3A-D curves so this might not be a very urgent issue we have to deal with. 

@mabijkerk and I have shortly discussed a few solutions for this issue:

1. For lack of 2019 curves, use the 2015 curves and shift those a few days to ensure they start on a Tuesday instead of a Thursday. 
2. Check with MFFBAS whether it's possible to get the NEDU 2019 curves. If not, we could also check this with other parties such as the system operators.
3. Use the 2019 heat demand curve (which is derived from the gas balance) for both electricity and heat demand.

Personally, I don't prefer option 3 since it would make sense to distinguish (not heat related) electricity demand and heat demand of the other industry sectors. Besides that, the NEDU E3D (or `industry_other_electricity.csv`) curve is also used for the ICT sector and IMO it wouldn't make sense to use a heat demand curve here. Also see https://github.com/quintel/etsource/issues/2295.

Therefore, I would prefer to first check out option 2 and have option 1 as a back-up plan if option 2 doesn't work out.

Notifying @ChaelKruip and @DorinevanderVlies: also curious to hear your opinion on this issue!

**Comment by mabijkerk** [comment]
To help make your choice: below I have visualised the first ~1000 hours of the nl2019 curve and the nl2015 curves.

<img width="710" alt="image" src="https://user-images.githubusercontent.com/67338510/215988840-d8be0a15-a2f1-46ba-866a-1aae0d95112b.png">

**Comment by mabijkerk** [comment]
Another solution:

4. Use the 2019 [`industry_other.csv`](https://github.com/quintel/etsource/blob/master/datasets/nl2019/curves/industry_other.csv) curve for 2019 heat demand, and use the shifted 2015 [`industry_other_electricity.csv`](https://github.com/quintel/etsource/blob/master/datasets/nl2019/curves/industry_other_electricity.csv) for 2019 electricity demand

**Comment by redekok** [comment]
I just e-mailed MFFBAS once again, let's hope they will respond soon. :)
