### ISSUE TITLE
Priority of capacity and efficiency inputs

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etsource#2850]
For example in [this](https://energytransitionmodel.com/scenarios/951055) scenario.

<img src="https://user-images.githubusercontent.com/67338510/219369229-63f1fc62-3cef-4695-a711-86afc75e378b.png" width="400">

<img src="https://user-images.githubusercontent.com/67338510/219369275-34d56056-4992-4f1b-8aa4-afb17ea2be0b.png" width="600">

Could be caused by https://github.com/quintel/etengine/pull/1312/commits/8d118d853a771eb3beba62c031f147538da8bfa7

**Comment by mabijkerk** [comment]
Potentially:

- Check queries in merit order table for overlap
- Check availability

**Comment by mabijkerk** [comment]
The issue does not occur for `energy_chp_local_engine_biogas` and `energy_chp_local_wood_pellets`. Therefore it might not be related to https://github.com/quintel/etengine/commit/8d118d853a771eb3beba62c031f147538da8bfa7 after all.

The installed capacity produced in the merit order table, 154.29 MW, is also visible in the node specifications on ETEngine and when querying any of the following:

```ruby
V(energy_chp_local_engine_network_gas, "electricity_output_capacity * number_of_units")

V(energy_chp_local_engine_network_gas, "typical_input_capacity * electricity_output_conversion * number_of_units"),

PRODUCT(
    DIVIDE(
      DIVIDE(V(energy_chp_local_engine_network_gas,demand),MJ_PER_MWH),
      V(energy_chp_local_engine_network_gas,full_load_hours)
    ),
    V(energy_chp_local_engine_network_gas,electricity_output_conversion)
)
```

The issue may therefore be caused by some type of miscommunication between ETEngine and ETModel. Perhaps this slider was not reset properly when the migration was performed. @noracato could you look into this at some point?

**Comment by mabijkerk** [comment]
This is caused by the efficiency and capacities inputs interfering. Both have the same priority of 0 and apparently somewhere while setting one of the inputs, the other value is changed, leading to a difference in what the input says and what the actual capacity is. By removing the efficiency inputs from the scenario, the difference is gone:

![Screenshot 2024-05-06 at 09 32 38](https://github.com/quintel/etsource/assets/67338510/d5c552e8-ae10-48c4-9cb0-e6ae50a04de4)

It also occurs in a blank scenario, with just the capacities and efficiencies set for this CHP: [https://energytransitionmodel.com/saved_scenarios/17127](https://energytransitionmodel.com/saved_scenarios/17127). This indicates a broader issue.

**Comment by kndehaan** [comment]
Issue is solved with this [PR](https://github.com/quintel/etsource/pull/3096) and can therefore be closed.
