### ISSUE TITLE
Add new queries

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etsource#2851]
As requested by ENTSO, the following selection of queries should be added to the model.

Agreed selection:
- [x] Number of units of heat pumps per type, sector and application
- [x] Electricity demand of heat pumps per type
- [x] Network gas demand of hybrid heat pumps per type, sector and application
- [x] Base COP of hybrid heat pumps per type, sector and application
- [x] COP per degree of hybrid heat pumps per type, sector and application
- [x] COP of heat pumps per type, sector and application
- [x] Number of units of air conditioning
- [x] Number of units of electric heaters
- [x] Number of electric vehicles per type
- [x] Passenger kms per transport technology type
- [x] Freight tonne kms per transport technology type
- [x] Vehicle efficiency per electric vehicle type

Process:
- [x] Vehicle efficiency per electric vehicle type: requested is vkm/MJ, not pkm/MJ and tkm/MJ)
- [ ] Number of units of heat pumps per type, sector and application: communicate clearly (see discussion below)
- [ ] COP of heat pumps is sometimes COP, sometimes SCOP: communicate clearly
- [x] Wrap-up with documentation of all queries

Questions:
- ~~Should water and space heaters be counted as a single unit?~~
- ~~Should cooling and heating be counted as a single unit?~~
- ~~What type of unit is `industry_chemicals_other_steam_recompression_electricity` (should it be added to list of heat pumps)~~
- ~~Can COP be queried from all heat pumps?~~

**Comment by mabijkerk** [comment]
We have been asked to write queries for the number of units of heat pumps. When I query all the heat pumps in the application group, I will for example get `households_space_heater_heatpump_air_water_electricity` and the `households_water_heater_heatpump_air_water_electricity`.

I would assume that they represent the same technology, and that `households_cooling_heatpump_air_water_electricity` should be counted as the same single technology as well. However, when I query the NoU, i get different results for each technology:

```ruby
EACH(
  V(households_space_heater_heatpump_air_water_electricity,number_of_units),
  V(households_water_heater_heatpump_air_water_electricity,number_of_units),
  V(households_cooling_heatpump_air_water_electricity,number_of_units)
)
```
```ruby
[
  189,434.8567100454,
  150,336.209112773,
  55,453.84958161603,
]
```

@redekok do you happen to know more about this topic? How should the NoU be interpreted?

**Comment by redekok** [comment]
I _think_ the NoU are derived from the (peak?) demand and the heat capacity per unit. Perhaps you could compare the ratio between the (peak) heat demand of both nodes to the ratio between the NoU to check if this is indeed the case?

**Comment by mabijkerk** [comment]
Thanks for this @redekok, I agree that this is how it functions technically. For me the issue is more conceptually: is communicating the number of units for each technology actually what ENTSO want to know?

From the discussion we just had I think it would be good to check with the client how they want to use these new queries. Then we can decide whether the number of units attribute serves their needs, or whether we should consider implementing a different kind of query:

- Number of residences equipped with a space and water heating technology (where space and water count as 1)
- Number of residences equipped with a cooling technology
- Number of buildings equipped with a space heating technology
- Number of buildings equipped with a cooling technology

**Comment by mabijkerk** [comment]
I just had short discussion with the client. We agreed that I will deliver the queries as is i.e., querying the `number_of_units` attribute. We then do need to clearly communicate how the `number_of_units` should be interpreted. This can be included in the Excel in which I track all the query requests.
