### ISSUE TITLE
District heating costs per household contain mistake in heat delivery system costs

### ISSUE THREAD

**Issue by KoenvanB** [quintel/etsource#2992]
The vertical_stacked_bar_ht_district_heating_costs_per_household figure (and mt and lt versions) contain the heat delivery system costs per household. These costs are calculated by taking the ht heat delivery system capital and depreciation costs (capex) and dividing those by the number of residences in the district heating network ([link](https://github.com/quintel/etsource/blob/2ec8296e803fe0258e7e0e148f3723f2211d3879/gqueries/output_elements/output_series/vertical_stacked_bar_ht_district_heating_costs_per_household/households_ht_heat_delivery_system_costs_per_household/households_ht_heat_delivery_system_capex_per_household.gql)):

```ruby
- unit = eur
- query =
    number_of_residences_in_ht_heating_network = V(households_space_heater_district_heating_ht_steam_hot_water,number_of_units);
    ht_heat_delivery_system_total_annual_costs = 
        SUM(
            Q(households_ht_heat_delivery_system_depreciation_costs),
            Q(households_ht_heat_delivery_system_capital_costs)
        );

    DIVIDE(
        ht_heat_delivery_system_total_annual_costs,
        number_of_residences_in_ht_heating_network
    )
```

However, the heat delivery system capex is based on ALL residences with that system, not just the residences that have district heating. As a result, the capex is too high, and therefore the costs per household as well.

This query should recalculate the capex for district heating households only to correct for this mistake.

**Comment by mabijkerk** [comment]
> However, the heat delivery system capex is based on ALL residences with that system, not just the residences that have district heating

I don't completely understand the difference. What do you mean with "that system".

**Comment by KoenvanB** [comment]
I mean that in this example capex is calculated based on all residences that have ht heat delivery systems, not just the residences that are in the district heating network.

I also realize this relates to an update to the heat delivery system costs that I have implemented on my branch only. So rather than writing an issue about it I should just go ahead and fix it on my branch first...

**Comment by mabijkerk** [comment]
> I mean that in this example capex is calculated based on all residences that have ht heat delivery systems, not just the residences that are in the district heating network.

Clear, good point!

**Comment by mabijkerk** [comment]
@KoenvanB what is the status of this issue?
