### ISSUE TITLE
Could the order be changed in charts of hourly heat suppy LT, MT, HT for visual purposes

### ISSUE THREAD

**Issue by MartLubben** [quintel/etsource#3001]
Visually it would be much stronger is heat supply has an altered order. The baseload technologies should be close to the x-axis. In the pictur below the heat from the storage should be on top. It makes is visually clear that this storage does the peak balancing.

<img width="479" alt="image" src="https://github.com/quintel/etsource/assets/33415156/9909eaa7-4e6f-4fc7-b1d2-781e99a6f1c6">

**Comment by mabijkerk** [comment]
Good suggestion @MartLubben. This issue is closed in https://github.com/quintel/etmodel/pull/4195
