### ISSUE TITLE
Ammonia reforming is missing from the installed capacity of flexible technologies chart

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etsource#3052]
I have created a scenario with 2 GW of flexible ammonia reforming. However, it does not show up in the installed capacity of flexible technologies chart:

![Installed capacity of flexible technologies 2566843](https://github.com/quintel/etsource/assets/67338510/bfe46607-c06a-492a-b50c-d78146aa5ab2)

@kaskranenburgQ is this something you can pick up?

**Comment by kaskranenburgQ** [comment]
I also see that when we put 2 GW of dispatchable ATR, the graph shows 2,66 GW is this supposed to happen?
<img width="834" alt="Screenshot 2024-05-15 at 18 27 06" src="https://github.com/quintel/etsource/assets/150331345/517efde4-0a86-4453-9250-c383a2e49aef">
