### ISSUE TITLE
Vanishing energy in network gas backup burner

### ISSUE THREAD

**Issue by kaskranenburgQ** [quintel/etsource#3053]
In this [scenario] (https://beta.energytransitionmodel.com/scenarios/2402130), the energy_heat_backup_burner_ht_network_gas shows the following energy input & output:
![Screenshot 2024-05-15 at 12 29 20](https://github.com/quintel/etsource/assets/150331345/9380b1e6-f6b0-411b-9b15-80cc1ad7b8f5)

Part of this imbalance can be attributed to the output efficiency of this node : 1.03. 

However, when this efficiency is set to 1.0, an imbalance remains: 
![Screenshot 2024-05-15 at 13 10 46](https://github.com/quintel/etsource/assets/150331345/944ef628-ddf7-4145-9c0f-7cee07c1860b)

This imbalance probably arises due to hourly calculations in the heat network. 
When I remove the hourly network heat attributes from the node, it is balanced:
![Screenshot 2024-05-15 at 13 14 51](https://github.com/quintel/etsource/assets/150331345/3e4e611a-25c1-4e65-85bd-24da43e4cac5)

This issue causes the sankey export queries to be slightly imbalanced.

**Comment by kaskranenburgQ** [comment]
I delved into this issue a bit further, it seems that this occurs due to the energy_heat_flexibility_p2h_boiler_electricity and the energy_heat_flexibility_p2h_heatpump_electricity nodes. 
With the following inputs, the error occurs on the node energy_heat_backup_burner_mt_network_gas:
`households_heater_coal_share: 0.0
households_heater_combined_hydrogen_share: 0.0
households_heater_combined_network_gas_share: 0.0
households_heater_crude_oil_share: 0.0
households_heater_electricity_share: 0.0
households_heater_heatpump_air_water_electricity_share: 0.0
households_heater_heatpump_ground_water_electricity_share: 0.0
households_heater_heatpump_pvt_electricity_share: 0.0
households_heater_hybrid_heatpump_air_water_electricity_share: 0.0
households_heater_hybrid_hydrogen_heatpump_air_water_electricity_share: 0.0
households_heater_network_gas_share: 0.0
households_heater_wood_pellets_share: 0.0
households_heater_district_heating_mt_steam_hot_water_share: 100.0
households_heater_district_heating_lt_steam_hot_water_share: 0.0
households_heater_heatpump_surface_water_water_ts_electricity_share: 0.0
share_of_energy_heat_flexibility_p2h_boiler_ht_electricity: 0.0
share_of_energy_heat_flexibility_p2h_boiler_mt_electricity: 100.0
share_of_energy_heat_flexibility_p2h_heatpump_ht_electricity: 0.0
share_of_energy_heat_flexibility_p2h_heatpump_mt_electricity: 100.0
wtp_of_energy_heat_flexibility_p2h_boiler_electricity: 300.0
wtp_of_energy_heat_flexibility_p2h_heatpump_electricity: 300.0
capacity_of_energy_heat_flexibility_p2h_boiler_electricity: 63780.9
capacity_of_energy_heat_flexibility_p2h_heatpump_electricity: 21489.2`



![Screenshot 2024-05-22 at 09 54 00](https://github.com/quintel/etsource/assets/150331345/9a9138b7-1744-4e13-a84b-65d23e464822)

**Comment by mabijkerk** [comment]
@kaskranenburgQ isn't this part of the generic issue in https://github.com/quintel/etsource/issues/3080? Can we close this issue?

**Comment by kaskranenburgQ** [comment]
I have added this issue to the descirption of the generic issue in #3080. Will close this issue.
