### ISSUE TITLE
Add specs for document validation

### ISSUE THREAD

**Issue by kaskranenburgQ** [quintel/etsource#3082]
- [ ] Check whether the inputs and outputs for all carriers add up to 1.0 in the node files.
- [ ] Check whether wacc that is inside the node file is equal to the wacc group that is given.
- [ ] Check whether participants in merit have a group that matches the merit_order.level and type.
- [ ] Check whether all V() commands that refer to hardcoded nodes have a valid node inside. 
- For this spec, all V() commands that refer to a GROUP, FILTER, INTERSECTION, SECTOR or EDGE need to be filtered out. The main goal for this spec is to find typos or outdated nodes.

- [ ] Check whether all GROUPS have valid groups inside. This also needs to check the G() command.
- [ ] Check whether all SECTORS have valid sectors inside. 
- [ ] Check whether all EDGE commands have valid edges inside.

**Comment by mabijkerk** [comment]
From #3033. Closing that issue as it's covered here.

> Energy nodes may have `wacc` attribute that is set at either 2%, 3%, 4% or 7%. Nodes that have a `wacc` attribute should have a matching node group `wacc_proven_tech`, `wacc_unproven_tech` etc.
> 
> We should write Semaphore test that, for all energy nodes in the graph, checks that for those with a `wacc` attribute, the value of the attribute and the label of the group align.

**Comment by mabijkerk** [comment]
> Check whether the inputs and outputs for all carriers add up to 1.0 in the node files.

For some node exceptions would have to be made, notably the hydrogen and gas burners with efficiencies based on LHV >  100%. Preferably, if a spec is added to test this, the relevant node will be assigned a group that actively exempts them from this spec.
