### ISSUE TITLE
Get rid of current solar thermal solution in Households and add it as heat producing technology

### ISSUE THREAD

**Issue by wmeyers** [quintel/etsource#344]
Solar thermal panels are currently modeled in the ETM as an energy saving solution. They don't produce heat, but they basically reduce demand for other heat. It seems that this was implemented in this way because CBS does not report solar thermal heat.

With our change to IEA data we can also get rid of this ugly solution in the ETM, because IEA **does** report solar thermal heat!

**Comment by jorisberkhout** [comment]
Removing milestone.
