### ISSUE TITLE
Manure and corn requirements can reach enormous proportions

### ISSUE THREAD

**Issue by wouterterlouw** [quintel/etsource#417]
If you make a scenario where a lot of biogas is used, the requirements of manure and corn are enormous (combined > 1500 PJ in http://et-engine.com/data/162480/layout)! In the model it is assumed that all this manure and corn is produced domestically, even if the bio-footprint rises to 5.7x NL.

Possibilities:
- do something with `greengas` if the required biogas exceed the available domestic biogas
- maximize the market penetration of biogas CHPs
- ...?

**Comment by marliekeverweij** [comment]
Not relevant anymore due to biomass update last summer
