### ISSUE TITLE
Coal-fired and lignite-fired power plants do not have O&M costs consistent with CHPs 

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etsource#620]
This is a research issue. It is about who is right. Our sources for coal-fired power plants (none too recent) or the EnergyMatters report detailing O&M costs for coal-fired power plants with district-heating (Central coal CHPs)?

The two have to somehow be made consistent. co-firing plant is also involved as it was derived from the standard plant.

The following plants are affected:
- [ ] energy_power_ultra_supercritical_coal
- [ ] energy_power_ultra_supercritical_cofiring_coal
- [ ] energy_power_ultra_supercritical_lignite

**Comment by jorisberkhout** [comment]
Reopening this issue as I would like to validate the node source analysis before closing it. The current status of all node source analyses is documented in [this Dropbox file](https://www.dropbox.com/s/dah2t2wo9u2x2e0/20150120_status_overview_node_source_analyses.xlsx?dl=0).

**Comment by jorisberkhout** [comment]
@mariatsagkaraki has updated the specs. Assigning myself to validate.
