### ISSUE TITLE
Improve refinery modelling

### ISSUE THREAD

**Issue by wouterterlouw** [quintel/etsource#725]
*Follow-up to issue https://github.com/quintel/etsource/issues/615*

#### Introduction

Refineries transform crude_oil into various oil products. These oil products are subsequently consumed in various sectors, including the industry (e.g. naphtha) and transport sector (e.g. gasoline and diesel).

Currently, only in the transport sector we convert `crude_oil` into more specific carriers, such as `gasoline` and we do that with an efficiency that resembles the aggregated efficiency of the refinery sector (e.g. in the [energy_production_diesel](https://github.com/quintel/etsource/blob/master/nodes/energy/energy_production_diesel.converter.ad#L3) converter).

However, all other sectors just use `crude_oil` that does not flow though a converter that accounts for the refinery losses. Nevertheless, the '`crude_oil`' these sectors use are merely 'oil_products' produced by a refinery.

For the NL 2011 this results in disregarded refinery losses for oil use outside the transport sector. In the NL the oil products use is appr. 600 PJ in the transport sector and appr. 700 PJ in the other sectors; resulting in 700 PJ / 0.92 = 760 PJ --> 60 PJ of disregarded primary crude oil demand.

#### Calculation of efficiency

On the IEA energy balance refineries are specified under transformation and own use. The aggregated efficiency of refineries is defined as `transformation output / (transformation input + own use)`, i.e. output divided by all inputs. 

![refinery](https://f.cloud.github.com/assets/4319656/1910618/ee962c62-7d1b-11e3-894c-9517f85ccb54.png)

For the EU (2011) this result in an efficiency of 26,994 PJ / (27,216 PJ + 1,934 PJ) = 0.926. See also the [*refinery efficiency analysis*](https://www.dropbox.com/s/3qmdco9qvihsa7j/20140114%20Refinery%20efficiency%20source%20analysis%20%28without%20EB%29.xlsx).

#### Solution

To model also the refinery properties for the non-transport oil-product streams, the following graph structure could be implemented:

![including refinery](https://f.cloud.github.com/assets/4319656/1910717/1be8167e-7d1e-11e3-9110-0c68dd9fb0b5.png)

1. The crude_oil_distribution converter will manage the production, import and export of crude oil.
2. The crude_oil_refinery converter will convert crude_oil into oil_products an efficiency of appr. 92%. These oil_products are delivered to the sectors or converted further in case of the transport sector.
3. The diesel_production converter (e.o.) will convert oil_products in diesel without further refinery losses.

**Comment by RobTerwel** [comment]
Closed with https://github.com/quintel/etsource/pull/1154
