### ISSUE TITLE
Own use in refineries is included twice

### ISSUE THREAD

**Issue by wouterterlouw** [quintel/etsource#761]
The own use of refineries in currently included twice in the model:

1. The transport fuel converters (energy_production_diesel, _gasoline, _heavy_fuel_oil, _kerosene and _lpg) do have an efficiency of appr. 92%, calculated by the aggregate `transformation output / (transformation input + own use)`. See the *Calculation of efficiency* part of https://github.com/quintel/etsource/issues/725. This method leads to an additional crude oil consumption of 42 PJ (consumption * (1 - eff) = 482 PJ * 0.08).

2. The own use of the energy industry (except for own use in electricity, CHP and heat plants; blast furnaces and coke ovens) is included in the final demand of the industry sector. See for example the [industry_final_demand_coal](https://github.com/quintel/etsource/blob/master/nodes/industry/industry_final_demand_coal.final_demand.ad) node. This result also in the inclusion of the own use in refineries, resulting in an additional consumption of 173 PJ: 
 - 51 PJ natural gas
 - 84 PJ refinery gas
 - 10 PJ non-specified oil products
 - 11 PJ electricity
 - 16 PJ heat

In the first case, the refinery own use is dependent on the demand of transport fuels, where in the second case, the refinery own use is included in the Other industry sector and does not follow demand for refinery products.

**Comment by ChaelKruip** [comment]
I think this is still relevant because the pull requests mentioned above have not been merged in the end. Re-opening.
