### ISSUE TITLE
Two attributes are only used by one node. Can we get rid of them?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#785]
Hardly used attributes:
- cost_of_installing = 1000.0 is the only non-zero value (for households_water_heater_fuel_cell_chp_network_gas) for all other nodes this is zero. @AlexanderWirtz could we just incorporate this 1000 EUR into the initial_investment?
- decommissioning_costs (only used for energy_power_nuclear_gen3_uranium_oxide)

Remaining from (https://github.com/quintel/etsource/issues/202)

**Comment by marliekeverweij** [comment]
Closing, because there is already this issue: https://github.com/quintel/etsource/issues/915
