### ISSUE TITLE
Low energy lightbulb needs cost parameters

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#793]
The following parameters should be researched and added to the ``` households_lighting_efficient_fluorescent_electricity``` converter:

* Investment cost
* Lifetime
* ...?

**Comment by jorisberkhout** [comment]
Reopening this issue as I would like to validate the node source analysis before closing it. The current status of all node source analyses is documented in [this Dropbox file](https://www.dropbox.com/s/dah2t2wo9u2x2e0/20150120_status_overview_node_source_analyses.xlsx?dl=0).

**Comment by jorisberkhout** [comment]
@mariatsagkaraki has updated the specs in https://github.com/quintel/etdataset/commit/5ddf6582ce5da8f42a1eaf90c455a1bb541e79f2. Assigning myself to validate.

**Comment by jorisberkhout** [comment]
Part of #797. Closing this issue.
