### ISSUE TITLE
Use quantitative data for behavioral sliders

### ISSUE THREAD

**Issue by JonasVoorzanger** [quintel/etsource#794]
The behavioral sliders have ambiguous descriptions. The slider "Turn down heating" (as seen below, or [in the ETM](http://pro.et-model.com/scenario/demand/households/behavior)) could be interpreted as turning all the heating down. If you assume that, it's very surprising that the heat demand only decreases a little bit.

![image](https://cloud.githubusercontent.com/assets/5858426/2971593/2591040e-db6c-11e3-9b52-73dba6d3a18d.png)
![image](https://cloud.githubusercontent.com/assets/5858426/2971605/367e7b02-db6c-11e3-9192-2c131867a9b1.png)

This particular slider (key = "households_behavior_close_windows_turn_off_heating") executes the following query:

```
 UPDATE(V(households_old_houses_useful_demand_for_heating,households_new_houses_useful_demand_for_heating), preset_demand, NEG(DIVIDE(USER_INPUT(),V(15.0))))
```

The result is that de maximum reduction in heat demand is 1/15 = 6.7%, and not the expected 100%.

It would be nice if this slider (and the other behavioral sliders) are changed so that...
- The slider represents the actual reduction in heat demand; OR
- The slider name shows that it's only reducing part of the heat; AND
- The information (?-button) explains why only 6.7% can be reduced by using quantitative data.

**Comment by ChaelKruip** [comment]
Removing Deploy milestone.

**Comment by AlexanderWirtz** [comment]
@ChaelKruip why has this scenario been assigned to me? I haven't the faintes how these sliders work and do not like them either. Let's agree on how to close this issue
