### ISSUE TITLE
Inconsistency between network_capacity_used_in_mw and actual peak load due to installed capacities.

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#875]
In the queries that calculate the peak load on the various parts of the network we currently add the **delta** due to changed slider settings
```
QUERY_DELTA( -> {SUM(V(Q(network_lv_net_converters),"simult_we*peak_load_in_mw")) })
```
 to the occupied capacity for that part of the network
```
V(energy_power_lv_network_electricity, network_capacity_used_in_mw).
```

The result of this sum will not be the same as the result of
```
SUM(V(Q(network_lv_net_converters),"simult_we*peak_load_in_mw"))
```
which, ideally, should be the same.
Perhaps we could find out by how much they differ.

**Comment by jorisberkhout** [comment]
> I understand this better now: the `V(energy_power_lv_network_electricity, network_capacity_used_in_mw)` is the average occupation of the network. This is assumed to be always there...

Correct (average over time, that is). The `V(energy_power_lv_network_electricity, network_capacity_used_in_mw)` is an estimate of the load on the network as a result of all technologies connected to the LV network. On top of this 'baseload' we calculate the load on the LV network as a result of a number of selected technologies that have a large impact on the network load. These technologies are specified in `network_lv_net_converters.gql` and include the usual suspects like heat pumps and electric vehicles.

> Still I am a bit confused as to why the peak load of all converters attached to the network (e.g., `SUM(V(Q(network_lv_net_converters),"simult_we*peak_load_in_mw")))` is roughly an order of magnitude smaller than the `V(energy_power_lv_network_electricity, network_capacity_used_in_mw)`.

In a default NL 2012 scenario, these selected technologies (i.e. the ones in `network_lv_net_converters.gql`) make up only a small fraction of all technologies connected to the LV network, which becomes clear by comparing the energy demands of these technologies compared to all technologies (I know energy demand is not the same as load).

`SUM(V(Q(network_lv_net_converters),demand)) = 27,556,383,096.62665`
`V(energy_power_lv_network_electricity, demand) = 223,547,779,846.69257`

The hardcoded `V(energy_power_lv_network_electricity, network_capacity_used_in_mw)` will be replaced by a distribution of average occupation of LV networks as a part of the network calculation improvement.

Closing this issue. @ChaelKruip , please re-open if anything is unclear.
