### ISSUE TITLE
A central_chp node group should be made

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#887]
If we want to compensate central CHPs for the heat they produce (see https://github.com/quintel/etsource/issues/236), we have to be able to distinguish them from other CHPs that are not capable of selling their heat.

This can most easily be done with a new converter group. I propose a group named `central_chps`.

**Comment by TessColijn** [comment]
I made an overview of all the groups that CHP converters are currently involved in:

Converter | `costs_chps`| `must_run_electricity_production` | `dispatchable_production`| `heat_production` | `electricity_ production`
------------ | ------------- | ---------- |--------- | ---------|---------
agriculture_chp_engine_biogas | Yes | Yes | Yes | Yes
agriculture_chp_engine_biogas_dumped_heat | No | No | No | No
agriculture_chp_engine_network_gas | Yes | Yes | Yes | No
agriculture_chp_supercritical_wood_pellets | Yes | Yes | Yes | Yes
buildings_chp_engine_biogas | Yes | Yes | Yes | Yes
buildings_chp_engine_biogas_dumped_heat| No | No | No | No
buildings_collective_chp_network_gas	| Yes | Yes | Yes | Yes
buildings_collective_chp_wood_pellets | Yes | Yes | Yes | Yes
energy_chp_combined_cycle_network_gas	| Yes | No | Yes | Yes
energy_chp_supercritical_waste_mix| Yes | Yes | Yes | Yes
energy_chp_ultra_supercritical_coal | Yes | No | Yes | Yes
energy_chp_ultra_supercritical_cofiring_coal | Yes | No | Yes | Yes
energy_chp_ultra_supercritical_lignite	| Yes | No | Yes | Yes
households_collective_chp_biogas| Yes |Yes | Yes | Yes
households_collective_chp_biogas_dumped_heat | No | No | No | No
households_collective_chp_network_gas | Yes | Yes | Yes | Yes
households_collective_chp_wood_pellets | Yes | Yes | Yes | Yes
households_space_heater_micro_chp_network_gas | Yes | Yes | Yes | Yes
households_water_heater_fuel_cell_chp_network_gas | Yes | Yes | Yes | No
households_water_heater_micro_chp_network_gas | Yes | Yes | Yes | Yes
industry_chp_combined_cycle_gas_power_fuelmix | Yes | Yes | Yes | No
industry_chp_engine_gas_power_fuelmix | Yes | Yes | Yes | No
industry_chp_turbine_gas_power_fuelmix | Yes | Yes | Yes | No
industry_chp_ultra_supercritical_coal | Yes | Yes | Yes | No

**Comment by michieldenhaan** [comment]
Closing, no longer relevant with new heat network modelling
