### ISSUE TITLE
Do we still need peak_load_units_present attribute?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etsource#891]
While reading about the network calculation I noticed that the `peak_load_units_present` attribute used to be 'Calculated in InputExcel', i.e. was a dynamic attribute. At the moment, this attribute is static as it is defined in the `<converter>.ad`. This can't be right.

The good news is that this attribute is only used in one gquery (`yearly_investment_costs_of_hv_net_wind_offshore`) and two methods (`delta_in_capacity_in_mw` and `peak_load_units_delta_for_mv_hv`).

I will come up with a solution as part of the project to improve the network calculation in the ETM that we do together with Alliander.

**Comment by jorisberkhout** [comment]
After https://github.com/quintel/etengine/commit/11b38971ebcd676466a3dbb5e04e81216019e3a3, the `peak_load_units_present` attribute is only used in one Gquery (`yearly_investment_costs_of_hv_net_wind_offshore.gql`) and one method (`delta_in_capacity_in_mw`), that in is turn used in one other Gquery (`hv_net_delta_capacity_decentral.gql`), in which the delta capacity for all converters connected to the HV/MV transformers is summed. This means that the `peak_load_units_present` is only used for a total of 6 converters (see below), even though it is defined for many more.

The name suggests that `peak_load_units_present` has something to do with the number of units in the present scenario and I made an overview of the `peak_load_units_present` and `number_of_units` for the 6 relevant converters. This suggests that the `number_of_units` is indeed very similar to `peak_load_units_present` for these converters, certainly if you keep in mind that the latter has last been updated in 2010. The only exception is `industry_chp_turbine_gas_power_fuelmix`.

| converter | peak_load_units_present | number_of_units (present) |
|:---|:---|:---|
| energy_power_wind_turbine_offshore | 66.7648502700049 | 75.142857142857 |
| energy_power_geothermal | 0 | 0 |
| energy_power_hydro_river | 3.77551020408163 | 3.7037037037037 |
| energy_power_wind_turbine_coastal | 68.7285223367698 | 261.290148148148 |
| energy_power_wind_turbine_inland | 371.134020618557 | 476.331666666666 |
| industry_chp_turbine_gas_power_fuelmix | 0 | 10.0912603322868 |

To quickly check the effect of replacing the `peak_load_units_present` by `number_of_units` (present), I changed the value of the `peak_load_units_present` attribute for the above 6 converters to the value in the right hand column. This has no effect whatsoever on any of the existing scenarios (default, Energieakkoord 2023, RLI 95% and Urgenda).

So, to cut a (very) long story short, let's remove the `peak_load_units_present` attribute from all converters and, where used, replace it by the `number_of_units` (present value).

Any objections, @ChaelKruip , @AlexanderWirtz or @dennisschoenmakers ?

**Comment by AlexanderWirtz** [comment]
No objections as long as we test this very well.

**Comment by ChaelKruip** [comment]
Fine by me! :+1:

**Comment by jorisberkhout** [comment]
Moving to February deploy milestone.

**Comment by jorisberkhout** [comment]
Not deploy critical, removing milestone.

**Comment by jorisberkhout** [comment]
@marliekeverweij removed this attribute and all the instances where it is used in https://github.com/quintel/etsource/pull/1712/commits/1c3cc4499b7139960a630afae80813f840cfd185. Closing.
