### ISSUE TITLE
The loss of load graph should be different on beta and on live

### ISSUE THREAD

**Issue by mariatsagkaraki** [quintel/etsource#906]
The loss of load graph should be different on beta and on live as the meaning of the attributes has been changed on beta.

On beta:
![screen shot 2015-01-20 at 09 33 10](https://cloud.githubusercontent.com/assets/8480544/5814087/bb7ba7ae-a087-11e4-9baa-af0009904c34.png)

On live:
![screen shot 2015-01-20 at 09 33 22](https://cloud.githubusercontent.com/assets/8480544/5814097/cd77096c-a087-11e4-9799-e42d9f352acb.png)

Assigning @ChaelKruip  to check it

**Comment by ChaelKruip** [comment]
The numbers are different but very similar. I think this is correct :smile: Closing
