### ISSUE TITLE
The loss of load in REH scenario is different on beta and on live

### ISSUE THREAD

**Issue by mariatsagkaraki** [quintel/etsource#907]
The loss of load in REH scenario is different on beta and on live.

On beta:
![screen shot 2015-01-20 at 09 45 55](https://cloud.githubusercontent.com/assets/8480544/5814356/edee3370-a08a-11e4-9dc0-28c1044c3647.png)

 On live:
![screen shot 2015-01-20 at 09 46 08](https://cloud.githubusercontent.com/assets/8480544/5814360/fd9a9c28-a08a-11e4-8cf8-9730fb0f5887.png)

How this difference can be explained?

Assigning @jorisberkhout to check it

**Comment by ChaelKruip** [comment]
@mariatsagkaraki what do you mean by "REH"?

**Comment by mariatsagkaraki** [comment]
sorry the 100% scenario 2030

**Comment by jorisberkhout** [comment]
Well spotted, @mariatsagkaraki . This is a result of the new way of calculating the LOLE. I believe this is correct. Closing.
