### ISSUE TITLE
Some carrier prices need to be updated

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#911]
In https://github.com/quintel/etsource/commit/03e9ea5ceadadb32b9596278a51e18327fee134b we updated some fuel prices. Some still need to be done.

**Comment by AlexanderWirtz** [comment]
@ChaelKruip I think these are all done now. How can I quickly see if all required ones have been updated?

**Comment by ChaelKruip** [comment]
You can look at the time-stamps on the carrier files to see how long ago they have been updated [on Github](https://github.com/quintel/etsource/tree/master/carriers)

**Comment by ChaelKruip** [comment]
@AlexanderWirtz can we close this?

**Comment by ChaelKruip** [comment]
Moved to next deploy.

**Comment by jorisberkhout** [comment]
@AlexanderWirtz , what is the status of this?

**Comment by AlexanderWirtz** [comment]
Closing this isue won't hurt. We still want to update carrier prices everytime we deploy. in the interest of testing, we usually do this after we deploy, right @ChaelKruip ?

**Comment by ChaelKruip** [comment]
> right @ChaelKruip ?

True

**Comment by jorisberkhout** [comment]
> Closing this issue won't hurt.

Let's close it then.
