### ISSUE TITLE
Peak load of must-run CHPs is not consistent with actual load profiles from Merit

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#912]
This issue is not very urgent but becomes more relevant with the effort to improve the network-expansion cost calculation:

The maximum load a must-run CHP is calculated from its input capacity (by ETE). This is used to assess how much it impacts the network.
At the same time, the must-run profile is used to decide what its capacity at any time is. 

In Merit, the must-run profile is scaled to match the total **electricity production** of the CHP. If we were to divide the resulting profile by the output capacity of the CHP, we would get a profile that should be between 0 and 1 at all times. 0 means that the CHP is off, 1 means that it is running at full capacity. So, it basically describes the load factor in time. The integral under that new curve represents the FLHs of the CHP. There currently is no check that the FLHs (from the CHP/power plant analysis) of a must-run CHP actually equals the integral under the load factor curve and it probably never actually matches.

Is that bad? Well, it is a bit ugly that CHPs might be running at capacities larger than their actual capacity or never reach their full capacity (depending on the scaling). On the positive side, we can use the discrepancies between the FLHs (from the CHP/power plant analysis) and the integral under the load factor curve as a measure of consistency between the load profiles we are using and the results of the CHP analysis.

**Comment by ChaelKruip** [comment]
> ...we can use the discrepancies between the FLHs (from the CHP/power plant analysis) and the integral under the load factor curve as a measure of consistency between the load profiles we are using and the results of the CHP analysis.

I will propose such a check and a way of implementing it.

Assigning to myself.

**Comment by ChaelKruip** [comment]
Moving to next deploy

**Comment by ChaelKruip** [comment]
Just a quick check for the start-scenario of the ETM showing only must-run CHPs where their load-curve is divided by their installed capacity:
![figure_1](https://cloud.githubusercontent.com/assets/1303760/12588088/589005d2-c457-11e5-8e19-59b66fe09d97.png)
Curves that exceed the dashed line at 1 represent CHPs that with loads that are higher than their total installed capacity. Fortunately, this is only the case for the `energy_chp_supercritical_waste_mix`.

**Comment by ChaelKruip** [comment]
If I install a bit* of each must-run technology in the ETM you see that there are actually five must-run technologies for which load > cap at some point:
![figure_1](https://cloud.githubusercontent.com/assets/1303760/12588581/93d1d52e-c459-11e5-8813-5bd41c983683.png)

*Note that it does not matter how much of a technology is installed to check if the ratio of load-curve and installed capacity is correct because that only depends on the FLHs of the technology and the shape of the load-profile).

Note also that it does not matter whether the Merit Order is 'on' or not because the must-run always runs.

**Comment by ChaelKruip** [comment]
I think that a check for consistency of profiles with FLHs should be part of the dataset analysis (in particular the CHP analysis). This also ties in with availability (https://github.com/quintel/etmodel/issues/1936)

**Comment by jorisberkhout** [comment]
Closing as this is part of the broader issue described in https://github.com/quintel/etmodel/issues/2803.
