### ISSUE TITLE
Can these node attributes be removed?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etsource#915]
While looking into https://github.com/quintel/etsource/issues/891 and https://github.com/quintel/etsource/issues/785, I realised that more node attributes are no longer or hardly used. @ChaelKruip and I had a look at the list of all node attributes and believe that the following attributes can be removed. Do you have any objections, @antw , @dennisschoenmakers and @AlexanderWirtz ? Including @ChaelKruip .
- `cost_of_installing` (nonzero for only 4 nodes, could be incorporated in `initial_investment`)
- `decommissioning_costs` (nonzero for only 1 node, could be incorporated in `initial_investment`)
- `electrical_efficiency_when_using_coal` (no longer used)
- `electrical_efficiency_when_using_wood_pellets` (no longer used)
- `forecasting_error` (no longer used)
- `part_load_efficiency_penalty` (no longer used)
- `part_load_operating_point` (no longer used)
- `peak_load_units_present` (no longer used)
- `residual_value` (no longer used)
- `simult_supply` (no longer used)

We were not sure about the following two, but it feels like one of them is redundant. Can you shine your light on this, @antw ?
- `demand_expected_value`
- `expected_demand`

**Comment by antw** [comment]
> We were not sure about the following two, but it feels like one of them is redundant. Can you shine your light on this, @antw ?
>
> * `demand_expected_value`
> * `expected_demand`

Both originate in the old InputExcel analysis and *should* be safe-to-delete. `demand_expected_value` is still used within ETEngine (to build [this page](http://beta.et-engine.com/data/latest/checks/expected_demand)) but I'm 90% sure the attribute is entirely internal and can removed from Atlas/ETSource.

I suggest deleting them all; if nothing breaks we can merge the change.

**Comment by ChaelKruip** [comment]
> but I'm 90% sure the attribute is entirely internal and can removed from Atlas/ETSource.

I thought that `demand_expected_value` is initialised by Refinery and then, later, compared to what ETEngine actually calculates for the demands of the nodes. I distinctly remember the smileys on that page being 'sad' after we ditched the Input Excel which implies that the check is still useful. I would therefore suggest to keep `demand_expected_value` unless what I've said above is not true :wink:

**Comment by antw** [comment]
> I thought that `demand_expected_value` is initialised by Refinery and then, later, compared to what ETEngine actually calculates for the demands of the nodes.

The *value* comes from Refinery, but the name – `demand_expected_value` – doesn't exist exists outside of ETEngine. Refinery only uses a `demand` attribute, and ETEngine later decides [whether to set `preset_demand` or `demand_expected_value`](https://github.com/quintel/etengine/blob/master/app/models/etsource/dataset/import.rb#L170-L174)

**Comment by ChaelKruip** [comment]
> The value comes from Refinery, but the name – demand_expected_value – doesn't exist exists outside of ETEngine. 

Thanks for unclogging my thinking :smile:

**Comment by AlexanderWirtz** [comment]
Joris, although the ETM doen not use these attributes in any way, they do represent interesting or relevant information about these nodes (when filled). That means that the attributes can be removed as far as I am concerned, but that they should o be removed from the etdataset node_source_analyses.

Lemme explain: the output of these node source analyses should of course correspond to whatever we decide to use in etsource, but how we arrive at those numbers should be explicitly documented in etdataset.

e.g.:
If `initial_investment` comprises several kinds of up-front costs like:

- PV module costs
- Inverter costs
- Cost of installing
- Balancing costs
- etc

we should document this in the source analysis file (on the `research-data` sheet), so we are transparent about where these numbers come from.

In a similar way, interesting and relevant information (to be used in future, I am sure) like part-load operating points, should be visible in etdataset node source analyses.

**Comment by jorisberkhout** [comment]
Not deploy critical, removing milestone.

**Comment by marliekeverweij** [comment]
Would be nice to remove these redundant node-attributes :) I think some have already been removed in the meantime (almost four years!) and these ones can be deleted: 

-     cost_of_installing (nonzero for only 7 nodes, could be incorporated in initial_investment)
-     decommissioning_costs (nonzero for only 6 nodes, could be incorporated in initial_investment)
-     forecasting_error (no longer used)
-     part_load_efficiency_penalty (no longer used)
-     part_load_operating_point (no longer used)
-     energy_balance_group (not sure about this, @antw?)

**Comment by antw** [comment]
> energy_balance_group (not sure about this, @antw?)

This isn't used anywhere in ETEngine nor in any input or query in ETSource. It should be safe to remove.
