### ISSUE TITLE
Why does the add-on heat pump not work as a demand-driven converter?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#918]
The [add-on heat pump](https://github.com/quintel/etsource/blob/master/nodes/households/households_space_heater_heatpump_add_on_electricity.converter.ad) should actually behave as other heating and hot water technologies in households: the number_of_units should be defined by:
```
number_of_units = slider_setting * number_of_residences
```
To make that work, the ```households_supplied_per_unit``` should be defined and the node should be part of the ```demand_driven``` group.

Somehow this does not work for the add-on heat pump.

**Comment by ChaelKruip** [comment]
It turns out that the ['tech_share'](https://github.com/quintel/etengine/blob/master/app/models/qernel/demand_driven_converter_api.rb#L65) is not updated for this technology. Perhaps because it is not part of a slider-group?

**Comment by ChaelKruip** [comment]
Moving to next deploy because this is actually stable for now.

**Comment by jorisberkhout** [comment]
Is still issue still relevant, now that we removed the add-on heat pump, @ChaelKruip ?

**Comment by ChaelKruip** [comment]
> Is still issue still relevant, now that we removed the add-on heat pump, @ChaelKruip ?

Nope
