### ISSUE TITLE
P2H node should be properly connected to the graph

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#921]
Currently it has no connections. I think it should replace the add-on heat pump for hot water. 
The reasons for this are:
* The add-on heat pump currently does not produce hot water (only space heating) so the edge from the add-on to hot water could be connected to the P2H node instead
![etengine_dev_data_latest_layout_edit](https://cloud.githubusercontent.com/assets/1303760/7631645/2c16aba0-fa45-11e4-9c08-6176ee10479c.png)
* The P2H node is similar to the add-on heat pump (and solar thermal panels) in the sense that it **reduces** the hot water demand rather than fulfils it. 

The reason I am not doing this right now is that it is quite an operation with a lot of renaming of nodes, edges, gqueries, update statements and node analyses.

**Comment by ChaelKruip** [comment]
I am logging what is being changed for compatibility reasons with ETDataset:

- [ ] rename `households_useful_demand_for_hot_water_for_houses_with_add_on` -> households_useful_demand_for_hot_water_for_houses_with_p2h
- [ ] rename `households_space_heater_heatpump_add_on_electricity-households_useful_demand_for_hot_water_for_houses_with_add_on@useable_heat` -> `households_flexibility_p2h_electricity-households_useful_demand_for_hot_water_for_houses_with_add_on@useable_heat`

**Comment by ChaelKruip** [comment]
TODO:

- [ ] fix shares in `households_useful_demand_for_hot_water_after_solar_heater_and_add_on-households_useful_demand_for_hot_water_for_houses_with_p2h@useable_heat`

**Comment by jorisberkhout** [comment]
Changing milestone to 'Deploy January 2016'.
