### ISSUE TITLE
FCE attributes for crude_oil, greengas and wood pellets carriers should be specified in the nl/datasets/fce folder individual yml files

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etsource#927]
All FCE carriers have these attributes specified in `<carrier_name>.yml` files in the `./datasets/nl/fce` directory of etsource, except for `crude_oil`, `greengas` and `wood_pellets`. For these carriers, the FCE attributes are specified in the global `<carrier_name>.ad` files. There is a good reason for this: these FCE carriers don't allow users to specify a mix of origins. 

Nonetheless, the FCE attributes now specified in the `<carrier_name>.ad` files are only valid for the Netherlands, and not global at all. Since we have started creating systematic documentation for these carriers on etdataset - we want to be open source and transparent after all - that makes the current approach confusing.

I am talking about the following attributes:

- `co2_exploration_per_mj`
- `co2_extraction_per_mj`
- `co2_treatment_per_mj`
- `co2_transportation_per_mj`
- `co2_waste_treatment_per_mj`

@jorisberkhout please be aware of this issue for etdataset issues [#601](https://github.com/quintel/etdataset/issues/601) and [#606](https://github.com/quintel/etdataset/issues/606) 

@dennisschoenmakers I know this seems a but trivial, but if we are to win over academics and students and get them to actually use the data in the ETM, we need to try an be transparent. I am open to suggestions.

**Comment by dennisschoenmakers** [comment]
Assigned to @grdw. 

@grdw: please have a meeting first with @AlexanderWirtz to discuss this issue throughly: the background of 'the problem', how it currently works, how it should work, the caveats and the interdependencies with **etdataset**. In other words: enough to talk about! :smile:

**Comment by AlexanderWirtz** [comment]
IT would be great to see if we can somehow come up with a solution that would in principal allow FCW for other countries as well.

**Comment by grdw** [comment]
What I'll do locally is:
- [ ] Move the attributes to the 'ideal' situation. 
- [ ] Run the specs from etsource to see if anything already breaks. 
- [ ] Boot etengine locally 
- [ ] Run those specs aswell 
- [ ] Discuss with either you or @jorisberkhout  what is suppose to happen (if anything broke).

**Comment by AlexanderWirtz** [comment]
@grdw the 'ideal' situation being the folder `./datasets/nl/fce`? In that case, go ahead and see what breaks! :-) I am available to comment on what should happen.

**Comment by grdw** [comment]
> the 'ideal' situation being the folder ./datasets/nl/fce
Yes

**Comment by grdw** [comment]
@AlexanderWirtz  I'm now at the point where I need a password for the `energy_balance.gpg` files in order to run the et-engine locally :innocent:

**Comment by jorisberkhout** [comment]
I believe this can be closed, @grdw ?

**Comment by grdw** [comment]
Yes

**Comment by jorisberkhout** [comment]
:+1:

**Comment by AlexanderWirtz** [comment]
For posterity's sake: the gpg files are decrypted using a password file that lives in the root of etsource, but is included in `.gitignore`
