### ISSUE TITLE
dollar_per_euro.gql is not a good way to store or update the currency exchange rates. Should it be an .ad file?

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etsource#929]
See [etdataset issue 616](https://github.com/quintel/etdataset/issues/616) 

It would be more transparent and less error prone to explicitly store the exchange rate as an `.ad` file in the global dataset. This makes it easy to automate updating this vale from etdataset using a rake task. The current GQL statement (`dollar_per_euro.gql`) is rather awkward as it really just stores a constant value. 

`dollar_per_euro.gql`:

> - query = V(1.1895)
> - unit = $

The question is where this `dollar_per_euro.ad` file should live. This is global data. In the future we will also use other currencies. Poland and Mexico are both interested in an ETM for their countries. We could create `peso_per_euro.ad` and `zloty_per_euro.ad` files next to the `dollar_per_euro.ad` file proposed.

This GQL statement is needed by etmodel to recalculate carrier prices that are normally quoted in dollars. 
@jorisberkhout

**Comment by jorisberkhout** [comment]
Assigning myself as we need to to make sure this is consistent with the carrier documentation, which @AlexanderWirtz and I looked into a while ago.
