### ISSUE TITLE
heavy_fuel_oil does not contain price information. it should

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etsource#930]
This carrier ad file does not contain price information, whereas its costs should be included in the cost calculation. Almost all carriers have price information. 

@jorisberkhout should we fix this? etdataset has the relevant info. Just as for gasoline and diesel I suggest adding the following attributes to the `heavy_fuel_oil.ad` file:

- cost_per_mj
- mj_per_kg
- kg_per_liter

@ChaelKruip does the cost calculation calculate costs for final or primary use of fuels? I mean, does it avoid double counting costs for `gasoline` and `crude_oil`, for example?

Who will include this carrier in the cost calculation?

**Comment by AlexanderWirtz** [comment]
The same seems to go for `kerosene' but I haven't found the data for it yet.

**Comment by AlexanderWirtz** [comment]
Data for jet fuel / `kerosene` now also documented

**Comment by jorisberkhout** [comment]
As of https://github.com/quintel/etsource/commit/117230dd8737b4bf2401e0f16962243b450816fe, these two carriers (`heavy_fuel_oil.ad` and `kerosene.ad`) have price information.

However the second part of the issue remains open. Assigning @ChaelKruip .

> @ChaelKruip does the cost calculation calculate costs for final or primary use of fuels? I mean, does it avoid double counting costs for gasoline and crude_oil, for example?

**Comment by jorisberkhout** [comment]
Assigning myself as I am already looking into this.

**Comment by jorisberkhout** [comment]
> @ChaelKruip does the cost calculation calculate costs for final or primary use of fuels? I mean, does it avoid double counting costs for gasoline and crude_oil, for example?

I have checked this by manually removing the cost attributes for these carriers which does not change the dashboards costs. I did the same for those carriers that did not have a CO2 attributes before, which also does not cause any differences.

Closing.
