### ISSUE TITLE
Heat pump add-on should work with demand_driven method

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#937]
In https://github.com/quintel/etsource/commit/bd177d079db3ad49b956acd59399291207e89f55 we reverted a commit that made the households_space_heater_heatpump_add_on_electricity 'demand driven'. Actually, we want that functionality back at some point!

The desired behaviour is that the number_of_units of the add-on are set to the number_of_households and the full_load_hours of the add-on are flexible (react to the energy demand).

This seems to work fine **except** for the start-year where the number_of_units do not correspond to the slider setting but rather to the a number equivalent to 60% of all houses. Curiously, 60% also is the share of the heat that is diverted to the add-on from `households_useful_demand_for_space_heating_after_insulation_for_houses_with_add_on`.

**Comment by ChaelKruip** [comment]
Including @jorisberkhout @dennisschoenmakers

**Comment by ChaelKruip** [comment]
This is something of a duplicate of https://github.com/quintel/etsource/issues/918

**Comment by jorisberkhout** [comment]
Is still issue still relevant, now that we removed the add-on heat pump, @ChaelKruip ?

**Comment by jorisberkhout** [comment]
Closing this as we no longer have add-on heat pumps in the ETM.
