### ISSUE TITLE
How could we update the efficiency of converters?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#942]
In light of https://github.com/quintel/etmodel/issues/1870 I am looking at how to make the efficiency of converters dependent on sliders. 

@antw is it possible to change the efficiency of a node in the same way as we do with `initial_investment` for example? Should I use the `output.electricity` attribute for that? Another option is `electricity_output_conversion` but that seems to be a method rather than an attribute...

**Comment by antw** [comment]
> Should I use the output.electricity attribute for that? Another option is electricity_output_conversion but that seems to be a method rather than an attribute...

`output.electricity` is a Atlas/ActiveDocument convention to set the `conversion` of the `electricity` output slot. If you wanted to change the efficiency of a converter in ETEngine with an Input, I guess you'd want to do something like this:

```ruby
UPDATE(OUTPUT_SLOTS(__CONVERTER_KEY__, electricity), conversion, USER_INPUT())
```

This assumes that `USER_INPUT()` is already a factor (0.2, rather than 20 (%)), so you would want to also set the Input `update_type` to "%":

```
- query = UPDATE(OUTPUT_SLOTS(energy_power_solar_csp_solar_radiation, electricity), conversion, USER_INPUT())
- priority = 0
- max_value = 100.0
- min_value = 0.0
- start_value = 0.0
- step_value = 1.0
- unit = %
- update_period = future
- update_type = %
```

**Comment by ChaelKruip** [comment]
:+1:

**Comment by ChaelKruip** [comment]
I have used the following input statement
```
# Increase the efficiency of solar PV panels

- query =
    EACH(
        UPDATE(OUTPUT_SLOTS(V(energy_power_solar_csp_solar_radiation), electricity), conversion, USER_INPUT() / 100.0),
        UPDATE(OUTPUT_SLOTS(V(buildings_solar_pv_solar_radiation), electricity), conversion, USER_INPUT() / 100.0),
        UPDATE(OUTPUT_SLOTS(V(energy_power_solar_pv_solar_radiation), electricity), conversion, USER_INPUT() / 100.0)
    )

- priority = 100
- max_value = 100.0
- min_value = 0.0
- start_value_gql = present:V(households_solar_pv_solar_radiation, "100 * electricity_output_conversion")
- step_value = 0.1
- unit = %
- update_period = future
- update_type = %
```
in the front-end using this:
```
INSERT INTO `input_elements` (`id`, `key`, `share_group`, `step_value`, `created_at`, `updated_at`, `unit`, `fixed`, `comments`, `interface_group`, `command_type`, `related_converter`, `slide_id`, `position`)
VALUES
	(NULL, 'efficiency_of_solar_pv', '', 0.1, '2015-08-31 09:04:03', '2015-08-31 09:45:23', '%', 0, '', 'Efficiency', 'efficiency_improvement', '', 5, 3);
```

Unfortunately, the efficiency does not seem to change...

NOTE: I have put the priority of the update statement to '100' in line with [this update statement](https://github.com/quintel/etsource/blob/master/inputs/supply/coal_plant_fuel/co_firing_biocoal_share.ad)

**Comment by antw** [comment]
Try replacing `USER_INPUT() / 100.0` with `USER_INPUT()` or remove `- update_type = %`. Setting the update type to `%` already divides the value by 100; you don't need to do this yourself.

You also don't need to use `V()` within the first argument to `OUTPUT_SLOTS`, you can just provide the converter key and save a couple of characters.

I can confirm the update query does work in ETEngine, and the attributes get set. Try this in the sandbox to see:

```ruby
EACH(
    UPDATE(OUTPUT_SLOTS(energy_power_solar_csp_solar_radiation, electricity), conversion, 5.0 / 100.0),
    UPDATE(OUTPUT_SLOTS(buildings_solar_pv_solar_radiation, electricity), conversion, 5.0 / 100.0),
    UPDATE(OUTPUT_SLOTS(energy_power_solar_pv_solar_radiation, electricity), conversion, 5.0 / 100.0)
);

EACH(
    V(OUTPUT_SLOTS(energy_power_solar_csp_solar_radiation, electricity), conversion),
    V(OUTPUT_SLOTS(buildings_solar_pv_solar_radiation, electricity), conversion),
    V(OUTPUT_SLOTS(energy_power_solar_pv_solar_radiation, electricity), conversion)
)
```

**Comment by ChaelKruip** [comment]
> Try replacing USER_INPUT() / 100.0 with USER_INPUT() or remove - update_type = %. Setting the update type to % already divides the value by 100; you don't need to do this yourself.

Thanks. That makes sense!

> I can confirm the update query does work in ETEngine, and the attributes get set.

I found the problem, I was monitoring the `households_solar_pv_solar_radiation` node but I accidentally copied the `energy_power_solar_csp_solar_radiation` in its place :tired_face:

**Comment by ChaelKruip** [comment]
Closing.
