### ISSUE TITLE
New renewability chart does not add up to 100% for Urgenda

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#957]
This chart will be my undoing someday :angry: 

For an extremely sustainable scenario (Urgenda), the queries do not add up to 100%:
<img width="1084" alt="energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_" src="https://cloud.githubusercontent.com/assets/1303760/10078097/8ad62cd6-62e3-11e5-8837-63cddbd1b143.png">

I suggest to keep this chart (including its error) for the coming deploy and fix the bug(s) for the next deploy because the chart is informative and the error seems only to show in extreme cases.

**Comment by ChaelKruip** [comment]
Fixed on BETA and LIVE by adding 'solar' to the database:
![cursor_and_energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_](https://cloud.githubusercontent.com/assets/1303760/10216824/1c7f7c58-682c-11e5-8f35-da8e6355e81d.png)

**Comment by jorisberkhout** [comment]
Very nice!
