### ISSUE TITLE
Demand- Buildings- Difference in district heating

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etsource#961]
There is a difference in the penetration of inputs in the district heating as seen in the screenshots

BETA:
![image](https://cloud.githubusercontent.com/assets/12493788/10163923/6b0975da-66b6-11e5-8b28-4af7a5f7594e.png)

LIVE:
![image](https://cloud.githubusercontent.com/assets/12493788/10163925/71724294-66b6-11e5-9be6-27bfa17228c0.png)

**Comment by jorisberkhout** [comment]
@georgiasavvidou , I am assuming this is for The Netherlands. Is that correct?

**Comment by georgiasavvidou** [comment]
@jorisberkhout  yes! I will make sure to mention that on my next issues!

**Comment by jorisberkhout** [comment]
:+1:

**Comment by ChaelKruip** [comment]
@AlexanderWirtz can this be related to your updates of capacities/efficiencies of CHP?

**Comment by AlexanderWirtz** [comment]
@ChaelKruip same answer as #963
