### ISSUE TITLE
Demand- Agriculture- Differences in inputs for heat

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etsource#963]
In the Netherlands, there are some small differences in the percentages of inputs for heat in Agricultural demand between BETA and LIVE

BETA:
![image](https://cloud.githubusercontent.com/assets/12493788/10164598/a80ba418-66ba-11e5-8fc9-c79d38ee0562.png)

LIVE:
![image](https://cloud.githubusercontent.com/assets/12493788/10164604/b8ab1920-66ba-11e5-942b-f0c673aa1ae9.png)

**Comment by ChaelKruip** [comment]
@AlexanderWirtz can this be related to changes you made in CHP efficiencies/capacities?

**Comment by AlexanderWirtz** [comment]
@ChaelKruip yes it might be related to that. these efficiencies/capacities did change slightly. how exactly this leads to these different slider settings is not yet clear to me.
