### ISSUE TITLE
Costs- Differences in fuel prices between BETA and LIVE

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etsource#964]
In the Netherlands, there is a difference in fuel prices of oil and coal between BETA and LIVE

BETA 
![image](https://cloud.githubusercontent.com/assets/12493788/10165826/7c6c7682-66c1-11e5-861a-74efc05d1025.png)

LIVE
![image](https://cloud.githubusercontent.com/assets/12493788/10165835/82e6b4d2-66c1-11e5-9e0d-ab105964de41.png)

**Comment by ChaelKruip** [comment]
This has been updated indeed. Closing.
