### ISSUE TITLE
CO2 price difference between LIVE and BETA

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etsource#965]
In the Netherlands, there is a difference in CO2 price between BETA and LIVE

BETA
![image](https://cloud.githubusercontent.com/assets/12493788/10165909/cc226e8e-66c1-11e5-9e66-ba11bcbcb090.png)

LIVE
![image](https://cloud.githubusercontent.com/assets/12493788/10165915/d2143c1e-66c1-11e5-9c96-0b1aff38ceb7.png)

**Comment by ChaelKruip** [comment]
Due to update of CO2 price. Closing.
