### ISSUE TITLE
Supply- Fossil heat- difference in number of CHPs between LIVE and BETA

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etsource#966]
In the Netherlands, the number of agriculture biogas and gas CHP is different between the LIVE and the 
BETA:
![image](https://cloud.githubusercontent.com/assets/12493788/10166220/518df2e0-66c3-11e5-9681-645ee1bb4bbc.png)

LIVE:
![image](https://cloud.githubusercontent.com/assets/12493788/10166215/4c1e1902-66c3-11e5-847f-4c151b14a754.png)

**Comment by ChaelKruip** [comment]
Assigning @jorisberkhout

**Comment by jorisberkhout** [comment]
These differences were introduced after the CHP specs were updated, see https://github.com/quintel/etsource/commit/68f423b4eea360c6fa14de18c69aa66c372ad60b as a starting point. Minor differences are to be expected. Closing.
