### ISSUE TITLE
Merit order-future FLH do not round to the nearest 50

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etsource#970]
The Full Load Hours (FLH) for the future do not round to the nearest 50 (which is the case for the present FLH)

![image](https://cloud.githubusercontent.com/assets/12493788/10363105/c58cc34c-6db2-11e5-9a47-ba8eab40b6d4.png)

**Comment by jorisberkhout** [comment]
Interesting find by @georgiasavvidou . Indeed some full load hours are round to the nearest 50, while others aren't.

Take 'Hydro river' as an example. According to the NL/2012 dataset (which is currently running on Beta), the FLH should be 2808, which is indeed the number that I get when I run `V(energy_power_hydro_river, "full_load_hours")` in the GQL Sandbox. Although the same Gquery is ran to determine the content of the table, it is shown as  2800 hours, so I expect the rounding to happen somewhere in HAML.

Other FLH are not rounded as @georgiasavvidou pointed out.

After discussing with @AlexanderWirtz , we believe that NOT rounding the numbers would be better for two reasons:

- The numbers displayed in the table would correspond to the ones in the dataset, increasing transparency
- The user gets a more detailed feedback on the effects of his choices on the merit order

@dennisschoenmakers , @antw, do you object to this change. If not, could you implement this?

**Comment by dennisschoenmakers** [comment]
Just for some historical background: the rounding with less 'significance' was requested and discussed in https://github.com/quintel/etmodel/issues/1312 (year 2013).

**Comment by antw** [comment]
> Just for some historical background: the rounding with less 'significance' was requested and discussed in quintel/etmodel#1312 (year 2013).

Nice find! @ChaelKruip's reasoning for the rounding [in the original issue](https://github.com/quintel/merit/issues/72) is probably still true today. If preferred, we could revert the change and instead ensure that all the FLHs are rounded to 50?

**Comment by ChaelKruip** [comment]
>  @ChaelKruip's reasoning for the rounding in the original issue is probably still true today. 

I guess so but today I'd say that the rounding casues confusion rather than preventing it. Mostly because significance is not taken into account anywhere in the model. Many tables and graphs show numbers at a precision which is actually not to be trusted :grin: So, I would go ahead with @jorisberkhout's suggestion of showing the numbers in hours again.

**Comment by jorisberkhout** [comment]
> So, I would go ahead with @jorisberkhout's suggestion of showing the numbers in hours again.

:relieved: This has already been implemented on Beta.
