### ISSUE TITLE
Do we need a separate converter for regasification of bio-LNG?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etsource#973]
**Background**

After 87a0773684e74189b7e091839df61fcbe8041dd8, the regasification of LNG and bio-LNG are added to the graph as follows

<img width="913" alt="screen shot 2015-10-09 at 09 50 14" src="https://cloud.githubusercontent.com/assets/4669028/10388550/5839792a-6e6b-11e5-8a65-c93692683f0c.png">

As discussed with John we ultimately want to include regasified LNG and regasified bio-LNG in the following chart.

<img width="611" alt="screen shot 2015-10-09 at 09 55 59" src="https://cloud.githubusercontent.com/assets/4669028/10388636/fbd21146-6e6b-11e5-9a7e-919d7af33fb3.png">

**Question**

I am wondering if it would make our lives easier if we add a separate `energy_regasification_bio_lng` converter the output of which we feed directly into the natural gas network? We can then determine the composition of the natural gas in the gas network straight from its four inputs (natural gas, green gas, regasified LNG and regasified bio-LNG), instead of having to work out the split between LNG and bio-LNG in the regasified LNG.

What do you think @ChaelKruip , @RobTerwel ?

**Comment by RobTerwel** [comment]
I'm in favour! Not only does this make our lives easier modelwise, but physically it makes a bit more sense too. One could argue that the regasification process for bio-LNG is slightly different from the one for LNG since it has a higher methane content than LNG and therefore has to be downgraded even more before it is imported into the gas network.

**Comment by ChaelKruip** [comment]
> We can then determine the composition of the natural gas in the gas network straight from its four inputs (natural gas, green gas, regasified LNG and regasified bio-LNG), instead of having to work out the split between LNG and bio-LNG in the regasified LNG.

:+1: In favor!

**Comment by RobTerwel** [comment]
This `energy_regasification_bio_lng` converter has been added in https://github.com/quintel/etsource/commit/a617803efdc376169e6d8b03437a0ad6c5810e06 .

Closing.
