### ISSUE TITLE
Should we add local bio LNG production?

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etsource#974]
For simplicity and for now, there is a bio lng import (see https://github.com/quintel/etsource/commit/2f1e722a69503c76ef0f773cd2a9422bf67ea1b0), but it is also possible to add a local bio LNG production. Bio LNG is the product of liquifying almost pure biomethane obtained from biogas.

Modelwise, it could for instance involve a biogas flow from `energy_distribution_biogas`  to  `energy_production_bio_lng` where it is purified and liquified. The latter converter could then be connected to the existing `energy_distribution_bio_lng`.

@jorisberkhout , @ChaelKruip , what are your thoughts?

**Comment by ChaelKruip** [comment]
> what are your thoughts?

This is hard to visualise like this. Could you include some schematics? Also, what numbers are we talking about? It seems like quite a bit of work so if this only has a minor impact on the front-end it might not be worth it...

**Comment by RobTerwel** [comment]
> Could you include some schematics?

Sure, here goes:

![screen shot 2015-10-12 at 15 55 07](https://cloud.githubusercontent.com/assets/14106387/10429558/bad85610-70f9-11e5-821e-9bda25e04a17.png)

I only included the relevant  part of the overview. The yellow converter is the new, proposed bio-lng production converters; green converters already exist.

> Also, what numbers are we talking about?

There is one large active bio-lng plant which produces just over 1500 tons/year, roughly equivalent to 2.15 million cubic meter natural gas, or about 74 TJ. In addition, several smaller ones, but these production quantities could increase significantly - more and more plans (and plants :) ) are being made.

**Comment by ChaelKruip** [comment]
@RobTerwel what is the status of this?

**Comment by RobTerwel** [comment]
@ChaelKruip I think this can be best described as a 'nice to have' for now. One of the difficulties also is that the EB reported biogas - includes or would include bio LNG - consumption in transport in the Netherlands is 0 TJ (or at least, as Otto Swertz from CBS also said, rounded off to zero). Therefore, even if a `production_bio_lng` converter were to be introduced, it wouldn't have an energy flow yet.

I think it's probably best to close this for now and pick it up later. Do you agree, @ChaelKruip ?

**Comment by jorisberkhout** [comment]
Putting this issue on hold and removing the milestone.

**Comment by michieldenhaan** [comment]
Closing, ``production_bio_lng`` has been added in 2019 biomass project
