### ISSUE TITLE
Things not to forget when removing add-on heat pump and adding hybrid heat pump

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#994]
## Testing

- [x] Add / remove Mechanical Turk tests

## Presets and scenario's
- [x] People with add-on heat pumps in their scenario should get HHP?

## Front-end
- [x] Add / remove for all relevant charts (https://github.com/quintel/etsource/issues/995)
- [x] Add HHP to investment table 

## Back-end

- [x] Converter positions
- [ ] Document how the inputs work and what still needs to be improved about that (https://github.com/quintel/etsource/issues/1002)

## Analyses

- [x] remove heat pump add on from all shares in ET-Source (residences_useful_demand_for_space_heating_after_insulation_for_houses_with_add_on_child_share.csv possibly among other)
- [x] remove heat pump add on from all shares from the analyses in ET-Dataset (which would otherwise 

## ETFlex

- [x] https://github.com/quintel/etflex/issues/434

**Comment by RobTerwel** [comment]
@ChaelKruip , if I may add:

- [ ] remove heat pump add on from all shares in ET-Source 
- [ ] remove heat pump add on from all shares from the analyses in ET-Dataset (which would otherwise be exported again)

But I can take care of some of these things too. :smile:

**Comment by ChaelKruip** [comment]
> @ChaelKruip , if I may add:

Sure! I've added them to the main overview.

> But I can take care of some of these things too. :smile:

That would be great!

**Comment by ChaelKruip** [comment]
Closing.
