### ISSUE TITLE
Looking for a way to change present (and future) demand in scaled scenarios

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etsource#996]
## Intro
When scaling a scenario by number of households, some energy demands can be quite far off from locally known numbers. This is true mostly for areas that are very different from the national 'average' of course. 

Ameland is such a case. We happen to have good and detailed energy statistics for this island in the Wadden Sea (i looked that up :smile:). Nearly all demand in all sectors is off by 50 - 200%. This makes a scenario scaled to 1657 residences not very useful.

## Input statements for `present`
As discussed with @dennisschoenmakers, we know it is possible to create input statements for the present graph. I tried using one in a scenario file to see what would happen:

`agriculture_useful_demand_electricity_present.ad` looks like this:

```
- query = UPDATE(V(agriculture_useful_demand_electricity), preset_demand, USER_INPUT())
- priority = 10
- unit = %
- update_period = present
- update_type = %y
```

and it works... sort of. in this case I set it to an annual change of -11.3%. No other sliders were set in the example below:

![image](https://cloud.githubusercontent.com/assets/308563/11501751/f8edc674-9836-11e5-9f5b-5cbbdf69c542.png)

Lo and behold, it does exactly what you would expect. It lowers the present electricity demand. 
Except: the `agriculture_useful_demand_electricity` slider now is now offset by the `-11.3%` specified in the scenario file for the present graph. Even a maximum decrease allowed of -5% annually cause a rise in electricity demand:

![image](https://cloud.githubusercontent.com/assets/308563/11501855/8cc4c9d8-9837-11e5-819e-6be3ad9f5f27.png)

Unfortunately, the future grap is not re-calculated wrt to the present graph, as I had hoped (against hope) it would. So if one wants to change present demand, one needs to also specify a change in future demand. This is a lot of work and presents other problems as well. For example, any sliders outside of their ranges, can no longer be used, lest they reset towards a value insider their ranges and suddenly grow or shrink a certain demand.

@dennisschoenmakers and @antw please advise.

**Comment by AlexanderWirtz** [comment]
Assigning @dennisschoenmakers for good measure. Feel free to assign back to me or anyone else.

**Comment by AlexanderWirtz** [comment]
Trying with an input statement that updates both `future` and `present`. That works like a charm. 

These statements can be used simultaneously in a scenario file:
````
agriculture_useful_demand_electricity_both: -11.3
agriculture_useful_demand_electricity: -5.0
````
![image](https://cloud.githubusercontent.com/assets/308563/11503346/5a9323f2-9840-11e5-9e95-3149a623409f.png)

Using only 'agriculture_useful_demand_electricity_both` of course lowers demand to the desired level. 

This would only present a problem in case sliders update both future and present.

**Comment by dennisschoenmakers** [comment]
Sometimes the model surprises even the best. :smile:

**Comment by ChaelKruip** [comment]
> This would only present a problem in case sliders update both future and present.

Isn't that what your 'agriculture_useful_demand_electricity_both` does?

> Sometimes the model surprises even the best. 

Yep! :+1:

**Comment by AlexanderWirtz** [comment]
> Isn't that what your 'agriculture_useful_demand_electricity_both` does?

Except that is not a slider. Just an input statement.

I am having trouble setting technology shares this way.
