### ISSUE TITLE
People with add-on heat pumps in their scenario should get HHP

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#998]
I think we should give everyone who has chosen a (no longer existing) add-on heat pump in a scenario, a hybrid heat pump in return. 

The difficulty is that the add-on was an auxiliary technology whereas the HHP is part of the main space heating (and hot water) slider group.

Additional complication is that I think it makes sense if people who get a HHP for space heating also get one for hot water. The add-on only impacted the space heating demand, however.

**Comment by ChaelKruip** [comment]
Both the remaining presets and the database scenario's should get the following 'migration':

* `households_space_heater_heatpump_add_on_electricity_share` should be replace with `households_space_heater_hybrid_heatpump_air_water_electricity_share`
* The `households_space_heater_combined_network_gas_share` should be decreased with the value of `households_space_heater_hybrid_heatpump_air_water_electricity_share` if possible and be set to zero if this decrease is larger than the current value

**Comment by antw** [comment]
> The households_space_heater_combined_network_gas_share should be decreased with the value of households_space_heater_hybrid_heatpump_air_water_electricity_share if possible **and be set to zero if this decrease is larger than the current value**

This would result in the share group not balancing.

Can we instead set the HHP to be `min(add_on_share, combined_network_gas_share)`?

| Before: Combined | Before: Add-on | After: Combined | After: HHP |
|-----------------:|----------------|----------------:|------------|
| 70%              | **30%**        | 40%             | 30%        |
| **20%**          | 30%            | 0%              | 20%        |

We can do it your way but we'd have to re-balance the share group; the HHP share still won't be exactly the same as the add-on share.

**Comment by ChaelKruip** [comment]
> This would result in the share group not balancing.

Good point!

> Can we instead set the HHP to be min(add_on_share, combined_network_gas_share)?

:+1:
